import { Product } from "./types";
import { isRemovedProductSlug } from "./removed-products";

/**
 * Product seed data â€” 18 chemical products (Vasudev Chemo Pharma catalog).
 * Used as a static fallback when the database is unavailable.
 */
const productCatalog: Product[] = [
  // â”€â”€â”€ INDUSTRIAL CHEMICALS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: 1,
    name: "MEA Triazine 78% H2S Scavenger",
    slug: "mea-triazine-78-h2s-scavenger",
    sku: "VCP-IND-0001",
    formula: "C3H9N3",
    casNumber: "4719-04-4",
    category: "industrial",
    subcategory: "Oilfield Chemicals",
    metaTitle: "MEA Triazine 78% H2S Scavenger Manufacturer | Vasudev Chemo Pharma",
    metaDescription: "MEA Triazine (Monoethanolamine Triazine) is a highly effective H2S scavenger for oil & gas, wastewater, and biogas. Buy direct from the manufacturer.",
    description:
      "MEA Triazine, also known as Monoethanolamine Triazine, is a highly effective chemical compound extensively used in various industrial sectors, particularly in the oil and gas industry. It is renowned for its remarkable ability to scavenge hydrogen sulfide (H2S), a toxic and corrosive gas commonly found in natural gas and crude oil. The presence of H2S poses significant risks to both infrastructure and personnel, making its removal a critical process in ensuring safety and operational efficiency.\n\nMEA Triazine offers a cost-effective and efficient solution for reducing H2S levels, thereby protecting equipment from corrosion, improving safety conditions, and ensuring compliance with stringent environmental regulations. Its versatility extends beyond the oil and gas industry, finding applications in wastewater treatment, biogas purification, and other sectors where H2S management is essential. As a clear to pale yellow liquid, MEA Triazine is easy to handle and integrate into various processes, making it a preferred choice for many industries.\n\nThe chemical's ability to react quickly and effectively with H2S, transforming it into non-corrosive and non-toxic byproducts, highlights its importance in maintaining operational integrity. By incorporating MEA Triazine into their processes, industries can enhance their operational efficiency, protect their assets, and contribute to a safer working environment.\n\n### H2S Scavenging Mechanism\nThe process involves a chemical reaction where MEA Triazine reacts with hydrogen sulfide to form stable, non-corrosive byproducts (thiadiazine). This reaction effectively removes H2S from drilling and completion fluids, ensuring the safety and integrity of the operation. Key benefits include protection of equipment from corrosive acids, significant safety improvement for personnel, and ensuring environmental compliance by minimizing H2S release.",
    appearance: "Clear to pale yellow liquid",
    molecularWeight: "177.20 g/mol",
    hsCode: "29336990",
    specs: {
      "Concentration (%)": "78% (Also available in 50%, 60%, 80%)",
      "Appearance": "Clear to pale yellow liquid",
      "pH (as is)": "9.0 - 11.0",
      "Density (g/cmÂ³ at 25Â°C)": "1.20 - 1.25",
      "Viscosity (cP at 25Â°C)": "25 - 35",
      "Freezing Point (Â°C)": "5",
      "Boiling Point (Â°C)": "100",
      "Solubility": "Fully miscible in water",
    },
    safetyClass: "Irritant",
    ghsPictograms: ["GHS07"],
    signalWord: "Warning",
    hazardStatements: [
      "H315 â€“ Causes skin irritation",
      "H319 â€“ Causes serious eye irritation",
      "H335 â€“ May cause respiratory irritation",
    ],
    documents: [],
    applications: [
      "Natural Gas Processing: Removal of H2S to meet pipeline specifications.",
      "Crude Oil Refining: Reducing H2S levels to protect infrastructure and improve safety.",
      "Wastewater Treatment: Odor reduction and prevention of corrosion in facilities.",
      "Biogas Purification: Enhancing gas quality for energy production.",
      "Drilling and Completion Fluids: Critical for personnel safety and equipment protection.",
    ],
    industries: [
      "Oil & Gas",
      "Petrochemicals",
      "Refineries",
      "Biogas & Renewable Energy",
      "Water Treatment",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: ["Industrial Grade", "Oilfield Grade"],
    packaging: [
      "Barrels: 200 liters (Durable and robust)",
      "IBC Totes: 1,000 liters (Bulk storage and transport)",
      "Custom bulk tanker loads",
    ],
    minOrderQuantity: "1 MT",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    imageUrl: "https://atjtpw4vvodv5rtp.public.blob.vercel-storage.com/MEA%20Triazine/MEA-triazine-78%25-VasudevChemoPharma1.jpeg",
    images: [
      {
        src: "https://atjtpw4vvodv5rtp.public.blob.vercel-storage.com/MEA%20Triazine/MEA-triazine-78%25-VasudevChemoPharma1.jpeg",
        alt: "MEA Triazine 78% H2S Scavenger â€” Vasudev Chemo Pharma",
        width: 1200,
        height: 900,
        isPrimary: true,
      },
      {
        src: "https://atjtpw4vvodv5rtp.public.blob.vercel-storage.com/MEA%20Triazine/MEA-triazine-78%25-VasudevChemoPharma2.jpeg",
        alt: "MEA Triazine 78% H2S Scavenger packaging â€” Vasudev Chemo Pharma",
        width: 1200,
        height: 900,
        isPrimary: false,
      },
    ],
    videos: [
      {
        src: "https://atjtpw4vvodv5rtp.public.blob.vercel-storage.com/MEA%20Triazine/MEA-triazine-78%25-VasudevChemoPharma.mp4",
        title: "MEA Triazine 78% H2S Scavenger â€” Product Overview",
        description: "Product demonstration video for MEA Triazine 78% H2S Scavenger by Vasudev Chemo Pharma.",
        thumbnail: "https://atjtpw4vvodv5rtp.public.blob.vercel-storage.com/MEA%20Triazine/MEA-triazine-78%25-VasudevChemoPharma1.jpeg",
        isPrimary: true,
      },
    ],
    status: "active",
    faqs: [],
  },
  {
    id: 2,
    name: "MMA Triazine 40%",
    slug: "mma-triazine-40",
    sku: "VCP-IND-0002",
    formula: "Câ‚ƒHâ‚†Nâ‚†",
    casNumber: "108-74-7",
    category: "industrial",
    subcategory: "Oilfield Chemicals",
    metaTitle: "",
    metaDescription: "",
    description:
      "MMA Triazine 40% is a methyl-substituted triazine-based Hâ‚‚S scavenger designed for applications where BTEX-free alternatives are required. It is widely used in natural gas processing and crude oil stabilisation. This formulation provides effective hydrogen sulphide removal at a moderate concentration, offering excellent cost-performance balance for continuous-injection systems. Manufactured by Vasudev Chemo Pharma, MMA Triazine 40% meets the stringent requirements of major oil and gas operators and is suitable for both onshore and offshore applications. The product is non-corrosive to common oilfield metallurgy and does not contribute to foaming in gas processing equipment.",
    appearance: "Clear to pale yellow liquid",
    molecularWeight: "126.12 g/mol",
    hsCode: "29336990",
    specs: {
      "Active Content": "â‰¥ 40%",
      "pH (1% solution)": "9.5 â€“ 11.5",
      "Specific Gravity (25Â°C)": "1.05 â€“ 1.10",
      "Colour": "Clear to pale yellow",
      "Odour": "Mild amine",
      "Solubility in Water": "Fully miscible",
      "Flash Point": "> 93Â°C",
      "Freezing Point": "< âˆ’10Â°C",
    },
    safetyClass: "Irritant",
    ghsPictograms: ["GHS07"],
    signalWord: "Warning",
    hazardStatements: [
      "H315 â€“ Causes skin irritation",
      "H319 â€“ Causes serious eye irritation",
    ],
    documents: [],
    applications: [
      "Hâ‚‚S removal in natural gas streams",
      "Crude oil stabilisation",
      "BTEX-free scavenging operations",
      "Wellhead and pipeline treatment",
      "Gas processing plant sweetening",
    ],
    industries: [
      "Oil & Gas",
      "Petrochemicals",
      "Refineries",
      "Biogas & Renewable Energy",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: ["Industrial Grade", "Oilfield Grade"],
    packaging: [
      "210 L HDPE drums",
      "1000 L IBC tanks",
      "Bulk tanker loads",
      "Custom packaging on request",
    ],
    minOrderQuantity: "1 MT",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    imageUrl: "https://atjtpw4vvodv5rtp.public.blob.vercel-storage.com/Product_Section/MMA_Triazine_Vasudev_Chemo_Pharma.png",
    images: [
      {
        src: "https://atjtpw4vvodv5rtp.public.blob.vercel-storage.com/Product_Section/MMA_Triazine_Vasudev_Chemo_Pharma.png",
        alt: "MMA Triazine 40% product packaging by Vasudev Chemo Pharma",
        width: 1200,
        height: 900,
        isPrimary: true,
      },
    ],
    videos: [
      {
        src: "https://atjtpw4vvodv5rtp.public.blob.vercel-storage.com/MMA%20Triazine/MMA3.mp4",
        title: "MMA Triazine 40% Product Video",
        description: "Product video for MMA Triazine 40% by Vasudev Chemo Pharma.",
        thumbnail: "https://atjtpw4vvodv5rtp.public.blob.vercel-storage.com/Product_Section/MMA_Triazine_Vasudev_Chemo_Pharma.png",
        isPrimary: true,
      },
    ],
    status: "active",
    faqs: [],
  },
  {
    id: 3,
    name: "P-Toluenesulfonic Acid",
    slug: "p-toluenesulfonic-acid",
    sku: "VCP-IND-0003",
    formula: "CHâ‚ƒCâ‚†Hâ‚„SOâ‚ƒH",
    casNumber: "104-15-4",
    category: "industrial",
    subcategory: "Organic Acids",
    metaTitle: "",
    metaDescription: "",
    description:
      "P-Toluenesulfonic Acid (PTSA) is a strong organic acid widely used as a catalyst in esterification, polymerization, and dehydration reactions. It is preferred over mineral acids due to its milder and more selective reactivity. Vasudev Chemo Pharma supplies PTSA in both monohydrate and anhydrous forms, manufactured under strict quality controls at our Gujarat facility. The product is a versatile acid catalyst for resin synthesis, alkyd coatings, and biodiesel transesterification. PTSA is valued for its non-oxidising nature, ease of handling, and clean reaction profiles compared to sulphuric acid or hydrochloric acid.",
    appearance: "White crystalline solid",
    molecularWeight: "172.20 g/mol",
    hsCode: "29042090",
    specs: {
      "Purity": "â‰¥ 95.0%",
      "Melting Point": "103 â€“ 106Â°C (monohydrate)",
      "Moisture": "â‰¤ 5.0% (monohydrate)",
      "Colour (Hazen)": "â‰¤ 50",
      "Sulphated Ash": "â‰¤ 0.1%",
      "Iron (Fe)": "â‰¤ 10 ppm",
      "pH (10% solution)": "1.0 â€“ 2.0",
      "Solubility in Water": "Freely soluble",
    },
    safetyClass: "Corrosive / Irritant",
    ghsPictograms: ["GHS05", "GHS07"],
    signalWord: "Danger",
    hazardStatements: [
      "H314 â€“ Causes severe skin burns and eye damage",
      "H335 â€“ May cause respiratory irritation",
    ],
    documents: [],
    applications: [
      "Esterification catalyst",
      "Polymerisation catalyst",
      "Alkyd resin manufacturing",
      "Biodiesel production",
      "Pharmaceutical synthesis",
      "Dehydration reactions",
      "Crosslinking catalyst for coatings",
    ],
    industries: [
      "Paints & Coatings",
      "Resins & Polymers",
      "Pharmaceuticals",
      "Biofuels",
      "Agrochemicals",
      "Fine Chemicals",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: ["Industrial Grade", "Technical Grade", "Pharmaceutical Grade"],
    packaging: [
      "25 kg HDPE bags",
      "50 kg fibre drums",
      "500 kg jumbo bags",
      "Custom packaging on request",
    ],
    minOrderQuantity: "500 kg",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
  {
    id: 4,
    name: "Copper Sulphate",
    slug: "copper-sulphate",
    sku: "VCP-IND-0004",
    formula: "CuSOâ‚„Â·5Hâ‚‚O",
    casNumber: "7758-99-8",
    category: "industrial",
    subcategory: "Inorganic Salts",
    metaTitle: "",
    metaDescription: "",
    description:
      "Copper Sulphate Pentahydrate is used in agriculture as a fungicide and soil additive, in mining as a flotation reagent, and in water treatment for algae control. Also used in electroplating and the production of copper compounds. Vasudev Chemo Pharma manufactures Copper Sulphate in multiple grades â€” from feed-grade micronutrient supplements to high-purity electroplating grade â€” at our ISO 9001:2015 certified facility. The product is available as blue crystalline granules or fine powder, and is exported to over 30 countries. Copper Sulphate (CAS 7758-99-8) is an essential input across agriculture, animal husbandry, and industrial chemistry.",
    appearance: "Blue crystalline granules",
    molecularWeight: "249.69 g/mol",
    hsCode: "28332500",
    specs: {
      "Purity (as CuSOâ‚„Â·5Hâ‚‚O)": "â‰¥ 98.0%",
      "Copper (Cu) Content": "â‰¥ 25.0%",
      "Iron (Fe)": "â‰¤ 0.05%",
      "Insoluble Matter": "â‰¤ 0.1%",
      "pH (5% solution)": "3.5 â€“ 4.5",
      "Moisture": "â‰¤ 1.0%",
      "Lead (Pb)": "â‰¤ 10 ppm",
      "Arsenic (As)": "â‰¤ 5 ppm",
    },
    safetyClass: "Harmful / Irritant / Hazardous to aquatic environment",
    ghsPictograms: ["GHS07", "GHS09"],
    signalWord: "Warning",
    hazardStatements: [
      "H302 â€“ Harmful if swallowed",
      "H315 â€“ Causes skin irritation",
      "H318 â€“ Causes serious eye damage",
      "H410 â€“ Very toxic to aquatic life with long lasting effects",
    ],
    documents: [],
    applications: [
      "Agricultural fungicide (Bordeaux mixture)",
      "Animal feed micronutrient",
      "Electroplating & electroforming",
      "Water treatment & algae control",
      "Mining flotation reagent",
      "Wood preservative (CCA treatment)",
      "Lab reagent & analytical chemistry",
    ],
    industries: [
      "Agriculture",
      "Animal Feed",
      "Mining",
      "Water Treatment",
      "Electroplating",
      "Construction (wood treatment)",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: [
      "Industrial Grade",
      "Feed Grade",
      "Electroplating Grade",
      "Lab / Reagent Grade",
    ],
    packaging: [
      "25 kg HDPE bags",
      "50 kg HDPE bags",
      "1 MT jumbo bags",
      "Custom packaging on request",
    ],
    minOrderQuantity: "1 MT",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
  {
    id: 5,
    name: "Manganese Sulphate",
    slug: "manganese-sulphate",
    sku: "VCP-IND-0005",
    formula: "MnSOâ‚„Â·Hâ‚‚O",
    casNumber: "10034-96-5",
    category: "industrial",
    subcategory: "Inorganic Salts",
    metaTitle: "",
    metaDescription: "",
    description:
      "Manganese Sulphate Monohydrate is used as a micronutrient in animal feed and fertilisers, as a precursor in the production of electrolytic manganese dioxide (EMD) for batteries, and in various chemical processes. Vasudev Chemo Pharma supplies Manganese Sulphate (CAS 10034-96-5) in feed-grade and industrial-grade variants, manufactured at our Gujarat-based facility. The product provides a bioavailable source of manganese essential for plant growth and animal health, and serves as a critical raw material in the lithium-ion battery supply chain for EMD and manganese-based cathode materials.",
    appearance: "Pale pink crystalline powder",
    molecularWeight: "169.02 g/mol",
    hsCode: "28332990",
    specs: {
      "Purity (as MnSOâ‚„Â·Hâ‚‚O)": "â‰¥ 98.0%",
      "Manganese (Mn) Content": "â‰¥ 31.5%",
      "Iron (Fe)": "â‰¤ 0.01%",
      "Heavy Metals (as Pb)": "â‰¤ 10 ppm",
      "Insoluble Matter": "â‰¤ 0.05%",
      "Moisture": "â‰¤ 1.0%",
      "pH (5% solution)": "3.5 â€“ 5.0",
      "Lead (Pb)": "â‰¤ 5 ppm",
    },
    safetyClass: "Harmful",
    ghsPictograms: ["GHS07"],
    signalWord: "Warning",
    hazardStatements: [
      "H302 â€“ Harmful if swallowed",
      "H315 â€“ Causes skin irritation",
      "H319 â€“ Causes serious eye irritation",
    ],
    documents: [],
    applications: [
      "Animal feed micronutrient",
      "Agricultural fertiliser additive",
      "Electrolytic Manganese Dioxide (EMD) production",
      "Battery cathode precursor",
      "Ceramic and dye manufacturing",
      "Water purification reagent",
    ],
    industries: [
      "Agriculture",
      "Animal Feed",
      "Batteries & Energy Storage",
      "Ceramics",
      "Chemicals Manufacturing",
      "Water Treatment",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: ["Industrial Grade", "Feed Grade", "Battery Grade"],
    packaging: [
      "25 kg HDPE bags",
      "50 kg HDPE bags",
      "1 MT jumbo bags",
      "Custom packaging on request",
    ],
    minOrderQuantity: "1 MT",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },

  // â”€â”€â”€ SURFACTANT CHEMICALS â€” HYDROTROPES â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: 6,
    name: "Sodium Cumene Sulfonate 40%",
    slug: "sodium-cumene-sulfonate-40",
    sku: "VCP-SFC-0001",
    formula: "Câ‚‰Hâ‚â‚NaOâ‚ƒS",
    casNumber: "28348-53-0",
    category: "surfactant",
    subcategory: "Hydrotropes",
    metaTitle: "",
    metaDescription: "",
    description: "Sodium Cumene Sulfonate 40% (SCS 40%) is a high-performance liquid hydrotrope used as a coupling agent, solubiliser, and viscosity reducer in surfactant-based formulations. It enhances the aqueous solubility of sparingly soluble organic compounds â€” such as surfactants, fragrances, and dyes â€” preventing phase separation, cloudiness, and gel formation in concentrated liquid detergents, industrial cleaners, and personal care products. SCS 40% is sulfate-free and sulfone-free, making it suitable for mild and sensitive-skin formulations. Also known as sodium isopropylbenzenesulfonate or sodium 4-(propan-2-yl)benzenesulfonate, it is a versatile ingredient used across household, industrial, oilfield, and agrochemical applications. Manufactured by Vasudev Chemo Pharma at our ISO 9001:2015 certified facility in Gujarat, India, this product is exported to detergent manufacturers, personal care formulators, and specialty chemical companies worldwide.",
    appearance: "Clear to slightly hazy liquid",
    molecularWeight: "222.24 g/mol",
    hsCode: "29041090",
    specs: {
      "Active Content": "39.0 â€“ 41.0%",
      "pH (as supplied)": "7.0 â€“ 10.0",
      "Specific Gravity (25Â°C)": "1.07 â€“ 1.12",
      "Colour": "Clear to slightly hazy",
      "Odour": "Mild aromatic",
      "Solubility in Water": "Fully miscible",
      "Sulfate Content": "< 1.0%",
      "Sulfone Content": "< 1.0%",
      "Moisture": "58 â€“ 62%",
      "Cloud Point": "< 0Â°C (as supplied)",
      "Storage Temperature": "> 10Â°C (to prevent crystallisation)",
    },
    safetyClass: "Irritant",
    ghsPictograms: ["GHS07"],
    signalWord: "Warning",
    hazardStatements: [
      "H315 â€“ Causes skin irritation",
      "H319 â€“ Causes serious eye irritation",
    ],
    documents: [],
    applications: [
      "Hydrotrope and coupling agent in liquid detergents",
      "Solubiliser in concentrated all-purpose cleaners",
      "Viscosity reducer in high-surfactant formulations",
      "Cloud point depressant in industrial cleaning products",
      "Stabiliser in shampoos, body washes, and liquid soaps",
      "Dispersant in paints, coatings, and dye formulations",
      "Compatibility enhancer for anionic, nonionic, and amphoteric surfactant blends",
      "Drilling fluid additive and cementing aid in oilfield operations",
      "Wetting agent in agrochemical and pesticide formulations",
      "Metal cleaning and electroplating bath additive",
    ],
    industries: [
      "Household & Industrial Cleaning",
      "Personal Care & Cosmetics",
      "Detergent Manufacturing",
      "Oil & Gas",
      "Paints & Coatings",
      "Agrochemicals",
      "Textile Processing",
      "Metal Processing & Electroplating",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: ["Technical Grade", "Industrial Grade"],
    packaging: [
      "240 L HDPE drums",
      "1000 L IBC tanks",
      "Bulk tanker loads",
      "Custom packaging on request",
    ],
    minOrderQuantity: "1 MT",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
  {
    id: 7,
    name: "Sodium Cumene Sulfonate 90%",
    slug: "sodium-cumene-sulfonate-90",
    sku: "VCP-SFC-0002",
    formula: "Câ‚‰Hâ‚â‚NaOâ‚ƒS",
    casNumber: "28348-53-0",
    category: "surfactant",
    subcategory: "Hydrotropes",
    metaTitle: "",
    metaDescription: "",
    description: "Sodium Cumene Sulfonate 90% (SCS 90%) is a concentrated powder-form hydrotrope containing approximately 90% active sodium 4-isopropylbenzenesulfonate. It is used as a coupling agent, solubiliser, and viscosity reducer in surfactant-based formulations including liquid detergents, industrial cleaners, and personal care products. The high active content makes SCS 90% cost-effective for large-volume formulators who dissolve it on-site before blending, significantly reducing freight costs compared to liquid grades. It is sulfate-free and sulfone-free, biodegradable, and compatible with anionic, nonionic, and amphoteric surfactant systems. Manufactured by Vasudev Chemo Pharma at our ISO 9001:2015 certified facility in Gujarat, India.",
    appearance: "White to off-white powder / flakes",
    molecularWeight: "222.24 g/mol",
    hsCode: "29041090",
    specs: {
      "Active Content": "â‰¥ 90.0%",
      "pH (10% solution)": "8.0 â€“ 11.0",
      "Colour": "White to off-white",
      "Odour": "Mild aromatic",
      "Solubility in Water": "Freely soluble",
      "Sulfate Content": "< 0.5%",
      "Sulfone Content": "< 1.0%",
      "Moisture": "â‰¤ 5.0%",
      "Bulk Density": "0.5 â€“ 0.7 g/mL",
    },
    safetyClass: "Irritant",
    ghsPictograms: ["GHS07"],
    signalWord: "Warning",
    hazardStatements: [
      "H315 â€“ Causes skin irritation",
      "H319 â€“ Causes serious eye irritation",
    ],
    documents: [],
    applications: [
      "Hydrotrope and coupling agent in liquid detergents",
      "Solubiliser in concentrated all-purpose cleaners",
      "Viscosity reducer in high-surfactant formulations",
      "Cloud point depressant in industrial cleaning products",
      "Stabiliser in shampoos, body washes, and liquid soaps",
      "Dispersant in paints, coatings, and dye formulations",
      "Compatibility enhancer for anionic, nonionic, and amphoteric surfactant blends",
      "Drilling fluid additive and cementing aid in oilfield operations",
      "Wetting agent in agrochemical and pesticide formulations",
    ],
    industries: [
      "Household & Industrial Cleaning",
      "Personal Care & Cosmetics",
      "Detergent Manufacturing",
      "Oil & Gas",
      "Paints & Coatings",
      "Agrochemicals",
      "Textile Processing",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: ["Technical Grade", "Industrial Grade"],
    packaging: [
      "25 kg HDPE-lined bags",
      "500 kg jumbo bags",
      "Custom packaging on request",
    ],
    minOrderQuantity: "1 MT",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
  {
    id: 8,
    name: "Sodium Xylene Sulfonate 90%",
    slug: "sodium-xylene-sulfonate-90",
    sku: "VCP-SFC-0003",
    formula: "Câ‚ˆHâ‚‰NaOâ‚ƒS",
    casNumber: "1300-72-7",
    category: "surfactant",
    subcategory: "Hydrotropes",
    metaTitle: "",
    metaDescription: "",
    description: "Sodium Xylene Sulfonate 90% (SXS 90%) is a high-active, free-flowing powder hydrotrope containing 90% active sodium xylenesulfonate (CAS 1300-72-7). It is the dry, export-efficient grade of SXS used when formulators want lower shipped water, compact storage, and flexible on-site dilution before blending. SXS 90% functions as a hydrotrope, coupling agent, solubiliser, viscosity reducer, cloud-point depressant, dispersant, and processing aid in surfactant-based systems. It is used in detergent powders, concentrated alkaline cleaners, industrial and institutional cleaning compounds, agrochemical water-dispersible granules, textile auxiliaries, paper-processing additives, and personal-care surfactant bases where clarity, electrolyte tolerance, and phase stability are important. Manufactured by Vasudev Chemo Pharma at our ISO 9001:2015 certified facility in Ankleshwar, Gujarat, India, SXS 90% is supplied with batch COA, SDS, TDS support, export documentation, and bulk packaging for domestic and international buyers.",
    appearance: "White to off-white powder",
    molecularWeight: "208.21 g/mol",
    hsCode: "29041090",
    specs: {
      "Active Content": "â‰¥ 90.0%",
      "pH (10% solution)": "8.0 â€“ 11.0",
      "Colour": "White to off-white",
      "Odour": "Mild",
      "Solubility in Water": "Freely soluble",
      "Sulfate Content": "< 1.0%",
      "Moisture": "â‰¤ 5.0%",
      "Bulk Density": "0.5 â€“ 0.7 g/mL",
      "EC Number": "215-090-9",
      "Typical Form": "Free-flowing powder",
      "Recommended Storage": "Keep sealed in a cool, dry warehouse",
    },
    safetyClass: "Irritant",
    ghsPictograms: ["GHS07"],
    signalWord: "Warning",
    hazardStatements: [
      "H315 â€“ Causes skin irritation",
      "H319 â€“ Causes serious eye irritation",
    ],
    documents: [],
    applications: [
      "Hydrotrope and coupling agent in liquid detergents",
      "Solubiliser in concentrated household and industrial cleaners",
      "Viscosity reducer in high-surfactant formulations",
      "Cloud point depressant in cleaning product formulations",
      "Spray-dried detergent powder processing aid",
      "Alkaline cleaner and degreaser stability additive",
      "Agrochemical water-dispersible granule and soluble-liquid formulation aid",
      "Stabiliser in shampoos, body washes, and liquid hand soaps",
      "Dispersant in textile and dye processing",
      "Paper industry pentosan and lignin extraction aid",
      "Glue and adhesive additive for leather and packaging applications",
      "Compatibility enhancer for mixed surfactant systems",
      "Wetting agent in agrochemical formulations",
    ],
    industries: [
      "Household & Industrial Cleaning",
      "Personal Care & Cosmetics",
      "Detergent Manufacturing",
      "Textile Processing",
      "Agrochemicals",
      "Paints & Coatings",
      "Paper & Leather Auxiliaries",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: ["Technical Grade", "Industrial Grade"],
    packaging: [
      "15 kg HDPE-lined bags",
      "25 kg HDPE-lined bags",
      "500 kg jumbo bags",
      "1000 kg jumbo bags",
      "Custom packaging on request",
    ],
    minOrderQuantity: "1 MT",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
  {
    id: 19,
    name: "Sodium Xylene Sulfonate 40%",
    slug: "sodium-xylene-sulfonate-40",
    sku: "VCP-SFC-0004",
    formula: "Câ‚ˆHâ‚‰NaOâ‚ƒS",
    casNumber: "1300-72-7",
    category: "surfactant",
    subcategory: "Hydrotropes",
    metaTitle: "",
    metaDescription: "",
    description: "Sodium Xylene Sulfonate 40% (SXS 40%) is a ready-to-use liquid hydrotrope containing approximately 40% active sodium xylenesulfonate in aqueous solution. It is used as a coupling agent, solubiliser, and viscosity reducer in surfactant-based formulations â€” keeping concentrated liquid detergents, all-purpose cleaners, and personal care products clear, stable, and pourable. SXS 40% blends easily into liquid formulations without pre-dissolution, making it the preferred choice for detergent and personal care manufacturers who value formulation speed and ease of handling. It is biodegradable, non-toxic at use concentrations, and compatible with anionic, nonionic, cationic, and amphoteric surfactant systems. Manufactured by Vasudev Chemo Pharma at our ISO 9001:2015 certified facility in Gujarat, India.",
    appearance: "Clear to slightly hazy liquid",
    molecularWeight: "208.21 g/mol",
    hsCode: "29041090",
    specs: {
      "Active Content": "39.0 â€“ 41.0%",
      "pH (as supplied)": "7.0 â€“ 10.0",
      "Specific Gravity (25Â°C)": "1.06 â€“ 1.10",
      "Colour": "Clear to slightly hazy",
      "Odour": "Mild",
      "Solubility in Water": "Fully miscible",
      "Sulfate Content": "< 1.0%",
      "Moisture": "58 â€“ 62%",
      "Cloud Point": "< 0Â°C (as supplied)",
      "Storage Temperature": "> 10Â°C (to prevent crystallisation)",
    },
    safetyClass: "Irritant",
    ghsPictograms: ["GHS07"],
    signalWord: "Warning",
    hazardStatements: [
      "H315 â€“ Causes skin irritation",
      "H319 â€“ Causes serious eye irritation",
    ],
    documents: [],
    applications: [
      "Hydrotrope and coupling agent in liquid detergents",
      "Solubiliser in concentrated household and industrial cleaners",
      "Viscosity reducer in high-surfactant formulations",
      "Cloud point depressant in cleaning product formulations",
      "Stabiliser in shampoos, body washes, and liquid hand soaps",
      "Dispersant in textile and dye processing",
      "Compatibility enhancer for mixed surfactant systems",
      "Wetting agent in agrochemical formulations",
      "Metal cleaning and degreasing formulations",
    ],
    industries: [
      "Household & Industrial Cleaning",
      "Personal Care & Cosmetics",
      "Detergent Manufacturing",
      "Textile Processing",
      "Agrochemicals",
      "Paints & Coatings",
      "Metal Processing",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: ["Technical Grade", "Industrial Grade"],
    packaging: [
      "240 L HDPE drums",
      "1000 L IBC tanks",
      "Bulk tanker loads",
      "Custom packaging on request",
    ],
    minOrderQuantity: "1 MT",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },

  // â”€â”€â”€ SPECIALTY CHEMICALS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: 9,
    name: "Bis(2-chloroethyl)amine Hydrochloride",
    slug: "bis-2-chloroethyl-amine-hydrochloride",
    sku: "VCP-SPC-0001",
    formula: "Câ‚„Hâ‚‰Clâ‚‚NÂ·HCl",
    casNumber: "821-48-7",
    category: "specialty",
    subcategory: "Organic Intermediates",
    metaTitle: "",
    metaDescription: "",
    description:
      "Bis(2-chloroethyl)amine Hydrochloride is a specialty organic intermediate used in pharmaceutical synthesis and the production of nitrogen mustard derivatives for research and industrial applications. Supplied by Vasudev Chemo Pharma, this compound (CAS 821-48-7) is manufactured under controlled conditions with strict purity assurance. It serves as a key building block for the synthesis of anti-cancer alkylating agents, cross-linking reagents, and nitrogen heterocycles. This substance is listed under the Chemical Weapons Convention (CWC) Schedule 2 and may be subject to national export-control regulations (e.g. ECCN, REACH Annex XIV). The product is handled and shipped in compliance with applicable dangerous goods and export-control regulations. All sales and shipments require prior end-user vetting and appropriate licensing documentation.",
    appearance: "White to off-white crystalline solid",
    molecularWeight: "178.49 g/mol",
    hsCode: "29211990",
    specs: {
      "Purity (by HPLC)": "â‰¥ 98.0%",
      "Melting Point": "210 â€“ 215Â°C (decomp.)",
      "Moisture": "â‰¤ 0.5%",
      "Residue on Ignition": "â‰¤ 0.1%",
      "Chloride Content": "Within spec",
      "Appearance": "White to off-white crystalline solid",
    },
    safetyClass: "Toxic / Harmful",
    ghsPictograms: ["GHS06", "GHS08"],
    signalWord: "Danger",
    hazardStatements: [
      "H301 â€“ Toxic if swallowed",
      "H311 â€“ Toxic in contact with skin",
      "H331 â€“ Toxic if inhaled",
      "H350 â€“ May cause cancer",
    ],
    complianceDisclaimer:
      "This substance is listed under the Chemical Weapons Convention (CWC) Schedule 2 and may be subject to national export-control regulations including ECCN classification, REACH Annex XIV authorisation, and other chemical-control frameworks. Sale, purchase, and shipment of this product require prior end-user vetting, valid import/export licences, and appropriate regulatory documentation. Vasudev Chemo Pharma will not process orders without completed compliance verification.",
    documents: [],
    applications: [
      "Anti-cancer drug intermediate (nitrogen mustard derivatives)",
      "Cross-linking reagent for bioconjugation",
      "Synthesis of nitrogen heterocycles",
      "Pharmaceutical R&D and process chemistry",
    ],
    industries: [
      "Pharmaceuticals",
      "Oncology Research",
      "Fine Chemicals",
      "Biotechnology",
    ],
    price: 0,
    priceUnit: "/kg",
    currency: "USD",
    unitOfMeasure: "kg",
    grades: ["Synthesis Grade (â‰¥ 98%)", "Research Grade"],
    packaging: [
      "1 kg HDPE containers",
      "5 kg HDPE drums",
      "25 kg fibre drums",
      "Custom packaging on request",
    ],
    minOrderQuantity: "1 kg",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
  {
    id: 10,
    name: "Di Ethyl Amino Ethyl Chloride Hydrochloride",
    slug: "di-ethyl-amino-ethyl-chloride-hydrochloride",
    sku: "VCP-SPC-0002",
    formula: "Câ‚†Hâ‚â‚„ClNÂ·HCl",
    casNumber: "869-24-9",
    category: "specialty",
    subcategory: "Organic Intermediates",
    metaTitle: "",
    metaDescription: "",
    description:
      "DEAE-Cl HCl (Diethylaminoethyl Chloride Hydrochloride) is a key pharmaceutical intermediate used in the synthesis of various active pharmaceutical ingredients including antihistamines and local anaesthetics. Vasudev Chemo Pharma supplies this compound (CAS 869-24-9) in high purity for GMP and non-GMP applications. It is used as an alkylating agent to introduce the diethylaminoethyl side chain into drug molecules â€” a structural motif found in Chloroquine, Procaine, and several other pharmaceuticals. The product is manufactured under rigorous process controls at our specialty synthesis unit in Gujarat, India.",
    appearance: "White crystalline powder",
    molecularWeight: "172.10 g/mol",
    hsCode: "29211990",
    specs: {
      "Purity (by GC)": "â‰¥ 99.0%",
      "Melting Point": "210 â€“ 215Â°C",
      "Moisture": "â‰¤ 0.5%",
      "Residue on Ignition": "â‰¤ 0.1%",
      "pH (5% solution)": "3.0 â€“ 5.0",
      "Heavy Metals (as Pb)": "â‰¤ 10 ppm",
    },
    safetyClass: "Corrosive / Toxic",
    ghsPictograms: ["GHS05", "GHS06"],
    signalWord: "Danger",
    hazardStatements: [
      "H301 â€“ Toxic if swallowed",
      "H311 â€“ Toxic in contact with skin",
      "H314 â€“ Causes severe skin burns and eye damage",
    ],
    documents: [],
    applications: [
      "Intermediate for Chloroquine and Hydroxychloroquine",
      "Synthesis of local anaesthetics (Procaine family)",
      "Antihistamine API manufacturing",
      "Alkylating agent in organic synthesis",
      "Ion-exchange resin functionalisation",
    ],
    industries: [
      "Pharmaceuticals",
      "API Manufacturing",
      "Fine Chemicals",
      "Polymer Chemistry",
    ],
    price: 0,
    priceUnit: "/kg",
    currency: "USD",
    unitOfMeasure: "kg",
    grades: ["Pharmaceutical Grade (â‰¥ 99%)", "Technical Grade (â‰¥ 98%)"],
    packaging: [
      "1 kg HDPE containers",
      "5 kg HDPE drums",
      "25 kg fibre drums",
      "Custom packaging on request",
    ],
    minOrderQuantity: "5 kg",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
  {
    id: 11,
    name: "2-Amino-5-methylthiazole",
    slug: "2-amino-5-methylthiazole",
    sku: "VCP-SPC-0003",
    formula: "Câ‚„Hâ‚†Nâ‚‚S",
    casNumber: "7305-71-7",
    category: "specialty",
    subcategory: "Heterocyclic Compounds",
    metaTitle: "",
    metaDescription: "",
    description:
      "2-Amino-5-methylthiazole is a heterocyclic building block used in the synthesis of pharmaceuticals, agrochemicals, and dyes. It is a key intermediate in the manufacture of several drug molecules. Supplied by Vasudev Chemo Pharma (CAS 7305-71-7), this thiazole derivative is manufactured in high purity for pharmaceutical and research applications. The compound serves as a starting material for the synthesis of Famotidine (Hâ‚‚-receptor antagonist), Nizatidine, and various sulfonamide antibiotics. It is also used as a corrosion inhibitor in industrial applications and as a building block in materials science.",
    appearance: "Pale yellow crystalline solid",
    molecularWeight: "114.17 g/mol",
    hsCode: "29341090",
    specs: {
      "Purity (by HPLC)": "â‰¥ 98.0%",
      "Melting Point": "93 â€“ 97Â°C",
      "Moisture": "â‰¤ 0.5%",
      "Residue on Ignition": "â‰¤ 0.1%",
      "Appearance": "Pale yellow crystalline solid",
      "Solubility": "Soluble in ethanol, sparingly soluble in water",
    },
    safetyClass: "Irritant",
    ghsPictograms: ["GHS07"],
    signalWord: "Warning",
    hazardStatements: [
      "H302 â€“ Harmful if swallowed",
      "H315 â€“ Causes skin irritation",
      "H319 â€“ Causes serious eye irritation",
    ],
    documents: [],
    applications: [
      "Famotidine API intermediate",
      "Nizatidine & ranitidine synthesis",
      "Agrochemical intermediate",
      "Dye and pigment synthesis",
      "Corrosion inhibitor",
      "Heterocyclic building block for research",
    ],
    industries: [
      "Pharmaceuticals",
      "Agrochemicals",
      "Dyes & Pigments",
      "Fine Chemicals",
      "Research & Development",
    ],
    price: 0,
    priceUnit: "/kg",
    currency: "USD",
    unitOfMeasure: "kg",
    grades: ["Pharmaceutical Grade (â‰¥ 98%)", "Technical Grade (â‰¥ 97%)"],
    packaging: [
      "1 kg HDPE containers",
      "5 kg HDPE drums",
      "25 kg fibre drums",
      "Custom packaging on request",
    ],
    minOrderQuantity: "5 kg",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
  {
    id: 12,
    name: "2-Chloroethylamine Hydrochloride",
    slug: "2-chloroethylamine-hydrochloride",
    sku: "VCP-SPC-0004",
    formula: "ClCHâ‚‚CHâ‚‚NHâ‚‚Â·HCl",
    casNumber: "870-24-6",
    category: "specialty",
    subcategory: "Organic Intermediates",
    metaTitle: "",
    metaDescription: "",
    description:
      "2-Chloroethylamine Hydrochloride is a versatile organic intermediate used in the synthesis of pharmaceuticals, agrochemicals, and specialty polymers. It is a key building block for ethyleneimine derivatives. Vasudev Chemo Pharma supplies this compound (CAS 870-24-6) in high purity for use in the production of aziridine-based crosslinkers, surfactants, and pharmaceutical intermediates. The product is manufactured at our specialty chemicals unit under controlled conditions and is available in research and bulk quantities for industrial-scale synthesis.",
    appearance: "White crystalline powder",
    molecularWeight: "116.01 g/mol",
    hsCode: "29211990",
    specs: {
      "Purity (by GC)": "â‰¥ 99.0%",
      "Melting Point": "143 â€“ 146Â°C",
      "Moisture": "â‰¤ 0.5%",
      "Residue on Ignition": "â‰¤ 0.1%",
      "pH (5% solution)": "2.0 â€“ 4.0",
      "Appearance": "White crystalline powder",
    },
    safetyClass: "Corrosive / Toxic",
    ghsPictograms: ["GHS05", "GHS06"],
    signalWord: "Danger",
    hazardStatements: [
      "H301 â€“ Toxic if swallowed",
      "H311 â€“ Toxic in contact with skin",
      "H314 â€“ Causes severe skin burns and eye damage",
      "H331 â€“ Toxic if inhaled",
    ],
    documents: [],
    applications: [
      "Ethyleneimine (aziridine) synthesis",
      "Pharmaceutical intermediate",
      "Agrochemical intermediate",
      "Cross-linking agent for coatings & resins",
      "Surfactant synthesis",
      "Specialty polymer building block",
    ],
    industries: [
      "Pharmaceuticals",
      "Agrochemicals",
      "Polymers & Resins",
      "Fine Chemicals",
      "Coatings",
    ],
    price: 0,
    priceUnit: "/kg",
    currency: "USD",
    unitOfMeasure: "kg",
    grades: ["Pharmaceutical Grade (â‰¥ 99%)", "Technical Grade (â‰¥ 98%)"],
    packaging: [
      "1 kg HDPE containers",
      "5 kg HDPE drums",
      "25 kg fibre drums",
      "Custom packaging on request",
    ],
    minOrderQuantity: "5 kg",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
  {
    id: 13,
    name: "Triazine Based H2S Scavenger (General)",
    slug: "triazine-h2s-scavenger-general",
    sku: "VCP-IND-0012",
    formula: "C6H15N3O3 / C3H6N6",
    casNumber: "4719-04-4 / 108-74-7",
    category: "industrial",
    subcategory: "Oilfield Chemicals",
    metaTitle: "Triazine Based H2S Scavenger Manufacturer Vasudev Chemo Pharma",
    metaDescription: "Comprehensive range of Triazine Based H2S Scavengers. Custom concentrations for oilfield, refinery, and biogas H2S removal. Trusted Indian manufacturer.",
    description: "Vasudev Chemo Pharma provides a comprehensive portfolio of Triazine Based H2S Scavengers for the global energy and industrial sectors. Hydrogen sulfide (H2S) is a toxic, corrosive gas that poses significant risks to personnel and infrastructure; our triazine technology offers the most reliable and cost-effective chemical removal method available today. Whether you require Monoethanolamine (MEA) Triazine for rapid gas-phase sweetening or Methylamine (MMA) Triazine for crude oil stabilization, our technical team can provide a tailored solution.",
    appearance: "Clear to light yellow liquid",
    molecularWeight: "Varies",
    hsCode: "29336990",
    specs: {
      "Type": "MEA or MMA Based",
      "Concentration": "20% to 80% available",
      "Reaction Speed": "Instantaneous",
      "Solubility": "Water Soluble",
    },
    safetyClass: "Irritant",
    ghsPictograms: ["GHS07"],
    signalWord: "Warning",
    hazardStatements: [
      "H315 â€“ Causes skin irritation",
      "H319 â€“ Causes serious eye irritation",
    ],
    documents: [],
    applications: [
      "Natural Gas Sweetening",
      "Crude Oil Stabilization",
      "LPG Sweetening",
      "Biogas Purification",
    ],
    industries: [
      "Oil & Gas",
      "Petrochemicals",
      "Refineries",
      "Biogas & Renewable Energy",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: ["Industrial Grade", "Oilfield Grade"],
    packaging: [
      "210 L HDPE drums",
      "1000 L IBC tanks",
      "Bulk tanker loads",
    ],
    minOrderQuantity: "1 MT",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
  {
    id: 14,
    name: "Metal Working Fluids",
    slug: "metal-working-fluids",
    sku: "VCP-IND-0013",
    formula: "N/A",
    casNumber: "N/A",
    category: "industrial",
    subcategory: "Industrial Preservatives",
    metaTitle: "Metal Working Fluids - Manufacturer Vasudev Chemo Pharma",
    metaDescription: "Enhance the life of your Metal Working Fluids (MWF) with Vasudev's specialized triazine biocides. Prevents odor, slime, and fluid degradation.",
    description: "In the precision world of machining, the longevity and performance of Metal Working Fluids (MWF) are paramount. Vasudev Chemo Pharma manufactures high-quality triazine-based additives that serve as essential preservatives and biocides for cooling and cutting fluids. Biological contamination in MWF systems leads to foul odors, fluid split, and filter plugging. Our triazine chemistry acts as a powerful formaldehyde-releasing biocide, effectively controlling the growth of bacteria and fungi.",
    appearance: "Clear liquid",
    molecularWeight: "N/A",
    hsCode: "38119000",
    specs: {
      "Application Rate": "0.1% to 0.25%",
      "pH Stability": "8.5 â€“ 10.5",
      "Odor Control": "Excellent",
      "Compatibility": "Synthetic & Semi-Synthetic",
    },
    safetyClass: "Irritant",
    ghsPictograms: ["GHS07"],
    signalWord: "Warning",
    hazardStatements: [
      "H315 â€“ Causes skin irritation",
      "H317 â€“ May cause an allergic skin reaction",
    ],
    documents: [],
    applications: [
      "Cooling Fluid Preservation",
      "Cutting Fluid Biocide",
      "Odor Control in CNC Machining",
      "Fluid Life Extension",
    ],
    industries: [
      "Metal Processing",
      "Automotive Manufacturing",
      "Aerospace Engineering",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: ["Technical Grade"],
    packaging: [
      "50 L drums",
      "210 L drums",
      "1000 L IBC tanks",
    ],
    minOrderQuantity: "500 kg",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
  {
    id: 15,
    name: "Biocide for Oil & Gas Industries",
    slug: "biocide-oil-gas",
    sku: "VCP-IND-0014",
    formula: "N/A",
    casNumber: "N/A",
    category: "industrial",
    subcategory: "Oilfield Chemicals",
    metaTitle: "Biocide for Oil & Gas Industries - Manufacturer Vasudev Chemo Pharma",
    metaDescription: "Control bacteria in pipelines and water injection systems with Vasudevâ€™s Oil & Gas Biocides. Prevents SRB-induced corrosion and biofouling.",
    description: "Microbial-influenced corrosion (MIC) costs the oil and gas industry billions annually. Vasudev Chemo Pharmaâ€™s Oil & Gas Biocides are specifically formulated to combat Sulfate-Reducing Bacteria (SRB) and Acid-Producing Bacteria (APB) in complex oilfield environments. Our biocides are critical for water injection systems, produced water handling, and pipeline preservation. By utilizing triazine-based technology, we provide a dual-action solution that both sanitizes the system and neutralizes corrosive H2S byproducts.",
    appearance: "Clear to pale yellow liquid",
    molecularWeight: "N/A",
    hsCode: "38089400",
    specs: {
      "Target Bacteria": "SRB & APB",
      "Thermal Stability": "High",
      "Kill Rate": "Rapid",
      "Solubility": "Water Soluble",
    },
    safetyClass: "Toxic / Irritant",
    ghsPictograms: ["GHS06", "GHS07"],
    signalWord: "Danger",
    hazardStatements: [
      "H301 â€“ Toxic if swallowed",
      "H314 â€“ Causes severe skin burns and eye damage",
      "H400 â€“ Very toxic to aquatic life",
    ],
    documents: [],
    applications: [
      "Water Injection Systems",
      "Produced Water Handling",
      "Pipeline Preservation",
      "Hydrostatic Testing",
      "Fracturing Fluid Protection",
    ],
    industries: [
      "Oil & Gas",
      "Refineries",
      "Pipeline Management",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: ["Oilfield Grade"],
    packaging: [
      "210 L HDPE drums",
      "1000 L IBC tanks",
    ],
    minOrderQuantity: "1 MT",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
  {
    id: 16,
    name: "MEA Triazine 78% (High Concentration)",
    slug: "mea-triazine-78-high-concentration",
    sku: "VCP-IND-0015",
    formula: "C6H15N3O3",
    casNumber: "4719-04-4",
    category: "industrial",
    subcategory: "Oilfield Chemicals",
    metaTitle: "Triazine Based H2S Scavenger - MEA Triazine 78% Manufacturer Vasudev Chemo Pharma",
    metaDescription: "Leading manufacturer of high-concentration MEA Triazine 78%. Export-ready H2S scavenger for global oilfield services. Guaranteed purity and performance.",
    description: "For large-scale industrial operators, chemical purity and concentration are the keys to logistical efficiency. Vasudev Chemo Pharmaâ€™s High-Concentration MEA Triazine 78% is the preferred choice for international oilfield service companies requiring bulk, export-ready H2S scavenging solutions. This high-active formulation is specifically engineered to maximize H2S removal capacity per liter, significantly reducing the frequency of chemical deliveries.",
    appearance: "Clear to light yellow liquid",
    molecularWeight: "177.20 g/mol",
    hsCode: "29336990",
    specs: {
      "Active Matter": "â‰¥ 78%",
      "Specific Gravity": "1.10 â€“ 1.15",
      "Reaction Capacity": "Maximum per Liter",
      "Export Standard": "ISO 9001:2015",
    },
    safetyClass: "Irritant",
    ghsPictograms: ["GHS07"],
    signalWord: "Warning",
    hazardStatements: [
      "H315 â€“ Causes skin irritation",
      "H319 â€“ Causes serious eye irritation",
    ],
    documents: [],
    applications: [
      "Offshore H2S Scavenging",
      "Remote Well Site Treatment",
      "Bulk Export Operations",
      "High-Sulfur Gas Streams",
    ],
    industries: [
      "Oil & Gas",
      "International Logistics",
      "Energy Sector",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: ["Premium Oilfield Grade"],
    packaging: [
      "210 L drums",
      "1000 L IBC tanks",
      "ISO Tanks",
    ],
    minOrderQuantity: "1 MT",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
  {
    id: 17,
    name: "MMA Triazine 40% (BTX-Free)",
    slug: "mma-triazine-40-btx-free",
    sku: "VCP-IND-0016",
    formula: "C3H6N6",
    casNumber: "108-74-7",
    category: "industrial",
    subcategory: "Oilfield Chemicals",
    metaTitle: "Triazine Based H2S Scavenger - MMA Triazine 40% Manufacturer Vasudev Chemo Pharma",
    metaDescription: "Discover the benefits of BTX-Free MMA Triazine 40% for H2S removal. Safer for the environment, reduced solids formation.",
    description: "Safety and environmental stewardship are transforming the oilfield chemical market. Vasudev Chemo Pharmaâ€™s BTX-Free MMA Triazine 40% represents the next generation of H2S scavenging technology, specifically designed to eliminate the presence of hazardous aromatics like Benzene, Toluene, and Xylene. Our MMA Triazine 40% provides the powerful H2S neutralization you need without introducing regulated BTX compounds into your system.",
    appearance: "Clear liquid",
    molecularWeight: "126.12 g/mol",
    hsCode: "29336990",
    specs: {
      "BTX Content": "None Detected",
      "Freeze Point Resistance": "Superior",
      "Eco-Compliance": "ESG Ready",
      "Solubility": "High (No Fouling)",
    },
    safetyClass: "Irritant",
    ghsPictograms: ["GHS07"],
    signalWord: "Warning",
    hazardStatements: [
      "H315 â€“ Causes skin irritation",
      "H319 â€“ Causes serious eye irritation",
    ],
    documents: [],
    applications: [
      "Refinery Overhead Treatment",
      "Municipal Sewage Odor Control",
      "Landfill Gas Purification",
      "Sensitive Ecosystem Operations",
    ],
    industries: [
      "Environmental Services",
      "Refineries",
      "Wastewater Treatment",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: ["Environmental Grade"],
    packaging: [
      "210 L drums",
      "1000 L IBC tanks",
    ],
    minOrderQuantity: "1 MT",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
];

export const products: Product[] = productCatalog.filter(
  (product) => !isRemovedProductSlug(product.slug)
);

/** Find a product by slug */
export function getProductBySlug(slug: string): Product | undefined {
  if (isRemovedProductSlug(slug)) return undefined;
  return products.find((p) => p.slug === slug);
}

/** Get all active product slugs for static generation */
export function getAllProductSlugs(): string[] {
  return products.filter((p) => p.status === "active").map((p) => p.slug);
}

/** Get related products (same category, excluding current) */
export function getRelatedProducts(
  currentSlug: string,
  category: string,
  limit = 3
): Product[] {
  return products
    .filter((p) => p.category === category && p.slug !== currentSlug && p.status === "active")
    .slice(0, limit);
}


