type ProductKeywordConfig = {
  primaryKeyword: string;
  longTailKeywords: string[];
};

const MEA_TRIAZINE_PRODUCT_PAGE_KEYWORDS: ProductKeywordConfig = {
  primaryKeyword: "MEA triazine 78% H2S scavenger",
  longTailKeywords: [
    "MEA triazine H2S scavenger supplier",
    "MEA triazine 78 manufacturer",
    "monoethanolamine triazine CAS 4719-04-4",
    "H2S scavenger for sour gas",
    "MEA triazine exporter India",
    "MEA triazine drum IBC bulk supply",
    "oilfield H2S scavenger manufacturer",
    "MEA triazine technical data sheet",
  ],
};

export const PRODUCT_SEO_KEYWORDS: Record<string, ProductKeywordConfig> = {
  "mea-triazine-78-h2s-scavenger": {
    primaryKeyword: "MEA triazine 78% H2S scavenger",
    longTailKeywords: [
      // Primary, commercial, and application keywords
      "MEA triazine H2S scavenger",
      "MEA triazine 78%",
      "triazine scavenger",
      "TACELENE Cam 62081",
      "MEA triazine",
      "triazine based h2s scavenger",
      "Hydrogen Sulfide Scavenger",
      "monoethanolamine triazine H2S scavenger",
      "monoethanolamine triazine 78%",
      "MEA triazine hydrogen sulfide scavenger",
      "H2S scavenger triazine oil and gas",
      "triazine H2S scavenger natural gas",
      "triazine H2S scavenger crude oil",
      "triazine H2S scavenger supplier",
      "buy MEA triazine scavenger",
      "MEA triazine scavenger price",
      "MEA triazine scavenger manufacturer",
      "hexahydro triazine H2S scavenger",
      "H2S scavenger for sour gas",
      "triazine H2S scavenger dosing",
      "hydrogen sulfide removal chemical",
      "oilfield H2S scavenger",
      "gas sweetening chemical triazine",
      "MEA triazine vs MMA triazine",
      "treatmenttriazine scavenger wastewater ",
      "triazine biogas H2S removal",
      "water-soluble H2S scavenger",
      "MEA triazine supplier",
      "MEA triazine manufacturer",
      "MEA triazine exporter",
      "H2S scavenger manufacturer India",
      "MEA triazine supplier India",
      "MEA triazine exporter India",
      "MEA triazine supplier UAE",
      "MEA triazine supplier USA",
      "MEA triazine supplier UK",
      "MEA triazine supplier Vietnam",
      "MEA triazine Vietnam",
      "H2S scavenger supplier Vietnam",
      "oilfield chemical supplier India",

      // ── Vietnam market keywords ──────────────────────────
      "MEA triazine 78% Vietnam",
      "buy MEA triazine Vietnam",
      "MEA triazine import Vietnam",
      "H2S scavenger Vietnam oil gas",
      "triazine supplier Ho Chi Minh City",
      "MEA triazine CIF Vietnam",
      "H2S removal chemical Vietnam",
      "oilfield chemicals Vietnam",
      "sour gas treatment Vietnam",
      "natural gas sweetening Vietnam",
      "PetroVietnam H2S scavenger",
      "hydrogen sulfide scavenger Vietnam",
      "triazine import Vietnam wholesale",
      "MEA triazine distributor Vietnam",
      "petroleum additives Vietnam",
      "MEA triazine ASEAN supplier",
      "triazine supplier Southeast Asia",
      "H2S scavenger offshore Vietnam",
      "Bach Ho field H2S scavenger",
      "Ca Mau gas processing chemical",
      "Nghi Son refinery chemical supplier",

      // ── Vietnamese-language keywords ─────────────────────
      "chất hấp thụ H2S triazine",
      "hóa chất khử hydro sulfide",
      "chất khử H2S cho dầu khí",
      "hóa chất xử lý khí chua triazine",
      "triazine xử lý khí chua",
      "hóa chất khử lưu huỳnh",
      "nhà cung cấp MEA triazine Việt Nam",

      // ── Competitor brand keywords (Vietnam-visible) ──────
      "BK Biocide",
      "BK Biocide H2S scavenger",
      "Grotan BK equivalent Vietnam",
      "Grotan BK alternative",
      "MEA-T H2S scavenger",
      "Onyxide 200 alternative",
      "Busan 1060 alternative",
      "Nuosept 78 equivalent",
      "Triadine 3 alternative",
      "Scavtreat alternative",
      "ChampionX H2S scavenger alternative",
      "Halliburton triazine alternative",
      "Baker Hughes H2S scavenger alternative",

      // ── Concentration & spec keywords ────────────────────
      "MEA triazine 42%",
      "MEA triazine 60%",
      "MEA triazine 80%",
      "high concentration triazine scavenger",
      "triazine 78% active concentration",
      "MEA triazine IBC drum supply",
      "MEA triazine 200L drum",
      "MEA triazine ISO tank",
      "triazine specific gravity 1.10",
      "triazine pH 9-12",

      // ── Market & industry keywords ───────────────────────
      "MEA triazine market size",
      "MEA triazine market growth",
      "triazine market forecast",
      "H2S scavenger market demand",
      "MEA vs MMA triazine comparison",
      "water-soluble triazine biocide",
      "triazine biocide metalworking",
      "triazine cutting fluid preservative",
      "triazine pulp paper biocide",
      "triazine electroplating chemical",
      "triazine coatings preservative",
      "geothermal H2S scavenger",
      "drilling fluid additive triazine",
      "pipeline injection chemical triazine",
      "corrosion prevention H2S triazine",

      // ── USA market keywords ─────────────────────────────
      "MEA triazine 78% USA",
      "buy MEA triazine USA",
      "MEA triazine supplier United States",
      "H2S scavenger supplier United States",
      "wholesale MEA triazine USA",
      "bulk MEA triazine USA",
      "MEA triazine distributor USA",
      "triazine H2S scavenger Permian Basin",
      "H2S scavenger Eagle Ford shale",
      "MEA triazine Marcellus shale",
      "H2S scavenger Bakken formation",
      "H2S scavenger Haynesville shale",
      "triazine scavenger midstream gas processing",
      "H2S scavenger natural gas pipeline USA",
      "crude oil sweetening triazine USA",
      "biogas purification triazine USA",
      "landfill gas H2S scavenger",
      "SAGD H2S treatment triazine",
      "LPG H2S scavenger triazine",
      "MEA triazine CIF Houston",
      "MEA triazine import Houston port",
      "triazine TSCA listed chemical",
      "H2S scavenger OSHA compliant",
      "DOT shipping H2S scavenger UN3082",
      "triazine solids formation prevention",
      "automated chemical injection triazine",
      "amine treater vent scrubber triazine",
      "non-regenerable H2S scavenger",
      "triazine vs iron sponge H2S removal",
      "triazine dosing rate oilfield calculator",

      // ── USA competitor brand keywords ───────────────────
      "Pro3 H2S scavenger alternative",
      "Pro3 HT triazine alternative",
      "PureMark M500 alternative",
      "PureMark B800 alternative",
      "Enviro-Scrub alternative",
      "HSCAV-80 equivalent",
      "Kontin triazine alternative",
      "HS-1526-40 triazine equivalent",
      "Sulfa-Check alternative",
      "Hexion triazine alternative",
      "Stepan triazine alternative",
      "Multi-Chem H2S scavenger alternative",
      "Ecolab triazine alternative",
      "Dow Bioban GK alternative",
      "BASF Protectol HT alternative",

      // ── USA concentration variants ──────────────────────
      "MEA triazine 30%",
      "MEA triazine 50%",
      "MEA triazine 70%",
      "custom concentration triazine supplier",

      // ── UAE / GCC market keywords ───────────────────────
      "MEA triazine 78% UAE",
      "MEA triazine supplier Dubai",
      "MEA triazine supplier Abu Dhabi",
      "H2S scavenger supplier UAE",
      "buy MEA triazine Dubai wholesale",
      "MEA triazine CIF Jebel Ali",
      "oilfield chemicals supplier UAE",
      "sour gas treatment chemical UAE",
      "gas sweetening chemical UAE",
      "ADNOC H2S scavenger supplier",
      "Shah gas field H2S scavenger",
      "Habshan Ruwais chemical supplier",
      "Ghasha ultra-sour gas scavenger",
      "H2S scavenger supplier Saudi Arabia",
      "MEA triazine supplier Oman",
      "H2S scavenger Qatar gas",
      "MEA triazine supplier Kuwait",
      "GCC oilfield chemicals supplier",
      "MENA region chemical supplier",
      "triazine re-export Jebel Ali FTZ",
      "MEA triazine bulk supplier GCC",
      "Dubai chemical trading company",
      "Abu Dhabi EHS compliant chemical",

      // ── Oman market keywords ──────────────────────────
      "MEA triazine 78% Oman",
      "buy MEA triazine Oman",
      "MEA triazine supplier Oman",
      "H2S scavenger supplier Muscat",
      "H2S scavenger Sohar port supplier",
      "triazine based H2S scavenger supplier Oman",
      "monoethanolamine triazine 78% Oman",
      "oilfield chemical supplier Oman",
      "H2S scavenger PDO operations Oman",
      "sour gas treatment chemical Oman",
      "triazine hydrogen sulfide scavenger Oman oil gas",
      "H2S removal chemical natural gas Oman",
      "H2S scavenger Oman LNG",
      "H2S scavenger BP Khazzan Oman",
      "triazine wellhead injection Oman",
      "gas sweetening chemical Oman",
      "triazine produced water treatment Oman",
      "chemical supplier India to Oman",
      "oilfield chemical import Oman",
      "triazine chemical shipping Sohar port",
      "MEA triazine price per kg Oman",
      "triazine 78% bulk order Oman",
      "H2S scavenger PDO approved supplier",
      "MEA triazine CIF Sohar",
      "triazine H2S scavenger manufacturer India to Oman",

      // ── Oman competitor brand keywords ────────────────
      "RXSOL triazine Oman alternative",
      "RXSOL-11-5014-210 Oman equivalent",
      "SULFA-CLEAR 8411HC equivalent Oman",
      "MC MX 2-1106 alternative Oman",
      "OS TRI-SCAV alternative",
      "MBBT H2S scavenger Oman alternative",
      "ICPL triazine Oman alternative",
      "OOISS triazine Oman alternative",

      // ── Arabic-language keywords ────────────────────────
      "مزيل كبريتيد الهيدروجين ترايازين",
      "كاسح H2S ترايازين",
      "مادة إزالة كبريتيد الهيدروجين",
      "معالجة الغاز الحامض ترايازين",
      "كيماويات النفط والغاز الإمارات",
      "مورد ترايازين دبي",
      "كيماويات حقول النفط",
      "مبيد حيوي ترايازين",
      "إزالة الكبريت",
      "كاسح كبريتيد الهيدروجين عُمان",
      "مورد مواد كيميائية لإزالة H2S في عمان",
      "معالجة الغاز الحامض عُمان",
      "مواد كيميائية لحقول النفط عُمان",
      "ترايازين لإزالة كبريتيد الهيدروجين",

      // ── Egypt market keywords ─────────────────────────
      "MEA triazine 78% Egypt",
      "triazine based h2s scavenger",
      "triazine based h2s scavenger and corrsion inhibitor",
      "buy MEA triazine Egypt",
      "MEA triazine supplier Egypt",
      "H2S scavenger supplier Cairo",
      "H2S scavenger supplier Alexandria",
      "triazine based H2S scavenger supplier Egypt",
      "monoethanolamine triazine 78% Egypt",
      "oilfield chemical supplier Egypt",
      "H2S scavenger Zohr gas field Egypt",
      "sour gas treatment chemical Nile Delta",
      "triazine H2S scavenger Western Desert Egypt",
      "H2S removal chemical natural gas Egypt",
      "H2S scavenger MIDOR refinery Egypt",
      "H2S scavenger Nooros field Egypt",
      "H2S scavenger Assiut refinery Egypt",
      "gas sweetening chemical Egypt",
      "triazine produced water treatment Egypt",
      "chemical supplier India to Egypt",
      "oilfield chemical import Egypt",
      "triazine chemical shipping Alexandria port",
      "MEA triazine price per kg Egypt",
      "triazine 78% bulk order Egypt",
      "MEA triazine CIF Alexandria",
      "MEA triazine CIF Damietta",
      "triazine H2S scavenger manufacturer India to Egypt",

      // ── Egypt competitor brand keywords ───────────────
      "ACPA H2S scavenger Egypt alternative",
      "Scomi Egypt triazine alternative",
      "AquaNile H2S scavenger alternative",
      "ICG MEA triazine Egypt alternative",
      "Filtron H2S scavenger Egypt alternative",

      // ── Egypt Arabic keywords ─────────────────────────
      "مادة كاسحة لكبريتيد الهيدروجين مصر",
      "مورد كيماويات حقول النفط مصر",
      "معالجة الغاز الحامض مصر",
      "كاسح كبريتيد الهيدروجين مصر",
      "مورد ترايازين مصر",
      "كيماويات حقول النفط القاهرة",
      "إزالة H2S من الغاز الطبيعي مصر",

      // ── Brazil market keywords ────────────────────────
      "MEA triazine 78% Brazil",
      "buy MEA triazine Brazil",
      "MEA triazine supplier Brazil",
      "H2S scavenger supplier Brazil",
      "monoethanolamine triazine 78% Brazil",
      "oilfield chemical supplier Brazil",
      "H2S scavenger pre-salt operations Brazil",
      "H2S scavenger Santos Basin deepwater",
      "H2S scavenger Campos Basin",
      "triazine H2S scavenger Buzios field",
      "H2S treatment Petrobras FPSO",
      "H2S scavenger Tupi Lula field Brazil",
      "gas sweetening chemical Brazil",
      "H2S scavenger biogas ethanol Brazil",
      "triazine produced water treatment Brazil",
      "sour gas treatment chemical Brazil",
      "triazine wellhead injection deepwater Brazil",
      "H2S scavenger crude oil export Brazil",
      "chemical supplier India to Brazil",
      "oilfield chemical import Brazil",
      "triazine chemical shipping Santos port",
      "MEA triazine price per kg Brazil",
      "triazine 78% bulk order Brazil",
      "MEA triazine CIF Santos",
      "MEA triazine CIF Paranaguá",
      "triazine H2S scavenger manufacturer India to Brazil",

      // ── Brazil competitor brand keywords ──────────────
      "SCAVTREAT 1063 alternative Brazil",
      "ABATE S-200 alternative Brazil",
      "Global Trend MEA-Triazina alternative",
      "Brenntag triazine Brazil alternative",
      "BerrySweet triazine alternative",
      "Nalco Ecolab H2S scavenger alternative Brazil",
      "SLB triazine H2S scavenger alternative Brazil",

      // ── Portuguese (PT-BR) keywords ───────────────────
      "removedor de H2S triazina MEA",
      "captador de H2S para petróleo e gás",
      "triazina MEA 78% para remoção de H2S",
      "comprar triazina MEA 78% industrial Brasil",
      "fornecedor de H2S scavenger Brasil",
      "fornecedor de triazina MEA Brasil",
      "captador de sulfeto de hidrogênio",
      "tratamento de gás ácido triazina",
      "biocida industrial triazina",
      "sequestrante de H2S triazina",
      "químicos para campos de petróleo Brasil",
      "triazina para operações de pré-sal",
      "importar triazina MEA da Índia para o Brasil",

      // ── Saudi Arabia market keywords ──────────────────
      "MEA triazine 78% Saudi Arabia",
      "buy MEA triazine Saudi Arabia",
      "MEA triazine supplier Saudi Arabia",
      "H2S scavenger supplier Saudi Arabia",
      "mono ethanol amine triazine manufacturer Saudi Arabia",
      "H2S scavenger supplier Dammam",
      "H2S scavenger supplier Jubail",
      "triazine based H2S scavenger supplier KSA",
      "monoethanolamine triazine 78% Saudi Arabia",
      "oilfield chemical supplier Saudi Arabia",
      "H2S scavenger Saudi Aramco operations",
      "H2S scavenger Ghawar field",
      "H2S scavenger Wasit gas plant",
      "H2S scavenger Fadhili gas plant",
      "H2S scavenger Haradh gas plant",
      "H2S scavenger Khurais field Saudi",
      "H2S scavenger Safaniyah field",
      "H2S scavenger Jafurah gas field",
      "sour gas treatment chemical KSA",
      "NGL processing chemical Saudi",
      "gas sweetening chemical Saudi Arabia",
      "triazine wellhead injection Saudi",
      "H2S scavenger SABIC petrochemicals",
      "triazine produced water treatment KSA",
      "SAMSS approved H2S scavenger",
      "SASO compliant chemical import",
      "IKTVA compliant chemical supplier",
      "MEA triazine price per kg Saudi Arabia",
      "triazine 78% bulk order KSA",
      "MEA triazine CIF Dammam",
      "MEA triazine CIF Jeddah",
      "chemical supplier India to KSA",
      "oilfield chemical import KSA",
      "triazine H2S scavenger manufacturer India to Saudi Arabia",

      // ── Saudi Arabia competitor brand keywords ────────
      "Saudi Multichem Chemara HS-1501 alternative",
      "G-SCAV EA77 alternative KSA",
      "SUGEST H2S scavenger alternative",
      "NassGuard MEA alternative Saudi",
      "ABATE S-200 alternative Saudi",
      "SULFA-CLEAR 8411HC alternative KSA",
      "Dorf Ketal H2S scavenger alternative Saudi",
      "DubiChem triazine biocide alternative KSA",
      "Cola Triazine 50 alternative Saudi",
      "RXSOL triazine alternative KSA",
      "HME-FILM triazine scavenger alternative",

      // ── Saudi Arabia Arabic keywords ──────────────────
      "مزيل كبريتيد الهيدروجين ترايازين السعودية",
      "كاسح H2S ترايازين المملكة العربية السعودية",
      "مورد كيماويات حقول النفط السعودية",
      "مادة معالجة الغاز الحامض ترايازين",
      "مورد ترايازين الدمام",
      "كيماويات حقول نفط أرامكو",
      "مزيل H2S الجبيل",
      "مادة كيميائية لحقول النفط السعودية",
      "كاسح كبريتيد الهيدروجين أرامكو",
      "معالجة الغاز الحامض السعودية",
      "مورد مواد كيميائية الرياض",

      // ── Iraq market keywords ──────────────────────────
      "MEA triazine 78% Iraq",
      "buy MEA triazine Iraq",
      "MEA triazine supplier Iraq",
      "H2S scavenger supplier Iraq",
      "mono ethanol amine triazine manufacturer Iraq",
      "H2S scavenger supplier Basra",
      "H2S scavenger supplier Erbil",
      "triazine based H2S scavenger Iraq",
      "monoethanolamine triazine 78% Iraq",
      "oilfield chemical supplier Iraq",
      "H2S scavenger Rumaila field",
      "H2S scavenger West Qurna field",
      "H2S scavenger Zubair field",
      "H2S scavenger Iraqi Kurdistan oilfields",
      "H2S removal Basra oil operations",
      "H2S scavenger Basra Gas Company",
      "triazine Karbala refinery",
      "triazine Halfaya field Iraq",
      "sour gas treatment chemical Iraq",
      "gas sweetening chemical Iraq",
      "H2S scavenger BP Rumaila JV",
      "H2S scavenger Shell West Qurna JV",
      "H2S scavenger South Oil Company SOC",
      "MEA triazine price per kg Iraq",
      "triazine 78% bulk order Iraq",
      "MEA triazine CIF Umm Qasr",
      "chemical supplier India to Iraq",
      "oilfield chemical import Iraq",
      "triazine H2S scavenger manufacturer India to Iraq",

      // ── Iraq competitor brand keywords ────────────────
      "Tawreed H2S scavenger alternative Iraq",
      "ALDUHA H2S scavenger alternative",
      "SAHARA MEA triazine alternative Rumaila",
      "Federal Group Advanced Chemicals alternative",
      "Baker Hughes H2S scavenger alternative Iraq",
      "Dorf Ketal triazine alternative Iraq",
      "DubiChem triazine biocide alternative Iraq",
      "Petrobon MEA triazine alternative",
      "Ishtar MEA alternative Iraq",
      "Falizan HS-9003 triazine alternative",
      "RXSOL triazine alternative Iraq",

      // ── Iraq Arabic keywords ──────────────────────────
      "كاسح كبريتيد الهيدروجين العراق",
      "مورد كيماويات حقول النفط العراق",
      "مادة معالجة H2S لحقول النفط العراقية",
      "مورد ترايازين البصرة",
      "كيماويات حقول النفط البصرة",
      "كاسح H2S حقل الرميلة",
      "معالجة الغاز الحامض العراق",
      "مورد كيماويات أربيل كردستان",
      "مادة كيميائية لحقول النفط العراق",
      "مورد مواد كيميائية بغداد",

      // ── Qatar market keywords ──────────────────────────
      "MEA triazine 78% Qatar",
      "buy MEA triazine Qatar",
      "MEA triazine supplier Qatar",
      "H2S scavenger supplier Qatar",
      "mono ethanol amine triazine manufacturer Qatar",
      "H2S scavenger supplier Doha",
      "H2S scavenger Ras Laffan supplier",
      "triazine based scavenger supplier Qatar",
      "monoethanolamine triazine 78% Qatar",
      "oilfield chemical supplier Qatar",
      "H2S scavenger QatarEnergy North Field",
      "H2S scavenger Ras Laffan LNG",
      "H2S scavenger Pearl GTL Qatar",
      "H2S scavenger North Field Expansion NFE",
      "H2S scavenger Dolphin gas pipeline",
      "H2S scavenger Dukhan field Qatar",
      "H2S scavenger Mesaieed Industrial City",
      "sour gas treatment chemical Qatar",
      "gas sweetening chemical Qatar",
      "triazine LNG feed gas treatment Qatar",
      "MEA triazine gas processing Qatar",
      "triazine wellhead injection H2S Qatar",
      "triazine produced water treatment Qatar",
      "triazine biocide production fluids Qatar",
      "triazine injection water biocide Qatar",
      "H2S removal chemical Qatar wholesale",
      "MEA triazine price Qatar",
      "MEA triazine price per kg Qatar",
      "triazine 78% bulk order Qatar",
      "chemical supplier India to Qatar",
      "oilfield chemical import Qatar",
      "triazine chemical shipping Hamad Port",
      "MEA triazine CIF Hamad Port",
      "oilfield chemical delivery Qatar 3-5 days",
      "H2S scavenger QatarEnergy approved supplier",
      "MEA triazine CAS 4719-04-4 Qatar",
      "triazine H2S scavenger manufacturer India to Qatar",

      // ── Qatar competitor brand keywords ────────────────
      "BKC Gulf triazine scavenger alternative",
      "BKC Gulf triazine Qatar alternative",
      "RXSOL triazine Qatar alternative",
      "HS-1526-40 triazine equivalent Qatar",
      "SULFA-CLEAR 8411HC alternative Qatar",
      "Univar triazine alternative Qatar",
      "ChampionX H2S scavenger alternative Qatar",
      "Baker Hughes H2S scavenger alternative Qatar",
      "Halliburton triazine alternative Qatar",
      "DubiChem triazine biocide alternative Qatar",
      "K2P MEA-T scavenger alternative",
      "Deluxe Chemical MEA alternative Qatar",
      "ICPL triazine Qatar alternative",
      "G-SCAV EA77 alternative Qatar",

      // ── Qatar Arabic keywords ──────────────────────────
      "كاسح كبريتيد الهيدروجين قطر",
      "مورد ترايازين قطر",
      "مورد مواد كيميائية لمعالجة الغاز قطر",
      "معالجة الغاز الحامض قطر",
      "كيماويات حقول النفط قطر",
      "كاسح H2S حقل الشمال",
      "مزيل كبريتيد الهيدروجين ترايازين قطر",
      "مورد كيماويات صناعية الدوحة",
      "مادة كيميائية لحقول النفط قطر",
      "إزالة H2S من الغاز الطبيعي قطر",

      // ── Kuwait market keywords ─────────────────────────
      "MEA triazine 78% Kuwait",
      "buy MEA triazine Kuwait",
      "MEA triazine supplier Kuwait",
      "H2S scavenger supplier Kuwait",
      "mono ethanol amine triazine manufacturer Kuwait",
      "H2S scavenger supplier Ahmadi Kuwait",
      "triazine based H2S scavenger supplier Kuwait",
      "monoethanolamine triazine 78% Kuwait",
      "oilfield chemical supplier Kuwait",
      "H2S scavenger KOC operations Kuwait",
      "H2S scavenger Burgan field Kuwait",
      "H2S scavenger Ratqa field Kuwait",
      "H2S scavenger Minagish field Kuwait",
      "H2S scavenger Wafra field Kuwait",
      "H2S scavenger KNPC Mina Al Ahmadi refinery",
      "H2S scavenger KNPC Mina Abdullah refinery",
      "sour gas treatment chemical Kuwait",
      "gas sweetening chemical Kuwait",
      "H2S removal chemical natural gas Kuwait",
      "sour crude H2S scavenger Kuwait",
      "triazine produced water treatment Kuwait",
      "triazine biocide production fluids Kuwait",
      "triazine wellhead injection H2S Kuwait",
      "crude oil H2S treatment Kuwait",
      "triazine biocide microbial control Kuwait",
      "H2S scavenger heavy oil Kuwait",
      "H2S removal chemical Kuwait wholesale",
      "MEA triazine price Kuwait",
      "MEA triazine price per kg Kuwait",
      "triazine 78% bulk order Kuwait",
      "chemical supplier India to Kuwait",
      "oilfield chemical import Kuwait",
      "triazine chemical shipping Shuwaikh Port",
      "MEA triazine CIF Shuwaikh Port",
      "oilfield chemical delivery Kuwait 4-6 days",
      "H2S scavenger KOC approved supplier",
      "KEPA compliant chemical import Kuwait",
      "MEA triazine CAS 4719-04-4 Kuwait",
      "triazine H2S scavenger manufacturer India to Kuwait",

      // ── Kuwait competitor brand keywords ────────────────
      "Bait Al Aseel triazine alternative Kuwait",
      "DK Petrochemicals MEA alternative Kuwait",
      "RXSOL triazine Kuwait alternative",
      "HME-FILM MEA triazine alternative Kuwait",
      "HS-1526-40 triazine equivalent Kuwait",
      "SULFA-CLEAR 8411HC alternative Kuwait",
      "ChampionX H2S scavenger alternative Kuwait",
      "Baker Hughes H2S scavenger alternative Kuwait",
      "Dorf Ketal scavenger alternative Kuwait",
      "DubiChem triazine biocide alternative Kuwait",
      "Triasorb triazine alternative",
      "Xipeng MEA triazine alternative",
      "ICPL triazine Kuwait alternative",

      // ── Kuwait Arabic keywords ─────────────────────────
      "كاسح كبريتيد الهيدروجين الكويت",
      "مورد ترايازين الكويت",
      "مادة إزالة H2S لحقول نفط الكويت",
      "معالجة الغاز الحامض الكويت",
      "كيماويات حقول النفط الكويت",
      "كاسح H2S حقل برقان",
      "مورد كيماويات صناعية الأحمدي",
      "مزيل كبريتيد الهيدروجين ترايازين الكويت",
      "مادة كيميائية لحقول النفط الكويت",
      "إزالة H2S من الغاز الطبيعي الكويت",

      // ── Thailand market keywords ───────────────────────
      "MEA triazine 78% Thailand",
      "buy MEA triazine Thailand",
      "MEA triazine supplier Thailand",
      "H2S scavenger supplier Thailand",
      "mono ethanol amine triazine manufacturer Thailand",
      "H2S scavenger supplier Bangkok",
      "triazine based H2S scavenger Thailand",
      "monoethanolamine triazine 78% Thailand",
      "oilfield chemical supplier Thailand",
      "H2S scavenger PTTEP operations Thailand",
      "H2S scavenger Gulf of Thailand offshore",
      "H2S scavenger Map Ta Phut petrochemical",
      "sour gas treatment chemical Thailand",
      "gas sweetening chemical Thailand",
      "H2S removal natural gas Thailand",
      "H2S scavenger biogas palm oil Thailand",
      "H2S scavenger biogas cassava processing",
      "H2S scavenger landfill gas Thailand",
      "triazine biocide water treatment Thailand",
      "triazine offshore platform Gulf of Thailand",
      "triazine wellhead injection H2S Thailand",
      "H2S removal chemical Thailand wholesale",
      "MEA triazine price Thailand",
      "MEA triazine price per kg Thailand",
      "triazine 78% bulk order Thailand",
      "chemical supplier India to Thailand",
      "oilfield chemical import Thailand",
      "triazine chemical shipping Laem Chabang",
      "MEA triazine CIF Laem Chabang",
      "MEA triazine CIF Bangkok Port",
      "oilfield chemical delivery Thailand 7-10 days",
      "MEA triazine CAS 4719-04-4 Thailand",
      "triazine H2S scavenger manufacturer India to Thailand",
      "raw MEA vs MEA triazine scavenger Thailand",
      "MEA triazine ASEAN supplier",
      "H2S scavenger Southeast Asia",

      // ── Thailand competitor brand keywords ─────────────
      "Brenntag MEA alternative Thailand",
      "PTT GC MEA alternative Thailand",
      "Krungthep Trading MEA alternative",
      "BK Biocide alternative Thailand",
      "ECHEMI MEA triazine alternative Thailand",
      "Borregaard H2S scavenger alternative",
      "Dayong MEA triazine alternative Thailand",
      "HS-1526-40 triazine equivalent Thailand",
      "ChampionX H2S scavenger alternative Thailand",
      "IRO Group triazine alternative Thailand",
      "K2P MEA-T alternative Thailand",
      "Xipeng MEA triazine alternative Thailand",

      // ── Thai-language keywords ─────────────────────────
      "สารกำจัด H2S ไตรอะซีน",
      "สารดักจับไฮโดรเจนซัลไฟด์",
      "สารบำบัดก๊าซเปรี้ยว",
      "ผู้ผลิต MEA ไตรอะซีน ประเทศไทย",
      "ซัพพลายเออร์ไตรอะซีน ประเทศไทย",
      "สารเคมีขจัด H2S สำหรับแก๊สธรรมชาติ",
      "เคมีภัณฑ์สำหรับอุตสาหกรรมน้ำมันและแก๊ส",
      "สารเคมีขจัดไฮโดรเจนซัลไฟด์ก๊าซชีวภาพ",
      "ซื้อ MEA triazine 78% ประเทศไทย",
      "สารเคมีบำบัดก๊าซ ปตท.",
      "สารดักจับ H2S สำหรับแท่นขุดเจาะอ่าวไทย",

      // ── Iran market keywords ───────────────────────────
      "MEA triazine 78% Iran",
      "buy MEA triazine Iran",
      "MEA triazine supplier Iran",
      "H2S scavenger supplier Iran",
      "mono ethanol amine triazine manufacturer Iran",
      "H2S scavenger supplier Tehran",
      "triazine based H2S scavenger Iran",
      "monoethanolamine triazine 78% Iran",
      "oilfield chemical supplier Iran",
      "H2S scavenger NIOC operations Iran",
      "H2S scavenger South Pars gas field",
      "H2S scavenger Assaluyeh gas processing",
      "H2S scavenger NIGC gas processing",
      "sour gas treatment chemical Iran",
      "gas sweetening chemical Iran",
      "H2S removal chemical natural gas Iran",
      "H2S scavenger Isfahan refinery",
      "H2S scavenger Abadan refinery",
      "H2S scavenger Bandar Abbas refinery",
      "H2S scavenger NPC petrochemical Iran",
      "sour crude H2S scavenger Iran",
      "triazine biocide production fluids Iran",
      "triazine wellhead injection Iran",
      "H2S removal chemical Iran wholesale",
      "MEA triazine price Iran",
      "MEA triazine price per kg Iran",
      "triazine 78% bulk order Iran",
      "chemical supplier India to Iran",
      "oilfield chemical import Iran",
      "MEA triazine CIF Bandar Abbas",
      "oilfield chemical delivery Iran 3-5 days",
      "MEA triazine CAS 4719-04-4 Iran",
      "triazine H2S scavenger manufacturer India to Iran",
      "MEA triazine 80% vs 78% concentration",
      "raw MEA vs MEA triazine scavenger Iran",

      // ── Iran competitor brand keywords ─────────────────
      "Tsorb3400 alternative Iran",
      "Tasfyeh Group triazine alternative Iran",
      "Chemical Iran MEA alternative",
      "IranChemicalMine MEA alternative",
      "RXSOL triazine alternative Iran",
      "Triasorb Sintez-Oka alternative Iran",
      "ChampionX H2S scavenger alternative Iran",
      "Baker Hughes H2S scavenger alternative Iran",
      "HS-1526-40 triazine equivalent Iran",
      "SULFA-CLEAR alternative Iran",
      "Sarex HPT triazine alternative Iran",

      // ── Farsi (Persian) keywords ───────────────────────
      "حذف‌کننده H2S تری‌آزین",
      "حذف‌کننده سولفید هیدروژن ایران",
      "تری‌آزین تأمین‌کننده ایران",
      "تصفیه گاز ترش ایران",
      "شیمیایی حذف H2S برای صنعت نفت و گاز",
      "مواد شیمیایی صنعتی میدان پارس جنوبی",
      "خرید تری‌آزین MEA ایران",
      "مبارزه با خوردگی H2S ایران",
      "شیمیایی حفاری و تولید نفت ایران",
      "تأمین‌کننده مواد شیمیایی بندرعباس",
      "شیمیایی پالایشگاه اصفهان آبادان",

      // ── Russia market keywords ─────────────────────────
      "MEA triazine 78% Russia",
      "buy MEA triazine Russia",
      "MEA triazine supplier Russia",
      "H2S scavenger supplier Russia",
      "mono ethanol amine triazine manufacturer Russia",
      "H2S scavenger supplier Moscow",
      "triazine based H2S scavenger Russia",
      "monoethanolamine triazine 78% Russia",
      "oilfield chemical supplier Russia",
      "H2S scavenger Gazprom gas processing",
      "H2S scavenger West Siberia oil fields",
      "H2S scavenger Rosneft operations",
      "H2S scavenger Lukoil upstream",
      "H2S scavenger Yamal LNG",
      "H2S scavenger Sakhalin projects",
      "sour gas treatment chemical Russia",
      "gas sweetening chemical Russia",
      "H2S removal natural gas Russia",
      "H2S scavenger associated gas treatment Russia",
      "triazine biocide production fluids Russia",
      "triazine wellhead injection Russia",
      "H2S scavenger pipeline treatment Russia",
      "gas condensate H2S treatment Russia",
      "H2S removal chemical Russia wholesale",
      "MEA triazine price Russia",
      "triazine 78% bulk order Russia",
      "chemical supplier India to Russia",
      "oilfield chemical import Russia",
      "MEA triazine CIF Novorossiysk",
      "MEA triazine CIF Vladivostok",
      "oilfield chemical delivery Russia 14-21 days",
      "EAEU customs clearance chemical triazine",
      "GOST chemical import requirements",
      "MEA triazine CAS 4719-04-4 Russia",

      // ── Russia competitor brand keywords ───────────────
      "Triasorb alternative Russia",
      "Sintez-Oka triazine alternative Russia",
      "Mirrico H2S scavenger alternative Russia",
      "NIKA-Synthetics triazine alternative",
      "Himeko triazine alternative Russia",
      "Kazanorgsintez MEA alternative",
      "Elarum MEA alternative Russia",
      "Sinotrust MEA triazine alternative Russia",
      "HME-FILM triazine alternative Russia",
      "HS-1526-40 triazine equivalent Russia",
      "Sinolook MEA alternative Russia",

      // ── Russian-language keywords ──────────────────────
      "нейтрализатор сероводорода триазин",
      "поглотитель H2S триазин МЭА 78%",
      "триазин МЭА поставщик Россия",
      "купить триазин МЭА 78%",
      "поставщик реагента для очистки газа",
      "удаление сероводорода из природного газа",
      "химический реагент очистка попутного газа",
      "нейтрализатор H2S нефтегазовая промышленность",
      "Трайасорб альтернатива Россия",
      "триазин десульфуратор купить",
      "осушка и очистка газа триазин",
      "реагент для обработки скважин H2S",
      "поставщик химических реагентов из Индии",
      "Миррико альтернатива H2S нейтрализатор",

      // ── UAE competitor brand keywords ───────────────────
      "RXSOL triazine biocide alternative",
      "RXSOL-43-8160-210 equivalent",
      "Saudi Multichem triazine alternative",
      "Geco Chemicals UAE alternative",
      "Dorf Ketal H2S scavenger alternative",
      "G-SCAV EA77 equivalent",
      "BASOLON SC 78 alternative",
      "STEPANQUAT 200 alternative",
      "Scomi Group H2S scavenger alternative",

      // CAS / IUPAC
      "CAS 4719-04-4",
      "CAS 4719-04-4 H2S scavenger",
      "hexahydro-1,3,5-tris(2-hydroxyethyl)-s-triazine",
      "1,3,5-Triazine-1,3,5(2H,4H,6H)-triethanol",
      // Functional keywords
      "H2S scavenger",
      "hydrogen sulfide scavenger",
      "desulfurizer",
      "gas sweetener",
      "mercaptan scavenger triazine",
      "sour gas treatment chemical",
      "natural gas sweetening chemical",

      // Additional India target keywords from competitor and SERP research
      "h2s scavenger 78 manufacturer in India",
      "monoethanolamine-triazine supplier in India",
      "monoethanolamine triazine India",
      "H2S Scavengers and Triazine-Based Gas Treatment Chemicals",
      "MEA Triazine 70%",
      "MEA Triazine manufacturers in India",
      "MEA Triazine 78 suppliers in India",
      "triazine manufacturer in India",
      "triazine based H2S scavenger manufacturer",
      "MEA Triazine by Kwantum India",
      "water based biocide",
      "biocides for metalworking fluids",
      "Tacelene Chem 62090",
      "Tacelene Chem 62087",
      "Tacelene Chem 62081",
      "JadeScan 54",
      "monoethanolamine triazine",
      "amine base triazine",
      "CAS no. 4719-04-4",
      "biocide used as H2S scavenger",
      "oil drilling fluids",
      "drilling fluids biocide",
      "HSCAV-70",
      "Nipacide BK",
      "Melzer speciality water treatment",
      "Melzer water treatment alternative",
      "Kwantum India triazine alternative",
      "water treatment biocide India",
    ],
  },
  "mma-triazine-40": {
    primaryKeyword: "mma triazine 40 supplier",
    longTailKeywords: [
      "mma triazine 40 percent h2s scavenger",
      "btx free h2s scavenger chemical supplier",
      "buy mma triazine 40 industrial grade",
    ],
  },
  "p-toluenesulfonic-acid": {
    primaryKeyword: "p-toluenesulfonic acid manufacturer india",
    longTailKeywords: [
      "ptsa catalyst supplier for resin manufacturing",
      "p toluenesulfonic acid cas 104-15-4 supplier",
      "buy p toluenesulfonic acid industrial grade",
    ],
  },
  "copper-sulphate": {
    primaryKeyword: "copper sulphate exporter india",
    longTailKeywords: [
      "copper sulphate pentahydrate supplier bulk",
      "copper sulphate cas 7758-99-8 manufacturer",
      "buy copper sulphate industrial grade india",
    ],
  },
  "manganese-sulphate": {
    primaryKeyword: "manganese sulphate manufacturer",
    longTailKeywords: [
      "manganese sulphate monohydrate supplier india",
      "manganese sulphate cas number chemical supplier",
      "buy manganese sulphate industrial grade",
    ],
  },
  "sodium-cumene-sulfonate-40": {
    primaryKeyword: "sodium cumene sulfonate 40% manufacturer India",
    longTailKeywords: [
      // ── Primary product & synonym keywords ──────────────
      "sodium cumene sulfonate 40%",
      "sodium cumene sulphonate 40%",
      "SCS-40",
      "SCS 40%",
      "sodium cumenesulfonate 40%",
      "sodium cumene sulfonate liquid",
      "sodium isopropylbenzenesulfonate 40%",
      "sodium salt of cumene sulfonic acid 40%",
      "benzenesulfonic acid 1-methylethyl sodium salt",
      "CAS 28348-53-0",

      // ── Application & industry keywords ─────────────────
      "hydrotrope for liquid detergent",
      "coupling agent detergent formulation",
      "solubilizer surfactant system",
      "cloud point depressant",
      "viscosity reducer detergent",
      "hydrotrope for industrial cleaner",
      "sodium cumene sulfonate for shampoo",
      "sodium cumene sulfonate personal care",
      "sodium cumene sulfonate oilfield chemicals",
      "sodium cumene sulfonate drilling fluids",
      "sodium cumene sulfonate textile dyeing",
      "sodium cumene sulfonate agrochemicals",
      "hydrotrope for household cleaner",
      "dispersant industrial formulation",
      "anionic surfactant hydrotrope",
      "sodium cumene sulfonate metal processing",

      // ── Buyer-intent & commercial keywords ──────────────
      "sodium cumene sulfonate 40% supplier",
      "sodium cumene sulfonate 40% manufacturer",
      "sodium cumene sulfonate 40% exporter",
      "buy sodium cumene sulfonate 40% bulk",
      "sodium cumene sulfonate 40% price",
      "sodium cumene sulfonate bulk supplier India",
      "sodium cumene sulfonate wholesale",
      "sodium cumene sulfonate manufacturer Gujarat",
      "sodium cumene sulfonate exporter India",

      // ── Technical specification keywords ─────────────────
      "sodium cumene sulfonate liquid form",
      "sodium cumene sulfonate 40% active matter",
      "hydrotrope liquid concentrate",
      "sodium cumene sulfonate pH 7-9",
      "sodium cumene sulfonate 240 kg drum",
      "sodium cumene sulfonate certificate of analysis",

      // ── Competitor alternative keywords ─────────────────
      "dolphin pharma SCS alternative",
      "ariix sodium cumene sulfonate alternative",
      "nandadeep SCS alternative",
      "navdeep SCS-40 alternative",
      "nolan chemicals SCS alternative",
      "marine chemical sodium cumene sulfonate alternative",

      // ── Geographic & market keywords ────────────────────
      "sodium cumene sulfonate supplier India",
      "sodium cumene sulfonate supplier Gujarat",
      "sodium cumene sulfonate supplier UAE",
      "sodium cumene sulfonate exporter Middle East",
      "sodium cumene sulfonate supplier Africa",
      "sodium cumene sulfonate CIF price",
    ],
  },
  "sodium-cumene-sulfonate-90": {
    primaryKeyword: "sodium cumene sulfonate 90% manufacturer India",
    longTailKeywords: [
      // ── Primary product & synonym keywords ──────────────
      "sodium cumene sulfonate 90%",
      "sodium cumene sulphonate 90%",
      "SCS-90",
      "SCS 90%",
      "sodium cumenesulfonate 90%",
      "sodium cumene sulfonate powder",
      "sodium isopropylbenzenesulfonate 90%",
      "sodium salt of cumene sulfonic acid 90%",
      "sodium p-cumenesulfonate",
      "sodium cumylsulfonate",
      "cumenesulfonic acid sodium salt",
      "C9H11NaO3S",
      "CAS 28348-53-0",
      "EC number 248-983-7",

      // ── Application & industry keywords ─────────────────
      "hydrotrope powder detergent",
      "coupling agent powder detergent formulation",
      "solubilizer surfactant system",
      "cloud point depressant powder",
      "anti-caking agent detergent powder",
      "hydrotrope for industrial cleaner",
      "sodium cumene sulfonate 90% for shampoo",
      "sodium cumene sulfonate personal care formulation",
      "sodium cumene sulfonate oilfield chemicals",
      "sodium cumene sulfonate drilling fluids additive",
      "sodium cumene sulfonate textile dyeing auxiliary",
      "sodium cumene sulfonate agrochemical formulation",
      "sodium cumene sulfonate household cleaner",
      "dispersant industrial formulation",
      "emulsifier industrial application",
      "anionic surfactant hydrotrope powder",
      "sodium cumene sulfonate metal processing",
      "sodium cumene sulfonate electroplating",

      // ── Buyer-intent & commercial keywords ──────────────
      "sodium cumene sulfonate 90% supplier",
      "sodium cumene sulfonate 90% manufacturer",
      "sodium cumene sulfonate 90% exporter",
      "buy sodium cumene sulfonate 90% bulk",
      "sodium cumene sulfonate 90% price",
      "sodium cumene sulfonate 90% price per kg",
      "sodium cumene sulfonate bulk supplier India",
      "sodium cumene sulfonate wholesale supplier",
      "sodium cumene sulfonate manufacturer Gujarat",
      "sodium cumene sulfonate exporter India",
      "sodium cumene sulfonate minimum order quantity",

      // ── Technical specification keywords ─────────────────
      "sodium cumene sulfonate 90% active matter",
      "sodium cumene sulfonate 98% purity",
      "sodium cumene sulfonate white powder",
      "sodium cumene sulfonate off-white powder",
      "sodium cumene sulfonate sulfone content below 1%",
      "sodium cumene sulfonate free sulphate",
      "sodium cumene sulfonate 15 kg bag",
      "sodium cumene sulfonate 25 kg bag",
      "sodium cumene sulfonate certificate of analysis",
      "sodium cumene sulfonate MSDS safety data sheet",

      // ── Competitor alternative keywords ─────────────────
      "dolphin pharma SCSDOL-90 alternative",
      "ariix sodium cumene sulfonate 90 alternative",
      "nandadeep SCS 90 alternative",
      "navdeep SCS-90 alternative",
      "nolan chemicals SCS powder alternative",
      "marine chemical sodium cumene sulfonate 93 alternative",
      "ataman chemicals sodium cumenesulfonate alternative",
      "multichemexports sodium cumene sulphonate alternative",

      // ── Geographic & market keywords ────────────────────
      "sodium cumene sulfonate supplier India",
      "sodium cumene sulfonate supplier Gujarat",
      "sodium cumene sulfonate supplier Ahmedabad",
      "sodium cumene sulfonate supplier UAE",
      "sodium cumene sulfonate supplier Dubai",
      "sodium cumene sulfonate exporter Middle East",
      "sodium cumene sulfonate supplier Africa",
      "sodium cumene sulfonate supplier Southeast Asia",
      "sodium cumene sulfonate CIF price",
      "sodium cumene sulfonate export from India",
    ],
  },
  "sodium-xylene-sulfonate-90": {
    primaryKeyword: "sodium xylene sulfonate 90% manufacturer india",
    longTailKeywords: [
      "sodium xylene sulfonate 90",
      "sodium xylene sulfonate 90% supplier",
      "sodium xylene sulphonate 90%",
      "sodium xylenesulfonate 90 powder",
      "sxs 90 powder manufacturer",
      "sodium xylene sulfonate powder supplier",
      "sodium xylene sulphonate powder supplier",
      "sodium xylene sulfonate manufacturer india",
      "sodium xylene sulfonate exporter india",
      "sodium xylene sulfonate bulk supplier",
      "buy sodium xylene sulfonate 90 bulk",
      "sodium xylene sulfonate cas 1300-72-7",
      "sodium xylenesulfonate cas 1300-72-7",
      "high purity sodium xylene sulfonate",
      "sodium xylene sulfonate hydrotrope",
      "powder hydrotrope for high solid formulations",
      "hydrotrope for solvent free systems",
      "hydrotrope for heavy duty detergents",
      "sodium xylene sulfonate solubilizer",
      "sodium xylene sulfonate coupling agent",
      "sodium xylene sulfonate processing aid",
      "sodium xylene sulfonate viscosity reducing agent",
      "sodium xylene sulfonate cloud point depressant",
      "sodium xylene sulfonate surfactant",
      "xylene sulfonic acid sodium salt",
      "dimethylbenzenesulfonic acid sodium salt",
      "sodium xylene sulfonate detergent formulations",
      "sodium xylene sulfonate industrial cleaners",
      "sodium xylene sulfonate household cleaners",
      "sodium xylene sulfonate personal care formulations",
      "sodium xylene sulfonate textile auxiliaries",
      "sodium xylene sulfonate degreasing compounds",
      "sodium xylene sulfonate dishwashing detergents",
      "sodium xylene sulfonate liquid soaps",
      "sodium xylene sulfonate hand wash formulations",
      "sodium xylene sulfonate shampoo additive",
      "sodium xylene sulfonate powder detergents",
      "sodium xylene sulfonate printing paste additive",
      "sodium xylene sulfonate leather industry additive",
      "sodium xylene sulfonate paper industry additive",
      "sodium xylene sulfonate agrochemical formulations",
    ],
  },
  "sodium-xylene-sulfonate-40": {
    primaryKeyword: "sodium xylene sulfonate 40% manufacturer india",
    longTailKeywords: [
      "sodium xylene sulfonate 40%",
      "sodium xylene sulphonate 40%",
      "sodium xylene sulfonate 40 solution",
      "sodium xylene sulfonate 40 liquid",
      "sodium xylene sulphonate liquid 40%",
      "sxs 40",
      "sxs 40%",
      "sodium xylene sulfonate 40% supplier",
      "sodium xylene sulfonate manufacturer india",
      "sodium xylene sulfonate exporter india",
      "sodium xylene sulfonate bulk supplier",
      "buy sodium xylene sulfonate 40 bulk",
      "sodium xylene sulfonate cas 1300-72-7",
      "sodium xylenesulfonate cas 1300-72-7",
      "liquid hydrotrope manufacturer",
      "sodium xylene sulfonate liquid hydrotrope manufacturer",
      "technical grade sodium xylene sulfonate",
      "clear light yellow liquid hydrotrope",
      "clear colorless liquid hydrotrope",
      "anionic surfactant hydrotrope",
      "sodium xylene sulfonate hydrotrope",
      "sodium xylene sulfonate solubilizer",
      "sodium xylene sulfonate coupling agent",
      "sodium xylene sulfonate cloud point depressant",
      "sodium xylene sulfonate viscosity reducer",
      "sodium xylene sulfonate processing aid",
      "sodium xylene sulfonate dispersant",
      "sodium xylene sulfonate emulsifier",
      "sodium xylene sulfonate cleansing agent",
      "sodium xylene sulfonate all purpose cleaning",
      "sodium xylene sulfonate heavy duty cleaning",
      "sodium xylene sulfonate industrial cleaning",
      "sodium xylene sulfonate hard surface care",
      "sodium xylene sulfonate wax strippers",
      "sodium xylene sulfonate dishwashing detergents",
      "sodium xylene sulfonate liquid detergents",
      "sodium xylene sulfonate personal care formulations",
      "sodium xylene sulfonate shampoos and conditioners",
      "sodium xylene sulfonate printing pastes",
      "sodium xylene sulfonate leather industry additive",
      "sodium xylene sulfonate dispersion auxiliaries",
      "sodium xylene sulfonate extraction auxiliaries",
      "sodium xylene sulfonate 240 kg drum",
    ],
  },
  "bis-2-chloroethyl-amine-hydrochloride": {
    primaryKeyword: "bis 2 chloroethyl amine hydrochloride supplier",
    longTailKeywords: [
      "bis 2 chloroethyl amine hydrochloride manufacturer",
      "bis 2 chloroethyl amine hydrochloride cas supplier",
      "buy bis 2 chloroethyl amine hydrochloride",
    ],
  },
  "di-ethyl-amino-ethyl-chloride-hydrochloride": {
    primaryKeyword: "di ethyl amino ethyl chloride hydrochloride manufacturer",
    longTailKeywords: [
      "di ethyl amino ethyl chloride hydrochloride supplier",
      "pharma intermediate deaec hydrochloride bulk",
      "buy di ethyl amino ethyl chloride hydrochloride",
    ],
  },
  "2-amino-5-methylthiazole": {
    primaryKeyword: "2 amino 5 methylthiazole supplier",
    longTailKeywords: [
      "2 amino 5 methylthiazole pharmaceutical intermediate",
      "2 amino 5 methylthiazole manufacturer india",
      "buy 2 amino 5 methylthiazole bulk",
    ],
  },
  "2-chloroethylamine-hydrochloride": {
    primaryKeyword: "2 chloroethylamine hydrochloride manufacturer india",
    longTailKeywords: [
      "2 chloroethylamine hydrochloride supplier",
      "2 chloroethylamine hydrochloride pharmaceutical intermediate",
      "buy 2 chloroethylamine hydrochloride bulk",
    ],
  },
};

function buildDefaultKeywords(name: string, casNumber: string): ProductKeywordConfig {
  const casSuffix = casNumber ? ` cas ${casNumber}` : "";
  return {
    primaryKeyword: `${name.toLowerCase()} manufacturer india`,
    longTailKeywords: [
      `${name.toLowerCase()} supplier${casSuffix}`.trim(),
      `buy ${name.toLowerCase()} industrial grade`,
      `${name.toLowerCase()} msds safety data sheet`,
    ],
  };
}

export function getProductSeoKeywords(slug: string, name: string, casNumber: string): ProductKeywordConfig {
  if (slug === "mea-triazine-78-h2s-scavenger") {
    return {
      primaryKeyword: MEA_TRIAZINE_PRODUCT_PAGE_KEYWORDS.primaryKeyword,
      longTailKeywords: Array.from(
        new Set(MEA_TRIAZINE_PRODUCT_PAGE_KEYWORDS.longTailKeywords)
      ),
    };
  }

  return PRODUCT_SEO_KEYWORDS[slug] || buildDefaultKeywords(name, casNumber);
}
