import { Product } from "./types";
import { isRemovedProductSlug } from "./removed-products";

/**
 * Product seed data — 12 chemical products (Vasudev Chemo Pharma catalog).
 * Used as a static fallback when the database is unavailable.
 */
const productCatalog: Product[] = [
  // ─── INDUSTRIAL CHEMICALS ───────────────────────────────────────
  {
    id: 1,
    name: "MEA Triazine 78% H2S Scavenger",
    slug: "mea-triazine-78-h2s-scavenger",
    sku: "VCP-IND-0001",
    formula: "C₆H₁₅N₃O₃",
    casNumber: "4719-04-4",
    category: "industrial",
    subcategory: "Oilfield Chemicals",
    metaTitle: "",
    metaDescription: "",
    description:
      "MEA Triazine 78% is a high-concentration hydrogen sulphide scavenger formulated for oil and gas applications. It reacts irreversibly with H₂S to form non-hazardous dithiazine by-products, ensuring efficient sweetening of crude oil and natural gas streams. Manufactured by Vasudev Chemo Pharma at our ISO 9001:2015 certified facility in Gujarat, India, this product is supplied at a guaranteed minimum active content of 78%, making it one of the most concentrated MEA Triazine solutions available in the market. It is compatible with both contact tower and direct-injection scavenging systems, and is suitable for sour gas treatment, amine unit support, and pipeline sweetening operations.",
    appearance: "Clear to pale yellow liquid",
    molecularWeight: "177.20 g/mol",
    hsCode: "29336990",
    specs: {
      "Active Content": "≥ 78%",
      "pH (1% solution)": "10.0 – 12.0",
      "Specific Gravity (25°C)": "1.10 – 1.15",
      "Colour": "Clear to pale yellow",
      "Odour": "Mild amine",
      "Solubility in Water": "Fully miscible",
      "Flash Point": "> 93°C",
      "Freezing Point": "< −5°C",
      "Viscosity (25°C)": "15 – 30 cP",
    },
    safetyClass: "Irritant",
    ghsPictograms: ["GHS07"],
    signalWord: "Warning",
    hazardStatements: [
      "H315 – Causes skin irritation",
      "H319 – Causes serious eye irritation",
      "H335 – May cause respiratory irritation",
    ],
    documents: [],
    applications: [
      "H₂S scavenging in natural gas",
      "Crude oil sweetening",
      "Amine unit support",
      "Pipeline and wellhead treatment",
      "Biogas desulphurisation",
      "Refinery sour water treatment",
    ],
    industries: [
      "Oil & Gas",
      "Petrochemicals",
      "Refineries",
      "Biogas & Renewable Energy",
      "Water Treatment",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: ["Industrial Grade", "Oilfield Grade"],
    packaging: [
      "210 L HDPE drums",
      "1000 L IBC tanks",
      "Bulk tanker loads",
      "Custom packaging on request",
    ],
    minOrderQuantity: "1 MT",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    imageUrl: "https://atjtpw4vvodv5rtp.public.blob.vercel-storage.com/MEA%20Triazine/MEA-triazine-78%25-VasudevChemoPharma1.jpeg",
    images: [
      {
        src: "https://atjtpw4vvodv5rtp.public.blob.vercel-storage.com/MEA%20Triazine/MEA-triazine-78%25-VasudevChemoPharma1.jpeg",
        alt: "MEA Triazine 78% H2S Scavenger — Vasudev Chemo Pharma",
        width: 1200,
        height: 900,
        isPrimary: true,
      },
      {
        src: "https://atjtpw4vvodv5rtp.public.blob.vercel-storage.com/MEA%20Triazine/MEA-triazine-78%25-VasudevChemoPharma2.jpeg",
        alt: "MEA Triazine 78% H2S Scavenger packaging — Vasudev Chemo Pharma",
        width: 1200,
        height: 900,
        isPrimary: false,
      },
    ],
    videos: [
      {
        src: "https://atjtpw4vvodv5rtp.public.blob.vercel-storage.com/MEA%20Triazine/MEA-triazine-78%25-VasudevChemoPharma.mp4",
        title: "MEA Triazine 78% H2S Scavenger — Product Overview",
        description: "Product demonstration video for MEA Triazine 78% H2S Scavenger by Vasudev Chemo Pharma.",
        thumbnail: "https://atjtpw4vvodv5rtp.public.blob.vercel-storage.com/MEA%20Triazine/MEA-triazine-78%25-VasudevChemoPharma1.jpeg",
        isPrimary: true,
      },
    ],
    status: "active",
    faqs: [],
  },
  {
    id: 2,
    name: "MMA Triazine 40%",
    slug: "mma-triazine-40",
    sku: "VCP-IND-0002",
    formula: "C₃H₆N₆",
    casNumber: "108-74-7",
    category: "industrial",
    subcategory: "Oilfield Chemicals",
    metaTitle: "",
    metaDescription: "",
    description:
      "MMA Triazine 40% is a methyl-substituted triazine-based H₂S scavenger designed for applications where BTEX-free alternatives are required. It is widely used in natural gas processing and crude oil stabilisation. This formulation provides effective hydrogen sulphide removal at a moderate concentration, offering excellent cost-performance balance for continuous-injection systems. Manufactured by Vasudev Chemo Pharma, MMA Triazine 40% meets the stringent requirements of major oil and gas operators and is suitable for both onshore and offshore applications. The product is non-corrosive to common oilfield metallurgy and does not contribute to foaming in gas processing equipment.",
    appearance: "Clear to pale yellow liquid",
    molecularWeight: "126.12 g/mol",
    hsCode: "29336990",
    specs: {
      "Active Content": "≥ 40%",
      "pH (1% solution)": "9.5 – 11.5",
      "Specific Gravity (25°C)": "1.05 – 1.10",
      "Colour": "Clear to pale yellow",
      "Odour": "Mild amine",
      "Solubility in Water": "Fully miscible",
      "Flash Point": "> 93°C",
      "Freezing Point": "< −10°C",
    },
    safetyClass: "Irritant",
    ghsPictograms: ["GHS07"],
    signalWord: "Warning",
    hazardStatements: [
      "H315 – Causes skin irritation",
      "H319 – Causes serious eye irritation",
    ],
    documents: [],
    applications: [
      "H₂S removal in natural gas streams",
      "Crude oil stabilisation",
      "BTEX-free scavenging operations",
      "Wellhead and pipeline treatment",
      "Gas processing plant sweetening",
    ],
    industries: [
      "Oil & Gas",
      "Petrochemicals",
      "Refineries",
      "Biogas & Renewable Energy",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: ["Industrial Grade", "Oilfield Grade"],
    packaging: [
      "210 L HDPE drums",
      "1000 L IBC tanks",
      "Bulk tanker loads",
      "Custom packaging on request",
    ],
    minOrderQuantity: "1 MT",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    imageUrl: "https://atjtpw4vvodv5rtp.public.blob.vercel-storage.com/Product_Section/MMA_Triazine_Vasudev_Chemo_Pharma.png",
    images: [
      {
        src: "https://atjtpw4vvodv5rtp.public.blob.vercel-storage.com/Product_Section/MMA_Triazine_Vasudev_Chemo_Pharma.png",
        alt: "MMA Triazine 40% product packaging by Vasudev Chemo Pharma",
        width: 1200,
        height: 900,
        isPrimary: true,
      },
    ],
    videos: [
      {
        src: "https://atjtpw4vvodv5rtp.public.blob.vercel-storage.com/MMA%20Triazine/MMA3.mp4",
        title: "MMA Triazine 40% Product Video",
        description: "Product video for MMA Triazine 40% by Vasudev Chemo Pharma.",
        thumbnail: "https://atjtpw4vvodv5rtp.public.blob.vercel-storage.com/Product_Section/MMA_Triazine_Vasudev_Chemo_Pharma.png",
        isPrimary: true,
      },
    ],
    status: "active",
    faqs: [],
  },
  {
    id: 3,
    name: "P-Toluenesulfonic Acid",
    slug: "p-toluenesulfonic-acid",
    sku: "VCP-IND-0003",
    formula: "CH₃C₆H₄SO₃H",
    casNumber: "104-15-4",
    category: "industrial",
    subcategory: "Organic Acids",
    metaTitle: "",
    metaDescription: "",
    description:
      "P-Toluenesulfonic Acid (PTSA) is a strong organic acid widely used as a catalyst in esterification, polymerization, and dehydration reactions. It is preferred over mineral acids due to its milder and more selective reactivity. Vasudev Chemo Pharma supplies PTSA in both monohydrate and anhydrous forms, manufactured under strict quality controls at our Gujarat facility. The product is a versatile acid catalyst for resin synthesis, alkyd coatings, and biodiesel transesterification. PTSA is valued for its non-oxidising nature, ease of handling, and clean reaction profiles compared to sulphuric acid or hydrochloric acid.",
    appearance: "White crystalline solid",
    molecularWeight: "172.20 g/mol",
    hsCode: "29042090",
    specs: {
      "Purity": "≥ 95.0%",
      "Melting Point": "103 – 106°C (monohydrate)",
      "Moisture": "≤ 5.0% (monohydrate)",
      "Colour (Hazen)": "≤ 50",
      "Sulphated Ash": "≤ 0.1%",
      "Iron (Fe)": "≤ 10 ppm",
      "pH (10% solution)": "1.0 – 2.0",
      "Solubility in Water": "Freely soluble",
    },
    safetyClass: "Corrosive / Irritant",
    ghsPictograms: ["GHS05", "GHS07"],
    signalWord: "Danger",
    hazardStatements: [
      "H314 – Causes severe skin burns and eye damage",
      "H335 – May cause respiratory irritation",
    ],
    documents: [],
    applications: [
      "Esterification catalyst",
      "Polymerisation catalyst",
      "Alkyd resin manufacturing",
      "Biodiesel production",
      "Pharmaceutical synthesis",
      "Dehydration reactions",
      "Crosslinking catalyst for coatings",
    ],
    industries: [
      "Paints & Coatings",
      "Resins & Polymers",
      "Pharmaceuticals",
      "Biofuels",
      "Agrochemicals",
      "Fine Chemicals",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: ["Industrial Grade", "Technical Grade", "Pharmaceutical Grade"],
    packaging: [
      "25 kg HDPE bags",
      "50 kg fibre drums",
      "500 kg jumbo bags",
      "Custom packaging on request",
    ],
    minOrderQuantity: "500 kg",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
  {
    id: 4,
    name: "Copper Sulphate",
    slug: "copper-sulphate",
    sku: "VCP-IND-0004",
    formula: "CuSO₄·5H₂O",
    casNumber: "7758-99-8",
    category: "industrial",
    subcategory: "Inorganic Salts",
    metaTitle: "",
    metaDescription: "",
    description:
      "Copper Sulphate Pentahydrate is used in agriculture as a fungicide and soil additive, in mining as a flotation reagent, and in water treatment for algae control. Also used in electroplating and the production of copper compounds. Vasudev Chemo Pharma manufactures Copper Sulphate in multiple grades — from feed-grade micronutrient supplements to high-purity electroplating grade — at our ISO 9001:2015 certified facility. The product is available as blue crystalline granules or fine powder, and is exported to over 30 countries. Copper Sulphate (CAS 7758-99-8) is an essential input across agriculture, animal husbandry, and industrial chemistry.",
    appearance: "Blue crystalline granules",
    molecularWeight: "249.69 g/mol",
    hsCode: "28332500",
    specs: {
      "Purity (as CuSO₄·5H₂O)": "≥ 98.0%",
      "Copper (Cu) Content": "≥ 25.0%",
      "Iron (Fe)": "≤ 0.05%",
      "Insoluble Matter": "≤ 0.1%",
      "pH (5% solution)": "3.5 – 4.5",
      "Moisture": "≤ 1.0%",
      "Lead (Pb)": "≤ 10 ppm",
      "Arsenic (As)": "≤ 5 ppm",
    },
    safetyClass: "Harmful / Irritant / Hazardous to aquatic environment",
    ghsPictograms: ["GHS07", "GHS09"],
    signalWord: "Warning",
    hazardStatements: [
      "H302 – Harmful if swallowed",
      "H315 – Causes skin irritation",
      "H318 – Causes serious eye damage",
      "H410 – Very toxic to aquatic life with long lasting effects",
    ],
    documents: [],
    applications: [
      "Agricultural fungicide (Bordeaux mixture)",
      "Animal feed micronutrient",
      "Electroplating & electroforming",
      "Water treatment & algae control",
      "Mining flotation reagent",
      "Wood preservative (CCA treatment)",
      "Lab reagent & analytical chemistry",
    ],
    industries: [
      "Agriculture",
      "Animal Feed",
      "Mining",
      "Water Treatment",
      "Electroplating",
      "Construction (wood treatment)",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: [
      "Industrial Grade",
      "Feed Grade",
      "Electroplating Grade",
      "Lab / Reagent Grade",
    ],
    packaging: [
      "25 kg HDPE bags",
      "50 kg HDPE bags",
      "1 MT jumbo bags",
      "Custom packaging on request",
    ],
    minOrderQuantity: "1 MT",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
  {
    id: 5,
    name: "Manganese Sulphate",
    slug: "manganese-sulphate",
    sku: "VCP-IND-0005",
    formula: "MnSO₄·H₂O",
    casNumber: "10034-96-5",
    category: "industrial",
    subcategory: "Inorganic Salts",
    metaTitle: "",
    metaDescription: "",
    description:
      "Manganese Sulphate Monohydrate is used as a micronutrient in animal feed and fertilisers, as a precursor in the production of electrolytic manganese dioxide (EMD) for batteries, and in various chemical processes. Vasudev Chemo Pharma supplies Manganese Sulphate (CAS 10034-96-5) in feed-grade and industrial-grade variants, manufactured at our Gujarat-based facility. The product provides a bioavailable source of manganese essential for plant growth and animal health, and serves as a critical raw material in the lithium-ion battery supply chain for EMD and manganese-based cathode materials.",
    appearance: "Pale pink crystalline powder",
    molecularWeight: "169.02 g/mol",
    hsCode: "28332990",
    specs: {
      "Purity (as MnSO₄·H₂O)": "≥ 98.0%",
      "Manganese (Mn) Content": "≥ 31.5%",
      "Iron (Fe)": "≤ 0.01%",
      "Heavy Metals (as Pb)": "≤ 10 ppm",
      "Insoluble Matter": "≤ 0.05%",
      "Moisture": "≤ 1.0%",
      "pH (5% solution)": "3.5 – 5.0",
      "Lead (Pb)": "≤ 5 ppm",
    },
    safetyClass: "Harmful",
    ghsPictograms: ["GHS07"],
    signalWord: "Warning",
    hazardStatements: [
      "H302 – Harmful if swallowed",
      "H315 – Causes skin irritation",
      "H319 – Causes serious eye irritation",
    ],
    documents: [],
    applications: [
      "Animal feed micronutrient",
      "Agricultural fertiliser additive",
      "Electrolytic Manganese Dioxide (EMD) production",
      "Battery cathode precursor",
      "Ceramic and dye manufacturing",
      "Water purification reagent",
    ],
    industries: [
      "Agriculture",
      "Animal Feed",
      "Batteries & Energy Storage",
      "Ceramics",
      "Chemicals Manufacturing",
      "Water Treatment",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: ["Industrial Grade", "Feed Grade", "Battery Grade"],
    packaging: [
      "25 kg HDPE bags",
      "50 kg HDPE bags",
      "1 MT jumbo bags",
      "Custom packaging on request",
    ],
    minOrderQuantity: "1 MT",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },

  // ─── SURFACTANT CHEMICALS — HYDROTROPES ────────────────────────
  {
    id: 6,
    name: "Sodium Cumene Sulfonate 40%",
    slug: "sodium-cumene-sulfonate-40",
    sku: "VCP-SFC-0001",
    formula: "C₉H₁₁NaO₃S",
    casNumber: "28348-53-0",
    category: "surfactant",
    subcategory: "Hydrotropes",
    metaTitle: "",
    metaDescription: "",
    description: "Sodium Cumene Sulfonate 40% (SCS 40%) is a high-performance liquid hydrotrope used as a coupling agent, solubiliser, and viscosity reducer in surfactant-based formulations. It enhances the aqueous solubility of sparingly soluble organic compounds — such as surfactants, fragrances, and dyes — preventing phase separation, cloudiness, and gel formation in concentrated liquid detergents, industrial cleaners, and personal care products. SCS 40% is sulfate-free and sulfone-free, making it suitable for mild and sensitive-skin formulations. Also known as sodium isopropylbenzenesulfonate or sodium 4-(propan-2-yl)benzenesulfonate, it is a versatile ingredient used across household, industrial, oilfield, and agrochemical applications. Manufactured by Vasudev Chemo Pharma at our ISO 9001:2015 certified facility in Gujarat, India, this product is exported to detergent manufacturers, personal care formulators, and specialty chemical companies worldwide.",
    appearance: "Clear to slightly hazy liquid",
    molecularWeight: "222.24 g/mol",
    hsCode: "29041090",
    specs: {
      "Active Content": "39.0 – 41.0%",
      "pH (as supplied)": "7.0 – 10.0",
      "Specific Gravity (25°C)": "1.07 – 1.12",
      "Colour": "Clear to slightly hazy",
      "Odour": "Mild aromatic",
      "Solubility in Water": "Fully miscible",
      "Sulfate Content": "< 1.0%",
      "Sulfone Content": "< 1.0%",
      "Moisture": "58 – 62%",
      "Cloud Point": "< 0°C (as supplied)",
      "Storage Temperature": "> 10°C (to prevent crystallisation)",
    },
    safetyClass: "Irritant",
    ghsPictograms: ["GHS07"],
    signalWord: "Warning",
    hazardStatements: [
      "H315 – Causes skin irritation",
      "H319 – Causes serious eye irritation",
    ],
    documents: [],
    applications: [
      "Hydrotrope and coupling agent in liquid detergents",
      "Solubiliser in concentrated all-purpose cleaners",
      "Viscosity reducer in high-surfactant formulations",
      "Cloud point depressant in industrial cleaning products",
      "Stabiliser in shampoos, body washes, and liquid soaps",
      "Dispersant in paints, coatings, and dye formulations",
      "Compatibility enhancer for anionic, nonionic, and amphoteric surfactant blends",
      "Drilling fluid additive and cementing aid in oilfield operations",
      "Wetting agent in agrochemical and pesticide formulations",
      "Metal cleaning and electroplating bath additive",
    ],
    industries: [
      "Household & Industrial Cleaning",
      "Personal Care & Cosmetics",
      "Detergent Manufacturing",
      "Oil & Gas",
      "Paints & Coatings",
      "Agrochemicals",
      "Textile Processing",
      "Metal Processing & Electroplating",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: ["Technical Grade", "Industrial Grade"],
    packaging: [
      "240 L HDPE drums",
      "1000 L IBC tanks",
      "Bulk tanker loads",
      "Custom packaging on request",
    ],
    minOrderQuantity: "1 MT",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
  {
    id: 7,
    name: "Sodium Cumene Sulfonate 90%",
    slug: "sodium-cumene-sulfonate-90",
    sku: "VCP-SFC-0002",
    formula: "C₉H₁₁NaO₃S",
    casNumber: "28348-53-0",
    category: "surfactant",
    subcategory: "Hydrotropes",
    metaTitle: "",
    metaDescription: "",
    description: "Sodium Cumene Sulfonate 90% (SCS 90%) is a concentrated powder-form hydrotrope containing approximately 90% active sodium 4-isopropylbenzenesulfonate. It is used as a coupling agent, solubiliser, and viscosity reducer in surfactant-based formulations including liquid detergents, industrial cleaners, and personal care products. The high active content makes SCS 90% cost-effective for large-volume formulators who dissolve it on-site before blending, significantly reducing freight costs compared to liquid grades. It is sulfate-free and sulfone-free, biodegradable, and compatible with anionic, nonionic, and amphoteric surfactant systems. Manufactured by Vasudev Chemo Pharma at our ISO 9001:2015 certified facility in Gujarat, India.",
    appearance: "White to off-white powder / flakes",
    molecularWeight: "222.24 g/mol",
    hsCode: "29041090",
    specs: {
      "Active Content": "≥ 90.0%",
      "pH (10% solution)": "8.0 – 11.0",
      "Colour": "White to off-white",
      "Odour": "Mild aromatic",
      "Solubility in Water": "Freely soluble",
      "Sulfate Content": "< 0.5%",
      "Sulfone Content": "< 1.0%",
      "Moisture": "≤ 5.0%",
      "Bulk Density": "0.5 – 0.7 g/mL",
    },
    safetyClass: "Irritant",
    ghsPictograms: ["GHS07"],
    signalWord: "Warning",
    hazardStatements: [
      "H315 – Causes skin irritation",
      "H319 – Causes serious eye irritation",
    ],
    documents: [],
    applications: [
      "Hydrotrope and coupling agent in liquid detergents",
      "Solubiliser in concentrated all-purpose cleaners",
      "Viscosity reducer in high-surfactant formulations",
      "Cloud point depressant in industrial cleaning products",
      "Stabiliser in shampoos, body washes, and liquid soaps",
      "Dispersant in paints, coatings, and dye formulations",
      "Compatibility enhancer for anionic, nonionic, and amphoteric surfactant blends",
      "Drilling fluid additive and cementing aid in oilfield operations",
      "Wetting agent in agrochemical and pesticide formulations",
    ],
    industries: [
      "Household & Industrial Cleaning",
      "Personal Care & Cosmetics",
      "Detergent Manufacturing",
      "Oil & Gas",
      "Paints & Coatings",
      "Agrochemicals",
      "Textile Processing",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: ["Technical Grade", "Industrial Grade"],
    packaging: [
      "25 kg HDPE-lined bags",
      "500 kg jumbo bags",
      "Custom packaging on request",
    ],
    minOrderQuantity: "1 MT",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
  {
    id: 8,
    name: "Sodium Xylene Sulfonate 90%",
    slug: "sodium-xylene-sulfonate-90",
    sku: "VCP-SFC-0003",
    formula: "C₈H₉NaO₃S",
    casNumber: "1300-72-7",
    category: "surfactant",
    subcategory: "Hydrotropes",
    metaTitle: "",
    metaDescription: "",
    description: "Sodium Xylene Sulfonate 90% (SXS 90%) is a high-active, free-flowing powder hydrotrope containing 90% active sodium xylenesulfonate (CAS 1300-72-7). It is the dry, export-efficient grade of SXS used when formulators want lower shipped water, compact storage, and flexible on-site dilution before blending. SXS 90% functions as a hydrotrope, coupling agent, solubiliser, viscosity reducer, cloud-point depressant, dispersant, and processing aid in surfactant-based systems. It is used in detergent powders, concentrated alkaline cleaners, industrial and institutional cleaning compounds, agrochemical water-dispersible granules, textile auxiliaries, paper-processing additives, and personal-care surfactant bases where clarity, electrolyte tolerance, and phase stability are important. Manufactured by Vasudev Chemo Pharma at our ISO 9001:2015 certified facility in Ankleshwar, Gujarat, India, SXS 90% is supplied with batch COA, SDS, TDS support, export documentation, and bulk packaging for domestic and international buyers.",
    appearance: "White to off-white powder",
    molecularWeight: "208.21 g/mol",
    hsCode: "29041090",
    specs: {
      "Active Content": "≥ 90.0%",
      "pH (10% solution)": "8.0 – 11.0",
      "Colour": "White to off-white",
      "Odour": "Mild",
      "Solubility in Water": "Freely soluble",
      "Sulfate Content": "< 1.0%",
      "Moisture": "≤ 5.0%",
      "Bulk Density": "0.5 – 0.7 g/mL",
      "EC Number": "215-090-9",
      "Typical Form": "Free-flowing powder",
      "Recommended Storage": "Keep sealed in a cool, dry warehouse",
    },
    safetyClass: "Irritant",
    ghsPictograms: ["GHS07"],
    signalWord: "Warning",
    hazardStatements: [
      "H315 – Causes skin irritation",
      "H319 – Causes serious eye irritation",
    ],
    documents: [],
    applications: [
      "Hydrotrope and coupling agent in liquid detergents",
      "Solubiliser in concentrated household and industrial cleaners",
      "Viscosity reducer in high-surfactant formulations",
      "Cloud point depressant in cleaning product formulations",
      "Spray-dried detergent powder processing aid",
      "Alkaline cleaner and degreaser stability additive",
      "Agrochemical water-dispersible granule and soluble-liquid formulation aid",
      "Stabiliser in shampoos, body washes, and liquid hand soaps",
      "Dispersant in textile and dye processing",
      "Paper industry pentosan and lignin extraction aid",
      "Glue and adhesive additive for leather and packaging applications",
      "Compatibility enhancer for mixed surfactant systems",
      "Wetting agent in agrochemical formulations",
    ],
    industries: [
      "Household & Industrial Cleaning",
      "Personal Care & Cosmetics",
      "Detergent Manufacturing",
      "Textile Processing",
      "Agrochemicals",
      "Paints & Coatings",
      "Paper & Leather Auxiliaries",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: ["Technical Grade", "Industrial Grade"],
    packaging: [
      "15 kg HDPE-lined bags",
      "25 kg HDPE-lined bags",
      "500 kg jumbo bags",
      "1000 kg jumbo bags",
      "Custom packaging on request",
    ],
    minOrderQuantity: "1 MT",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
  {
    id: 19,
    name: "Sodium Xylene Sulfonate 40%",
    slug: "sodium-xylene-sulfonate-40",
    sku: "VCP-SFC-0004",
    formula: "C₈H₉NaO₃S",
    casNumber: "1300-72-7",
    category: "surfactant",
    subcategory: "Hydrotropes",
    metaTitle: "",
    metaDescription: "",
    description: "Sodium Xylene Sulfonate 40% (SXS 40%) is a ready-to-use liquid hydrotrope containing approximately 40% active sodium xylenesulfonate in aqueous solution. It is used as a coupling agent, solubiliser, and viscosity reducer in surfactant-based formulations — keeping concentrated liquid detergents, all-purpose cleaners, and personal care products clear, stable, and pourable. SXS 40% blends easily into liquid formulations without pre-dissolution, making it the preferred choice for detergent and personal care manufacturers who value formulation speed and ease of handling. It is biodegradable, non-toxic at use concentrations, and compatible with anionic, nonionic, cationic, and amphoteric surfactant systems. Manufactured by Vasudev Chemo Pharma at our ISO 9001:2015 certified facility in Gujarat, India.",
    appearance: "Clear to slightly hazy liquid",
    molecularWeight: "208.21 g/mol",
    hsCode: "29041090",
    specs: {
      "Active Content": "39.0 – 41.0%",
      "pH (as supplied)": "7.0 – 10.0",
      "Specific Gravity (25°C)": "1.06 – 1.10",
      "Colour": "Clear to slightly hazy",
      "Odour": "Mild",
      "Solubility in Water": "Fully miscible",
      "Sulfate Content": "< 1.0%",
      "Moisture": "58 – 62%",
      "Cloud Point": "< 0°C (as supplied)",
      "Storage Temperature": "> 10°C (to prevent crystallisation)",
    },
    safetyClass: "Irritant",
    ghsPictograms: ["GHS07"],
    signalWord: "Warning",
    hazardStatements: [
      "H315 – Causes skin irritation",
      "H319 – Causes serious eye irritation",
    ],
    documents: [],
    applications: [
      "Hydrotrope and coupling agent in liquid detergents",
      "Solubiliser in concentrated household and industrial cleaners",
      "Viscosity reducer in high-surfactant formulations",
      "Cloud point depressant in cleaning product formulations",
      "Stabiliser in shampoos, body washes, and liquid hand soaps",
      "Dispersant in textile and dye processing",
      "Compatibility enhancer for mixed surfactant systems",
      "Wetting agent in agrochemical formulations",
      "Metal cleaning and degreasing formulations",
    ],
    industries: [
      "Household & Industrial Cleaning",
      "Personal Care & Cosmetics",
      "Detergent Manufacturing",
      "Textile Processing",
      "Agrochemicals",
      "Paints & Coatings",
      "Metal Processing",
    ],
    price: 0,
    priceUnit: "/MT",
    currency: "USD",
    unitOfMeasure: "MT",
    grades: ["Technical Grade", "Industrial Grade"],
    packaging: [
      "240 L HDPE drums",
      "1000 L IBC tanks",
      "Bulk tanker loads",
      "Custom packaging on request",
    ],
    minOrderQuantity: "1 MT",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },

  // ─── SPECIALTY CHEMICALS ────────────────────────────────────────
  {
    id: 9,
    name: "Bis(2-chloroethyl)amine Hydrochloride",
    slug: "bis-2-chloroethyl-amine-hydrochloride",
    sku: "VCP-SPC-0001",
    formula: "C₄H₉Cl₂N·HCl",
    casNumber: "821-48-7",
    category: "specialty",
    subcategory: "Organic Intermediates",
    metaTitle: "",
    metaDescription: "",
    description:
      "Bis(2-chloroethyl)amine Hydrochloride is a specialty organic intermediate used in pharmaceutical synthesis and the production of nitrogen mustard derivatives for research and industrial applications. Supplied by Vasudev Chemo Pharma, this compound (CAS 821-48-7) is manufactured under controlled conditions with strict purity assurance. It serves as a key building block for the synthesis of anti-cancer alkylating agents, cross-linking reagents, and nitrogen heterocycles. This substance is listed under the Chemical Weapons Convention (CWC) Schedule 2 and may be subject to national export-control regulations (e.g. ECCN, REACH Annex XIV). The product is handled and shipped in compliance with applicable dangerous goods and export-control regulations. All sales and shipments require prior end-user vetting and appropriate licensing documentation.",
    appearance: "White to off-white crystalline solid",
    molecularWeight: "178.49 g/mol",
    hsCode: "29211990",
    specs: {
      "Purity (by HPLC)": "≥ 98.0%",
      "Melting Point": "210 – 215°C (decomp.)",
      "Moisture": "≤ 0.5%",
      "Residue on Ignition": "≤ 0.1%",
      "Chloride Content": "Within spec",
      "Appearance": "White to off-white crystalline solid",
    },
    safetyClass: "Toxic / Harmful",
    ghsPictograms: ["GHS06", "GHS08"],
    signalWord: "Danger",
    hazardStatements: [
      "H301 – Toxic if swallowed",
      "H311 – Toxic in contact with skin",
      "H331 – Toxic if inhaled",
      "H350 – May cause cancer",
    ],
    complianceDisclaimer:
      "This substance is listed under the Chemical Weapons Convention (CWC) Schedule 2 and may be subject to national export-control regulations including ECCN classification, REACH Annex XIV authorisation, and other chemical-control frameworks. Sale, purchase, and shipment of this product require prior end-user vetting, valid import/export licences, and appropriate regulatory documentation. Vasudev Chemo Pharma will not process orders without completed compliance verification.",
    documents: [],
    applications: [
      "Anti-cancer drug intermediate (nitrogen mustard derivatives)",
      "Cross-linking reagent for bioconjugation",
      "Synthesis of nitrogen heterocycles",
      "Pharmaceutical R&D and process chemistry",
    ],
    industries: [
      "Pharmaceuticals",
      "Oncology Research",
      "Fine Chemicals",
      "Biotechnology",
    ],
    price: 0,
    priceUnit: "/kg",
    currency: "USD",
    unitOfMeasure: "kg",
    grades: ["Synthesis Grade (≥ 98%)", "Research Grade"],
    packaging: [
      "1 kg HDPE containers",
      "5 kg HDPE drums",
      "25 kg fibre drums",
      "Custom packaging on request",
    ],
    minOrderQuantity: "1 kg",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
  {
    id: 10,
    name: "Di Ethyl Amino Ethyl Chloride Hydrochloride",
    slug: "di-ethyl-amino-ethyl-chloride-hydrochloride",
    sku: "VCP-SPC-0002",
    formula: "C₆H₁₄ClN·HCl",
    casNumber: "869-24-9",
    category: "specialty",
    subcategory: "Organic Intermediates",
    metaTitle: "",
    metaDescription: "",
    description:
      "DEAE-Cl HCl (Diethylaminoethyl Chloride Hydrochloride) is a key pharmaceutical intermediate used in the synthesis of various active pharmaceutical ingredients including antihistamines and local anaesthetics. Vasudev Chemo Pharma supplies this compound (CAS 869-24-9) in high purity for GMP and non-GMP applications. It is used as an alkylating agent to introduce the diethylaminoethyl side chain into drug molecules — a structural motif found in Chloroquine, Procaine, and several other pharmaceuticals. The product is manufactured under rigorous process controls at our specialty synthesis unit in Gujarat, India.",
    appearance: "White crystalline powder",
    molecularWeight: "172.10 g/mol",
    hsCode: "29211990",
    specs: {
      "Purity (by GC)": "≥ 99.0%",
      "Melting Point": "210 – 215°C",
      "Moisture": "≤ 0.5%",
      "Residue on Ignition": "≤ 0.1%",
      "pH (5% solution)": "3.0 – 5.0",
      "Heavy Metals (as Pb)": "≤ 10 ppm",
    },
    safetyClass: "Corrosive / Toxic",
    ghsPictograms: ["GHS05", "GHS06"],
    signalWord: "Danger",
    hazardStatements: [
      "H301 – Toxic if swallowed",
      "H311 – Toxic in contact with skin",
      "H314 – Causes severe skin burns and eye damage",
    ],
    documents: [],
    applications: [
      "Intermediate for Chloroquine and Hydroxychloroquine",
      "Synthesis of local anaesthetics (Procaine family)",
      "Antihistamine API manufacturing",
      "Alkylating agent in organic synthesis",
      "Ion-exchange resin functionalisation",
    ],
    industries: [
      "Pharmaceuticals",
      "API Manufacturing",
      "Fine Chemicals",
      "Polymer Chemistry",
    ],
    price: 0,
    priceUnit: "/kg",
    currency: "USD",
    unitOfMeasure: "kg",
    grades: ["Pharmaceutical Grade (≥ 99%)", "Technical Grade (≥ 98%)"],
    packaging: [
      "1 kg HDPE containers",
      "5 kg HDPE drums",
      "25 kg fibre drums",
      "Custom packaging on request",
    ],
    minOrderQuantity: "5 kg",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
  {
    id: 11,
    name: "2-Amino-5-methylthiazole",
    slug: "2-amino-5-methylthiazole",
    sku: "VCP-SPC-0003",
    formula: "C₄H₆N₂S",
    casNumber: "7305-71-7",
    category: "specialty",
    subcategory: "Heterocyclic Compounds",
    metaTitle: "",
    metaDescription: "",
    description:
      "2-Amino-5-methylthiazole is a heterocyclic building block used in the synthesis of pharmaceuticals, agrochemicals, and dyes. It is a key intermediate in the manufacture of several drug molecules. Supplied by Vasudev Chemo Pharma (CAS 7305-71-7), this thiazole derivative is manufactured in high purity for pharmaceutical and research applications. The compound serves as a starting material for the synthesis of Famotidine (H₂-receptor antagonist), Nizatidine, and various sulfonamide antibiotics. It is also used as a corrosion inhibitor in industrial applications and as a building block in materials science.",
    appearance: "Pale yellow crystalline solid",
    molecularWeight: "114.17 g/mol",
    hsCode: "29341090",
    specs: {
      "Purity (by HPLC)": "≥ 98.0%",
      "Melting Point": "93 – 97°C",
      "Moisture": "≤ 0.5%",
      "Residue on Ignition": "≤ 0.1%",
      "Appearance": "Pale yellow crystalline solid",
      "Solubility": "Soluble in ethanol, sparingly soluble in water",
    },
    safetyClass: "Irritant",
    ghsPictograms: ["GHS07"],
    signalWord: "Warning",
    hazardStatements: [
      "H302 – Harmful if swallowed",
      "H315 – Causes skin irritation",
      "H319 – Causes serious eye irritation",
    ],
    documents: [],
    applications: [
      "Famotidine API intermediate",
      "Nizatidine & ranitidine synthesis",
      "Agrochemical intermediate",
      "Dye and pigment synthesis",
      "Corrosion inhibitor",
      "Heterocyclic building block for research",
    ],
    industries: [
      "Pharmaceuticals",
      "Agrochemicals",
      "Dyes & Pigments",
      "Fine Chemicals",
      "Research & Development",
    ],
    price: 0,
    priceUnit: "/kg",
    currency: "USD",
    unitOfMeasure: "kg",
    grades: ["Pharmaceutical Grade (≥ 98%)", "Technical Grade (≥ 97%)"],
    packaging: [
      "1 kg HDPE containers",
      "5 kg HDPE drums",
      "25 kg fibre drums",
      "Custom packaging on request",
    ],
    minOrderQuantity: "5 kg",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
  {
    id: 12,
    name: "2-Chloroethylamine Hydrochloride",
    slug: "2-chloroethylamine-hydrochloride",
    sku: "VCP-SPC-0004",
    formula: "ClCH₂CH₂NH₂·HCl",
    casNumber: "870-24-6",
    category: "specialty",
    subcategory: "Organic Intermediates",
    metaTitle: "",
    metaDescription: "",
    description:
      "2-Chloroethylamine Hydrochloride is a versatile organic intermediate used in the synthesis of pharmaceuticals, agrochemicals, and specialty polymers. It is a key building block for ethyleneimine derivatives. Vasudev Chemo Pharma supplies this compound (CAS 870-24-6) in high purity for use in the production of aziridine-based crosslinkers, surfactants, and pharmaceutical intermediates. The product is manufactured at our specialty chemicals unit under controlled conditions and is available in research and bulk quantities for industrial-scale synthesis.",
    appearance: "White crystalline powder",
    molecularWeight: "116.01 g/mol",
    hsCode: "29211990",
    specs: {
      "Purity (by GC)": "≥ 99.0%",
      "Melting Point": "143 – 146°C",
      "Moisture": "≤ 0.5%",
      "Residue on Ignition": "≤ 0.1%",
      "pH (5% solution)": "2.0 – 4.0",
      "Appearance": "White crystalline powder",
    },
    safetyClass: "Corrosive / Toxic",
    ghsPictograms: ["GHS05", "GHS06"],
    signalWord: "Danger",
    hazardStatements: [
      "H301 – Toxic if swallowed",
      "H311 – Toxic in contact with skin",
      "H314 – Causes severe skin burns and eye damage",
      "H331 – Toxic if inhaled",
    ],
    documents: [],
    applications: [
      "Ethyleneimine (aziridine) synthesis",
      "Pharmaceutical intermediate",
      "Agrochemical intermediate",
      "Cross-linking agent for coatings & resins",
      "Surfactant synthesis",
      "Specialty polymer building block",
    ],
    industries: [
      "Pharmaceuticals",
      "Agrochemicals",
      "Polymers & Resins",
      "Fine Chemicals",
      "Coatings",
    ],
    price: 0,
    priceUnit: "/kg",
    currency: "USD",
    unitOfMeasure: "kg",
    grades: ["Pharmaceutical Grade (≥ 99%)", "Technical Grade (≥ 98%)"],
    packaging: [
      "1 kg HDPE containers",
      "5 kg HDPE drums",
      "25 kg fibre drums",
      "Custom packaging on request",
    ],
    minOrderQuantity: "5 kg",
    originCountry: "India",
    certifications: ["ISO 9001:2015"],
    supplier: "Vasudev Chemo Pharma",
    images: [],
    status: "active",
    faqs: [],
  },
];

export const products: Product[] = productCatalog.filter(
  (product) => !isRemovedProductSlug(product.slug)
);

/** Find a product by slug */
export function getProductBySlug(slug: string): Product | undefined {
  if (isRemovedProductSlug(slug)) return undefined;
  return products.find((p) => p.slug === slug);
}

/** Get all active product slugs for static generation */
export function getAllProductSlugs(): string[] {
  return products.filter((p) => p.status === "active").map((p) => p.slug);
}

/** Get related products (same category, excluding current) */
export function getRelatedProducts(
  currentSlug: string,
  category: string,
  limit = 3
): Product[] {
  return products
    .filter((p) => p.category === category && p.slug !== currentSlug && p.status === "active")
    .slice(0, limit);
}
