/**
 * Slug-specific Product schema enrichment for MEA Triazine 78% H2S Scavenger.
 * This data is merged into the base ProductSchema when rendering the
 * `/product/mea-triazine-78-h2s-scavenger` page.
 */

export const MEA_TRIAZINE_SLUG = "mea-triazine-78-h2s-scavenger";

export const MEA_TRIAZINE_MARKET_LANGUAGE_CODES = [
  "en",
  "en-IN",
  "en-US",
  "en-GB",
  "en-AE",
  "ar-AE",
  "ar-OM",
  "ar-EG",
  "pt-BR",
  "ar-SA",
  "ar-IQ",
  "vi-VN",
  "zh-CN",
  "es-ES",
  "it-IT",
  "de-DE",
  "pl-PL",
  "x-default",
] as const;

export const MEA_TRIAZINE_OG_LOCALES = [
  "en_US",
  "en_GB",
  "en_AE",
  "ar_AE",
  "ar_OM",
  "ar_EG",
  "pt_BR",
  "ar_SA",
  "ar_IQ",
  "en_IN",
  "vi_VN",
  "zh_CN",
  "es_ES",
  "it_IT",
  "de_DE",
  "pl_PL",
] as const;

const MEA_TRIAZINE_TARGET_MARKETS = [
  "India",
  "United States",
  "United Arab Emirates",
  "Saudi Arabia",
  "United Kingdom",
  "Canada",
  "Australia",
  "China",
  "Spain",
  "Italy",
  "Germany",
  "Poland",
  "Switzerland",
  "Vietnam",
  "Oman",
  "Qatar",
  "Kuwait",
] as const;

export const MEA_TRIAZINE_METADATA = {
  // Title: lead with bare "MEA Triazine" query, include synonym for the
  // "monoethanolamine triazine" long-tail, keep commercial qualifier.
  // Kept at 52 chars to avoid desktop SERP truncation (~60 char limit).
  title: "MEA Triazine – 78% H2S Scavenger (Monoethanolamine)",
  description:
    "MEA Triazine 78% (Monoethanolamine Triazine, CAS 4719-04-4) — industrial H2S scavenger for oil, gas & biogas. ISO 9001 Indian manufacturer. Request a quote.",
  openGraphDescription:
    "MEA Triazine 78% (Monoethanolamine Triazine) — H2S scavenger for oil, gas, biogas & wastewater. ISO 9001 India manufacturer, drum/IBC/bulk export supply.",
  twitterDescription:
    "MEA Triazine 78% (Monoethanolamine Triazine, CAS 4719-04-4) — H2S scavenger from ISO 9001 India manufacturer. Drum, IBC & bulk export supply.",
} as const;

export const MEA_TRIAZINE_SCHEMA_ENRICHMENT = {
  description:
    "MEA Triazine 78% H2S Scavenger (CAS 4719-04-4) is a high-concentration monoethanolamine triazine solution used for removing hydrogen sulfide from natural gas, crude oil, wastewater, and biogas streams. Manufactured by Vasudev Chemo Pharma in Gujarat, India for industrial and export supply.",
  alternateName: [
    /* ── IUPAC / Chemical Synonyms ────────────────────────── */
    "Monoethanolamine Triazine 78%",
    "Hexahydro-1,3,5-tris(2-hydroxyethyl)-s-triazine",
    "Hexahydro-1,3,5-tris(2-hydroxyethyl)-s-triazine 78%",
    "1,3,5-Triazine-1,3,5(2H,4H,6H)-triethanol",
    "1,3,5-Triazine",
    "Triazinetriethanol",
    "Tris(N-hydroxyethyl) hexahydrotriazine",
    "Hexahydro-1,3,5-tris(hydroxyethyl)-s-triazine",
    "2,2',2''-(1,3,5-triazinane-1,3,5-triyl)triethanol",
    "2,2',2\"-(hexahydro-1,3,5-triazine-1,3,5-triyl)triethanol",
    "2,2\u2032,2\u2032\u2032-(hexahydro-1,3,5-triazine-1,3,5-triyl)triethanol (HHT)",
    "2,2',2''-(Hexahydro-1,3,5-triazine-1,3,5-triyl) Triethanol",
    "1,3,5-Tris(2-hydroxyethyl) hexahydro-triazine",
    "1,3,5-Tris(2-hydroxyethyl)hexahydro-1,3,5-triazine",
    "s-Triazine-1,3,5-triethanol",
    "J2.219E",
    /* ── Generic / Search Names ───────────────────────────── */
    "Triazine H2S Scavenger",
    "MEA Based Triazine",
    "MEA Triazine",
    "MEA Triazine 78",
    "MEA-triazine Blend",
    "Triazine 78%",
    "78% MEA Triazine",
    "MEA Triazine 78% H2S Scavenger",
    "Triazine Based H2S Scavenging Chemical",
    "Hexahydrotriazine H2S Scavenger",
    "Hydrogen Sulfide Scavenger",
    "Triazine Scavenger",
    "High Purity Triazine",
    /* ── Application-Based Synonyms ───────────────────────── */
    "H2S Scavenger",
    "Desulfurizer",
    "Gas Sweetener",
    "Gas Sweetening Agent",
    "Mercaptan Scavenger",
    "Offshore H2S Scavenger",
    "Onshore H2S Scavenger",
    "Formaldehyde-Releasing Biocide",
    "Industrial Microbiocide",
    "Microbiostat",
    "Slimicide",
    "Bactericide",
    "Algicide",
    "Cutting Fluid Preservative",
    "Anti-mildew Agent",
    "H2S Scavenger (Triazine based)",
    "Oil Drilling Fluid",
    /* ── Competitor / Trade Names ─────────────────────────── */
    "Grotan HD",
    "Grotan BK",
    "Grotan B",
    "Grotanol",
    "Acticide GR",
    "Acticide HHB",
    "Nipacide BK",
    "Bioban GK",
    "Onyxide 200",
    "Onyxide 200-50",
    "Busan 1060",
    "Busan 1506",
    "Protectol HT",
    "Basolon SC 78",
    "G-SCAV EA77",
    "Mergal KM200",
    "Mergal 174II",
    "Mergal 165",
    "Troyshield B2",
    "Triadine 3",
    "Triadine 10",
    "Triadine 174",
    "Kalpur TE",
    "H2Stopper 1908C",
    "JadeScan54",
    "BK Biocide",
    "SP-BIO-TZ",
    "Sine PF77",
    "Ottaform 204",
    "Roksol T",
    "Cobate C",
    "Bactraclean",
    "Actane",
    "ETA 75",
    "KM 200",
    "Amebact C",
    "Dodigen NJ",
    "Bestcide 1087T",
    "Permachem OB 2",
    "Surcide D",
    "Surcide P",
    "Silworld",
    "Silworld Triazine 78",
    "Nuosept 78",
    "Parmetol",
    "GreatAp HHT",
    "Triazine BK",
    "IR-Triazine",
    "Water Treatment Biocide BK",
    "Miliden X-2",
    "Scavtreat",
    "Syntan OXB",
    /* ── Vietnamese-language names ───────────────────────── */
    "Chất hấp thụ H2S Triazine",
    "Hóa chất khử hydro sulfide MEA Triazine",
    "Hóa chất xử lý khí chua Triazine",
    "Chất khử lưu huỳnh MEA Triazine",
    /* ── Vietnam-market brand names ──────────────────────── */
    "Dayong MEA Triazine",
    "IRO MEA Triazine",
    "H2S Scavenger Conc",
    "JDC H2S Scavenger",
    /* ── USA-market brand names ──────────────────────────── */
    "Pro3",
    "Pro3 HT",
    "Pro3 GT",
    "Pro3 NGL",
    "Pro3 Nano",
    "ProM",
    "Enviro-Scrub",
    "Enviro-Scrub Bio",
    "PureMark M500",
    "PureMark B800",
    "HSCAV-80",
    "Kontin",
    "HS-1526-40",
    "Sulfa-Check",
    /* ── UAE/GCC-market brand names ──────────────────────── */
    "RXSOL-43-8160-210",
    "RXSOL Triazine Based Biocide",
    "STEPANQUAT 200",
    "JadeScan54",
    "JadeScan56",
    "SP-BIO-TZ",
    "SINE PF77",
    /* ── Oman-market brand names ────────────────────────── */
    "RXSOL H2S Scavenger (RXSOL-11-5014-210)",
    "MC MX 2-1106",
    "SULFA-CLEAR 8411HC",
    "SULFA-CLEAR 8411C",
    "OS TRI-SCAV",
    "MBBT H2S Scavenger",
    "OOISS Triazine",
    "ICPL Triazine H2S Scavenger",
    /* ── Arabic-language names ───────────────────────────── */
    "مزيل كبريتيد الهيدروجين (H2S Scavenger)",
    "كاسح H2S (H2S Scavenger)",
    "مادة إزالة كبريتيد الهيدروجين (H2S Removal Substance)",
    "معالجة الغاز الحامض (Sour Gas Treatment)",
    "كيماويات حقول النفط (Oilfield Chemicals)",
    /* ── Oman Arabic-language names ─────────────────────── */
    "كاسح كبريتيد الهيدروجين عُمان (H2S Scavenger Oman)",
    "مورد مواد كيميائية لإزالة H2S في عمان (H2S Chemical Supplier Oman)",
    "معالجة الغاز الحامض عُمان (Sour Gas Treatment Oman)",
    "مواد كيميائية لحقول النفط عُمان (Oilfield Chemicals Oman)",
    "ترايازين لإزالة كبريتيد الهيدروجين (Triazine for H2S Removal)",
    /* ── Egypt-market brand names ───────────────────────── */
    "ACPA H2S Scavenger",
    "AquaNile H2S Scavenger",
    "MPC H2S Scavenger (Alamia Oil Services)",
    "Scomi Egypt",
    "ICG MEA Triazine",
    "Filtron H2S Scavenger",
    "CACIDE 301",
    "SDM CIDE",
    /* ── Egypt Arabic-language names ────────────────────── */
    "مادة كاسحة لكبريتيد الهيدروجين مصر (H2S Scavenger Egypt)",
    "مورد كيماويات حقول النفط مصر (Oilfield Chemical Supplier Egypt)",
    "معالجة الغاز الحامض مصر (Sour Gas Treatment Egypt)",
    "كاسح كبريتيد الهيدروجين مصر (H2S Scavenger Egypt)",
    "مورد ترايازين مصر (Triazine Supplier Egypt)",
    /* ── Brazil-market brand names ──────────────────────── */
    "Global Trend MEA-Triazina 78%",
    "SCAVTREAT 1063 (Clariant)",
    "ABATE S-200 Scavenger (Dow)",
    "Brenntag MEA / Triazine",
    "BerrySweet 80% (Berryman Chemical)",
    "ICS-5780 (International Chemical Group)",
    "SLB Triazine H2S Scavenger",
    "Nalco/Ecolab H2S Scavenger",
    "Foscote MEA",
    /* ── Portuguese-language names ─────────────────────── */
    "removedor de H2S triazina MEA (H2S Remover MEA Triazine)",
    "captador de sulfeto de hidrogênio (Hydrogen Sulfide Scavenger)",
    "triazina MEA 78% (MEA Triazine 78%)",
    "sequestrante de H2S triazina (H2S Sequestrant Triazine)",
    "tratamento de gás ácido triazina (Sour Gas Treatment Triazine)",
    /* ── Saudi Arabia brand names ──────────────────────── */
    "Chemara HS-1501 (Saudi Multichem)",
    "G-SCAV Triazine 78% (Jubail)",
    "SUGEST H2S Scavenger",
    "CHEMAOIL Triazine",
    "NassGuard MEA",
    "REPC Triazine",
    "UCC Triazine (United Chemical Company)",
    "Alkemist KSA MEA",
    "Cola Triazine 50 ME (Colonial Chemical)",
    "HME-FILM MEA Triazine (MED Drilling Fluids)",
    "DubiChem Triazine Biocide",
    /* ── Saudi Arabic-language names ───────────────────── */
    "مزيل كبريتيد الهيدروجين ترايازين السعودية (H2S Remover Triazine Saudi Arabia)",
    "كاسح H2S ترايازين المملكة العربية السعودية (H2S Scavenger Triazine KSA)",
    "مورد كيماويات حقول النفط السعودية (Oilfield Chemical Supplier KSA)",
    "مادة معالجة الغاز الحامض ترايازين (Sour Gas Treatment Triazine)",
    "كاسح كبريتيد الهيدروجين أرامكو (H2S Scavenger Aramco)",
    /* ── Iraq brand names ────────────────────────────── */
    "Tawreed H2S Scavenger (Baghdad)",
    "ALDUHA H2S Scavenger (Basra)",
    "SAHARA MEA Triazine (North Rumaila)",
    "Federal Group / Advanced Chemicals (Erbil)",
    "Sama Alyarmouk Chemicals (Baghdad)",
    "Manar Al-Basra Oilfield Services",
    "Petrobon MEA (Iran/Iraq)",
    "Ishtar MEA (Iran/Iraq)",
    "ATDMCO MEA (UAE/Turkey)",
    "TAQA Group Chemicals",
    "Falizan HS-9003 (Iran)",
    /* ── Iraqi Arabic-language names ───────────────────── */
    "كاسح كبريتيد الهيدروجين العراق (H2S Scavenger Iraq)",
    "مورد كيماويات حقول النفط العراق (Oilfield Chemical Supplier Iraq)",
    "مورد ترايازين البصرة (Triazine Supplier Basra)",
    "كاسح H2S حقل الرميلة (H2S Scavenger Rumaila Field)",
    "معالجة الغاز الحامض العراق (Sour Gas Treatment Iraq)",
    /* ── Qatar-market brand names ────────────────────────── */
    "BKC Gulf Triazine Scavenger",
    "Deluxe MEA (Qatar)",
    "Chemway MEA Triazine",
    "ChampionX H2S Scavenger (QatarEnergy)",
    "Baker Hughes H2S Scavenger (QatarEnergy)",
    "Halliburton Triazine (Qatar)",
    "HS-1526-40 Triazine (Univar)",
    "K2P MEA-T Scavenger",
    /* ── Qatar Arabic-language names ───────────────────── */
    "كاسح كبريتيد الهيدروجين قطر (H2S Scavenger Qatar)",
    "مورد ترايازين قطر (Triazine Supplier Qatar)",
    "مورد مواد كيميائية لمعالجة الغاز قطر (Gas Treatment Chemical Supplier Qatar)",
    "معالجة الغاز الحامض قطر (Sour Gas Treatment Qatar)",
    "كيماويات حقول النفط قطر (Oilfield Chemicals Qatar)",
    "كاسح H2S حقل الشمال (H2S Scavenger North Field)",
    /* ── Kuwait-market brand names ────────────────────────── */
    "Bait Al Aseel H2S Scavenger (Kuwait)",
    "DK Petrochemicals MEA (Kuwait)",
    "HME-FILM MEA Triazine (MED Drilling, GCC)",
    "Triasorb (Sintez-Oka, Russia)",
    "Xipeng MEA Triazine 78% (China)",
    "Sarex HPT Triazine (India)",
    "Dorf Ketal H2S Scavenger (Kuwait KOC)",
    /* ── Kuwait Arabic-language names ─────────────────────── */
    "كاسح كبريتيد الهيدروجين الكويت (H2S Scavenger Kuwait)",
    "مورد ترايازين الكويت (Triazine Supplier Kuwait)",
    "مادة إزالة H2S لحقول نفط الكويت (H2S Removal Kuwait Oilfields)",
    "معالجة الغاز الحامض الكويت (Sour Gas Treatment Kuwait)",
    "كيماويات حقول النفط الكويت (Oilfield Chemicals Kuwait)",
    /* ── Thailand-market brand names ─────────────────────── */
    "Brenntag MEA (Thailand)",
    "PTT GC MEA (Thailand)",
    "Krungthep Trading MEA (Thailand)",
    "Borregaard H2S Scavenger (Norway)",
    "ECHEMI MEA Triazine 78% (China)",
    "Chemipan MEA (Thailand retail)",
    /* ── Thai-language names ───────────────────────────── */
    "สารกำจัด H2S ไตรอะซีน (H2S Scavenger Triazine)",
    "สารดักจับไฮโดรเจนซัลไฟด์ (Hydrogen Sulfide Scavenger)",
    "สารบำบัดก๊าซเปรี้ยว (Sour Gas Treatment Agent)",
    "เคมีภัณฑ์สำหรับอุตสาหกรรมน้ำมันและแก๊ส (Oil & Gas Industry Chemicals)",
    "สารเคมีขจัดไฮโดรเจนซัลไฟด์ก๊าซชีวภาพ (Biogas H2S Removal)",
    /* ── Iran-market brand names ────────────────────────── */
    "Tsorb3400 (Tasfyeh Group, Iran)",
    "Tasfyeh MEA Triazine 80% (Iran)",
    "Chemical Iran MEA (Tehran)",
    "IranChemicalMine MEA (Iran)",
    "Triasorb (Sintez-Oka, Russia — Iran supply)",
    "Sarex HPT Triazine (India export)",
    /* ── Farsi (Persian) names ────────────────────────── */
    "حذف‌کننده H2S تری‌آزین (H2S Scavenger Triazine)",
    "حذف‌کننده سولفید هیدروژن ایران (H2S Scavenger Iran)",
    "تری‌آزین تأمین‌کننده ایران (Triazine Supplier Iran)",
    "تصفیه گاز ترش ایران (Sour Gas Treatment Iran)",
    "مواد شیمیایی صنعتی میدان پارس جنوبی (South Pars Industrial Chemicals)",
  ],
  mpn: "MEA-T78",
  material: "Monoethanolamine Triazine",
  category: "H2S Scavengers / Oilfield Chemicals",
  countryOfOrigin: "India",
  audience: {
    "@type": "BusinessAudience" as const,
    audienceType:
      "Oil and gas operators, refineries, wastewater treatment contractors, and industrial procurement teams",
  },
  areaServed: MEA_TRIAZINE_TARGET_MARKETS.map((name) => ({
    "@type": "Country" as const,
    name,
  })),
  additionalProperty: [
    { "@type": "PropertyValue" as const, name: "CAS Number", value: "4719-04-4" },
    { "@type": "PropertyValue" as const, name: "Active Concentration", value: "78% (w/w)" },
    { "@type": "PropertyValue" as const, name: "Appearance", value: "Clear to light yellow liquid" },
    { "@type": "PropertyValue" as const, name: "pH", value: "9.5-11.0" },
    { "@type": "PropertyValue" as const, name: "Shelf Life", value: "12 months" },
    { "@type": "PropertyValue" as const, name: "Flash Point", value: ">93 °C (>200 °F)" },
    { "@type": "PropertyValue" as const, name: "Density", value: "~1.10 g/mL at 20 °C" },
    { "@type": "PropertyValue" as const, name: "Solubility", value: "Fully miscible with water" },
  ],
} as const;

export const MEA_TRIAZINE_COMPARISON = [
  {
    feature: "Active concentration",
    meaTriazine78: "78%",
    mmaTriazine: "20-80%",
    glyoxalBased: "40-80%",
  },
  {
    feature: "Water solubility",
    meaTriazine78: "High",
    mmaTriazine: "High",
    glyoxalBased: "Moderate",
  },
  {
    feature: "Reaction speed",
    meaTriazine78: "Fast",
    mmaTriazine: "Fast",
    glyoxalBased: "Moderate",
  },
  {
    feature: "Solids formation risk",
    meaTriazine78: "Low-Medium",
    mmaTriazine: "Low",
    glyoxalBased: "Low",
  },
  {
    feature: "Suitable for offshore",
    meaTriazine78: "Yes",
    mmaTriazine: "Yes",
    glyoxalBased: "Conditional",
  },
  {
    feature: "Regenerable",
    meaTriazine78: "No",
    mmaTriazine: "No",
    glyoxalBased: "No",
  },
] as const;

/**
 * Real user search keywords mapped to their origin country.
 * Use for geo-targeted SEO, FAQ schema, and landing-page generation.
 */
export const MEA_TRIAZINE_SEARCH_KEYWORDS = [
  /* ── USA ────────────────────────────────────────────────── */
  { keyword: "Triazine Scavenger", country: "United States" },
  { keyword: "MEA Triazine", country: "United States" },
  { keyword: "MEA-triazine Blends", country: "United States" },
  { keyword: "Bioban GK", country: "United States" },
  { keyword: "Onyxide 200", country: "United States" },
  { keyword: "Onyxide 200-50", country: "United States" },
  { keyword: "Busan 1060", country: "United States" },
  { keyword: "Busan 1506", country: "United States" },
  { keyword: "Nuosept 78", country: "United States" },
  { keyword: "Mergal KM200", country: "United States" },
  { keyword: "Troyshield B2", country: "United States" },
  { keyword: "Triadine 3", country: "United States" },
  { keyword: "Triadine 10", country: "United States" },
  { keyword: "Triadine 174", country: "United States" },
  { keyword: "H2Stopper 1908C", country: "United States" },
  { keyword: "Cobate C", country: "United States" },
  { keyword: "Actane", country: "United States" },
  { keyword: "Bestcide 1087T", country: "United States" },
  { keyword: "Surcide D", country: "United States" },
  { keyword: "Surcide P", country: "United States" },
  { keyword: "Permachem OB 2", country: "United States" },
  { keyword: "ETA 75", country: "United States" },
  { keyword: "Pro3 H2S scavenger", country: "United States" },
  { keyword: "Pro3 HT triazine", country: "United States" },
  { keyword: "PureMark M500", country: "United States" },
  { keyword: "PureMark B800", country: "United States" },
  { keyword: "Enviro-Scrub", country: "United States" },
  { keyword: "HSCAV-80", country: "United States" },
  { keyword: "Kontin triazine", country: "United States" },
  { keyword: "HS-1526-40 triazine", country: "United States" },
  { keyword: "Sulfa-Check", country: "United States" },
  { keyword: "wholesale MEA triazine USA", country: "United States" },
  { keyword: "bulk MEA triazine Houston", country: "United States" },
  { keyword: "H2S scavenger Permian Basin", country: "United States" },
  { keyword: "triazine supplier Marcellus shale", country: "United States" },
  { keyword: "non-regenerable H2S scavenger", country: "United States" },
  { keyword: "MEA triazine TSCA listed", country: "United States" },
  { keyword: "triazine dosing rate calculator", country: "United States" },
  { keyword: "MEA triazine CIF Houston", country: "United States" },
  /* ── India ──────────────────────────────────────────────── */
  { keyword: "JadeScan54", country: "India" },
  { keyword: "Triazine Based H2S Scavenging Chemical", country: "India" },
  { keyword: "MEA Triazine 78% H2S Scavenger", country: "India" },
  { keyword: "78% MEA Triazine", country: "India" },
  { keyword: "Kalpur TE", country: "India" },
  { keyword: "MEA Triazine / JDC H2S Scavenger", country: "India" },
  { keyword: "SP-BIO-TZ", country: "India" },
  /* ── China ──────────────────────────────────────────────── */
  { keyword: "MEA Triazine 78%", country: "China" },
  { keyword: "MEA Triazine 78", country: "China" },
  { keyword: "BK Biocide", country: "China" },
  { keyword: "Triazine 78%", country: "China" },
  { keyword: "Triazine 78", country: "China" },
  { keyword: "MEA Triazine", country: "China" },
  { keyword: "Silworld", country: "China" },
  { keyword: "Silworld Triazine 78", country: "China" },
  { keyword: "G-SCAV EA77", country: "China" },
  { keyword: "Basolon SC 78", country: "China" },
  { keyword: "Sine PF77", country: "China" },
  { keyword: "Grotan BK equivalent", country: "China" },
  { keyword: "GreatAp HHT", country: "China" },
  { keyword: "Triazine BK", country: "China" },
  { keyword: "IR-Triazine", country: "China" },
  { keyword: "Water Treatment Biocide BK", country: "China" },
  { keyword: "H2S Scavenger (Triazine based)", country: "China" },
  { keyword: "High Purity Triazine", country: "China" },
  { keyword: "s-Triazine-1,3,5-triethanol", country: "China" },
  { keyword: "MEA Triazine Actane", country: "China" },
  { keyword: "Oil Drilling Fluid", country: "China" },
  /* ── Saudi Arabia ───────────────────────────────────────── */
  { keyword: "Triazine Scavenger", country: "Saudi Arabia" },
  { keyword: "MEA Triazine 78%", country: "Saudi Arabia" },
  { keyword: "G-SCAV EA77", country: "Saudi Arabia" },
  /* ── Germany ────────────────────────────────────────────── */
  { keyword: "Grotan HD", country: "Germany" },
  { keyword: "Grotan BK", country: "Germany" },
  { keyword: "Grotanol", country: "Germany" },
  { keyword: "Parmetol", country: "Germany" },
  { keyword: "Protectol HT", country: "Germany" },
  { keyword: "Basolon SC 78", country: "Germany" },
  { keyword: "KM 200", country: "Germany" },
  { keyword: "Dodigen NJ", country: "Germany" },
  { keyword: "Ottaform 204", country: "Germany" },
  /* ── UK ─────────────────────────────────────────────────── */
  { keyword: "Acticide GR", country: "United Kingdom" },
  { keyword: "Amebact C", country: "United Kingdom" },
  /* ── Spain ──────────────────────────────────────────────── */
  { keyword: "MEA Triazine 78%", country: "Spain" },
  /* ── Italy ──────────────────────────────────────────────── */
  { keyword: "MEA Triazine 78%", country: "Italy" },
  /* ── Switzerland ────────────────────────────────────────── */
  { keyword: "Nipacide BK", country: "Switzerland" },
  { keyword: "Triadine 3", country: "Switzerland" },
  /* ── Poland / Eastern Europe ────────────────────────────── */
  { keyword: "Roksol T", country: "Poland" },
  /* ── Canada ─────────────────────────────────────────────── */
  { keyword: "Permachem OB 2", country: "Canada" },
  /* ── Europe (multi-country) ─────────────────────────────── */
  { keyword: "Bactraclean", country: "Europe" },
  { keyword: "ETA 75", country: "Europe" },
  { keyword: "Acticide HHB", country: "Germany" },
  /* ── Vietnam ──────────────────────────────────────────────── */
  { keyword: "MEA Triazine 78% Vietnam", country: "Vietnam" },
  { keyword: "H2S scavenger supplier Vietnam", country: "Vietnam" },
  { keyword: "chất hấp thụ H2S triazine", country: "Vietnam" },
  { keyword: "hóa chất khử hydro sulfide", country: "Vietnam" },
  { keyword: "hóa chất xử lý khí chua triazine", country: "Vietnam" },
  { keyword: "triazine supplier Ho Chi Minh City", country: "Vietnam" },
  { keyword: "MEA Triazine import Vietnam", country: "Vietnam" },
  { keyword: "BK Biocide Vietnam", country: "Vietnam" },
  { keyword: "PetroVietnam H2S scavenger", country: "Vietnam" },
  { keyword: "oilfield chemicals Vietnam", country: "Vietnam" },
  { keyword: "nhà cung cấp MEA triazine Việt Nam", country: "Vietnam" },
  { keyword: "chất khử H2S cho dầu khí", country: "Vietnam" },
  { keyword: "MEA Triazine CIF Cat Lai", country: "Vietnam" },
  { keyword: "Dayong MEA Triazine", country: "Vietnam" },
  { keyword: "Grotan BK equivalent Vietnam", country: "Vietnam" },
  /* ── UAE / GCC ────────────────────────────────────────────── */
  { keyword: "MEA Triazine 78% UAE", country: "United Arab Emirates" },
  { keyword: "H2S scavenger supplier UAE", country: "United Arab Emirates" },
  { keyword: "MEA Triazine supplier Dubai", country: "United Arab Emirates" },
  { keyword: "triazine chemical supplier Abu Dhabi", country: "United Arab Emirates" },
  { keyword: "oilfield chemicals supplier UAE", country: "United Arab Emirates" },
  { keyword: "MEA Triazine CIF Jebel Ali", country: "United Arab Emirates" },
  { keyword: "ADNOC H2S scavenger", country: "United Arab Emirates" },
  { keyword: "sour gas treatment chemical UAE", country: "United Arab Emirates" },
  { keyword: "RXSOL triazine biocide", country: "United Arab Emirates" },
  { keyword: "Geco Chemicals UAE triazine", country: "United Arab Emirates" },
  { keyword: "مزيل كبريتيد الهيدروجين ترايازين", country: "United Arab Emirates" },
  { keyword: "كيماويات النفط والغاز الإمارات", country: "United Arab Emirates" },
  { keyword: "مورد ترايازين دبي", country: "United Arab Emirates" },
  { keyword: "معالجة الغاز الحامض", country: "United Arab Emirates" },
  { keyword: "MEA Triazine supplier Saudi Arabia", country: "Saudi Arabia" },
  { keyword: "Saudi Multichem Company triazine", country: "Saudi Arabia" },
  { keyword: "H2S scavenger Saudi Arabia", country: "Saudi Arabia" },
  { keyword: "MEA Triazine supplier Oman", country: "Oman" },
  { keyword: "H2S scavenger Qatar", country: "Qatar" },
  { keyword: "oilfield chemical supplier Kuwait", country: "Kuwait" },
  { keyword: "GCC oilfield chemicals", country: "United Arab Emirates" },
  { keyword: "MENA region chemical supplier", country: "United Arab Emirates" },
  /* ── Oman ─────────────────────────────────────────────── */
  { keyword: "MEA Triazine 78% Oman", country: "Oman" },
  { keyword: "H2S scavenger supplier Muscat", country: "Oman" },
  { keyword: "buy MEA Triazine Oman", country: "Oman" },
  { keyword: "triazine H2S scavenger Oman oil gas", country: "Oman" },
  { keyword: "oilfield chemical supplier Oman", country: "Oman" },
  { keyword: "H2S scavenger PDO operations", country: "Oman" },
  { keyword: "sour gas treatment chemical Oman", country: "Oman" },
  { keyword: "H2S scavenger Oman LNG", country: "Oman" },
  { keyword: "H2S scavenger BP Khazzan", country: "Oman" },
  { keyword: "triazine supplier Sohar port", country: "Oman" },
  { keyword: "MEA Triazine CIF Sohar", country: "Oman" },
  { keyword: "RXSOL triazine Oman", country: "Oman" },
  { keyword: "SULFA-CLEAR 8411HC Oman", country: "Oman" },
  { keyword: "MC MX 2-1106 Oman", country: "Oman" },
  { keyword: "OS TRI-SCAV triazine", country: "Oman" },
  { keyword: "MBBT H2S scavenger Muscat", country: "Oman" },
  { keyword: "كاسح كبريتيد الهيدروجين عُمان", country: "Oman" },
  { keyword: "مورد مواد كيميائية لإزالة H2S في عمان", country: "Oman" },
  { keyword: "معالجة الغاز الحامض عُمان", country: "Oman" },
  { keyword: "مواد كيميائية لحقول النفط عُمان", country: "Oman" },
  /* ── Egypt ────────────────────────────────────────────── */
  { keyword: "MEA Triazine 78% Egypt", country: "Egypt" },
  { keyword: "H2S scavenger supplier Egypt", country: "Egypt" },
  { keyword: "buy MEA Triazine Egypt", country: "Egypt" },
  { keyword: "H2S scavenger supplier Cairo", country: "Egypt" },
  { keyword: "oilfield chemical supplier Egypt", country: "Egypt" },
  { keyword: "H2S scavenger Zohr gas field", country: "Egypt" },
  { keyword: "sour gas treatment chemical Nile Delta", country: "Egypt" },
  { keyword: "triazine Western Desert Egypt", country: "Egypt" },
  { keyword: "H2S scavenger MIDOR refinery", country: "Egypt" },
  { keyword: "MEA Triazine CIF Alexandria", country: "Egypt" },
  { keyword: "triazine supplier Damietta port", country: "Egypt" },
  { keyword: "ACPA H2S scavenger Egypt", country: "Egypt" },
  { keyword: "Scomi Egypt triazine", country: "Egypt" },
  { keyword: "AquaNile H2S scavenger", country: "Egypt" },
  { keyword: "oilfield chemical import Egypt GOEIC", country: "Egypt" },
  { keyword: "مادة كاسحة لكبريتيد الهيدروجين مصر", country: "Egypt" },
  { keyword: "مورد كيماويات حقول النفط مصر", country: "Egypt" },
  { keyword: "معالجة الغاز الحامض مصر", country: "Egypt" },
  { keyword: "كاسح كبريتيد الهيدروجين مصر", country: "Egypt" },
  { keyword: "مورد ترايازين مصر", country: "Egypt" },
  /* ── Brazil ───────────────────────────────────────────── */
  { keyword: "MEA Triazine 78% Brazil", country: "Brazil" },
  { keyword: "H2S scavenger supplier Brazil", country: "Brazil" },
  { keyword: "buy MEA Triazine Brazil", country: "Brazil" },
  { keyword: "oilfield chemical supplier Brazil", country: "Brazil" },
  { keyword: "H2S scavenger pre-salt operations", country: "Brazil" },
  { keyword: "H2S scavenger Santos Basin", country: "Brazil" },
  { keyword: "H2S scavenger Campos Basin", country: "Brazil" },
  { keyword: "triazine Buzios field Brazil", country: "Brazil" },
  { keyword: "H2S treatment Petrobras FPSO", country: "Brazil" },
  { keyword: "MEA Triazine CIF Santos", country: "Brazil" },
  { keyword: "triazine deepwater operations Brazil", country: "Brazil" },
  { keyword: "SCAVTREAT 1063 Brazil", country: "Brazil" },
  { keyword: "ABATE S-200 Brazil", country: "Brazil" },
  { keyword: "Global Trend MEA-Triazina", country: "Brazil" },
  { keyword: "oilfield chemical import Brazil IBAMA", country: "Brazil" },
  { keyword: "removedor de H2S triazina MEA", country: "Brazil" },
  { keyword: "fornecedor de triazina MEA Brasil", country: "Brazil" },
  { keyword: "captador de sulfeto de hidrogênio", country: "Brazil" },
  { keyword: "triazina para operações de pré-sal", country: "Brazil" },
  { keyword: "comprar triazina MEA 78% Brasil", country: "Brazil" },
  /* ── Saudi Arabia ────────────────────────────────────── */
  { keyword: "MEA Triazine 78% Saudi Arabia", country: "Saudi Arabia" },
  { keyword: "H2S scavenger supplier Saudi Arabia", country: "Saudi Arabia" },
  { keyword: "buy MEA Triazine Saudi Arabia", country: "Saudi Arabia" },
  { keyword: "H2S scavenger supplier Dammam", country: "Saudi Arabia" },
  { keyword: "H2S scavenger supplier Jubail", country: "Saudi Arabia" },
  { keyword: "oilfield chemical supplier Saudi Arabia", country: "Saudi Arabia" },
  { keyword: "H2S scavenger Saudi Aramco", country: "Saudi Arabia" },
  { keyword: "H2S scavenger Ghawar field", country: "Saudi Arabia" },
  { keyword: "H2S scavenger Wasit gas plant", country: "Saudi Arabia" },
  { keyword: "H2S scavenger Fadhili gas plant", country: "Saudi Arabia" },
  { keyword: "H2S scavenger Haradh gas plant", country: "Saudi Arabia" },
  { keyword: "H2S scavenger Jafurah gas field", country: "Saudi Arabia" },
  { keyword: "MEA Triazine CIF Dammam", country: "Saudi Arabia" },
  { keyword: "SAMSS approved H2S scavenger", country: "Saudi Arabia" },
  { keyword: "SASO compliant chemical import", country: "Saudi Arabia" },
  { keyword: "IKTVA chemical supplier", country: "Saudi Arabia" },
  { keyword: "Chemara HS-1501 alternative", country: "Saudi Arabia" },
  { keyword: "G-SCAV EA77 alternative KSA", country: "Saudi Arabia" },
  { keyword: "SUGEST H2S scavenger Saudi", country: "Saudi Arabia" },
  { keyword: "NassGuard MEA Saudi", country: "Saudi Arabia" },
  { keyword: "NGL processing chemical Saudi", country: "Saudi Arabia" },
  { keyword: "مزيل كبريتيد الهيدروجين ترايازين السعودية", country: "Saudi Arabia" },
  { keyword: "كاسح H2S ترايازين المملكة العربية السعودية", country: "Saudi Arabia" },
  { keyword: "مورد كيماويات حقول النفط السعودية", country: "Saudi Arabia" },
  { keyword: "كاسح كبريتيد الهيدروجين أرامكو", country: "Saudi Arabia" },
  { keyword: "معالجة الغاز الحامض السعودية", country: "Saudi Arabia" },
  /* ── Iraq ──────────────────────────────────────────── */
  { keyword: "MEA Triazine 78% Iraq", country: "Iraq" },
  { keyword: "H2S scavenger supplier Iraq", country: "Iraq" },
  { keyword: "buy MEA Triazine Iraq", country: "Iraq" },
  { keyword: "H2S scavenger supplier Basra", country: "Iraq" },
  { keyword: "H2S scavenger supplier Erbil", country: "Iraq" },
  { keyword: "oilfield chemical supplier Iraq", country: "Iraq" },
  { keyword: "H2S scavenger Rumaila field", country: "Iraq" },
  { keyword: "H2S scavenger West Qurna field", country: "Iraq" },
  { keyword: "H2S scavenger Zubair field", country: "Iraq" },
  { keyword: "H2S scavenger Kurdistan oilfields", country: "Iraq" },
  { keyword: "H2S removal Basra oil operations", country: "Iraq" },
  { keyword: "H2S scavenger Basra Gas Company", country: "Iraq" },
  { keyword: "MEA Triazine CIF Umm Qasr", country: "Iraq" },
  { keyword: "oilfield chemical import Iraq", country: "Iraq" },
  { keyword: "H2S scavenger BP Rumaila JV", country: "Iraq" },
  { keyword: "Tawreed H2S scavenger alternative", country: "Iraq" },
  { keyword: "ALDUHA H2S scavenger alternative", country: "Iraq" },
  { keyword: "SAHARA MEA triazine Rumaila", country: "Iraq" },
  { keyword: "Petrobon MEA alternative Iraq", country: "Iraq" },
  { keyword: "كاسح كبريتيد الهيدروجين العراق", country: "Iraq" },
  { keyword: "مورد كيماويات حقول النفط العراق", country: "Iraq" },
  { keyword: "مورد ترايازين البصرة", country: "Iraq" },
  { keyword: "كاسح H2S حقل الرميلة", country: "Iraq" },
  { keyword: "معالجة الغاز الحامض العراق", country: "Iraq" },
  /* ── Qatar ──────────────────────────────────────────── */
  { keyword: "MEA Triazine 78% Qatar", country: "Qatar" },
  { keyword: "MEA triazine supplier Qatar", country: "Qatar" },
  { keyword: "H2S scavenger supplier Qatar", country: "Qatar" },
  { keyword: "H2S scavenger supplier Doha", country: "Qatar" },
  { keyword: "buy MEA Triazine Qatar", country: "Qatar" },
  { keyword: "mono ethanol amine triazine manufacturer Qatar", country: "Qatar" },
  { keyword: "oilfield chemical supplier Qatar", country: "Qatar" },
  { keyword: "H2S scavenger QatarEnergy North Field", country: "Qatar" },
  { keyword: "H2S scavenger Ras Laffan LNG", country: "Qatar" },
  { keyword: "H2S scavenger Pearl GTL Qatar", country: "Qatar" },
  { keyword: "sour gas treatment chemical Qatar", country: "Qatar" },
  { keyword: "triazine based scavenger Qatar", country: "Qatar" },
  { keyword: "MEA Triazine CIF Hamad Port", country: "Qatar" },
  { keyword: "H2S scavenger North Field Expansion", country: "Qatar" },
  { keyword: "MEA triazine Ras Laffan", country: "Qatar" },
  { keyword: "MEA triazine LNG gas treatment Qatar", country: "Qatar" },
  { keyword: "triazine H2S scavenger Doha", country: "Qatar" },
  { keyword: "H2S scavenger Dolphin gas pipeline", country: "Qatar" },
  { keyword: "BKC Gulf triazine alternative", country: "Qatar" },
  { keyword: "RXSOL triazine Qatar", country: "Qatar" },
  { keyword: "HS-1526-40 equivalent Qatar", country: "Qatar" },
  { keyword: "SULFA-CLEAR alternative Qatar", country: "Qatar" },
  { keyword: "monoethanolamine triazine 78% Qatar", country: "Qatar" },
  { keyword: "H2S removal chemical Qatar wholesale", country: "Qatar" },
  { keyword: "كاسح كبريتيد الهيدروجين قطر", country: "Qatar" },
  { keyword: "مورد ترايازين قطر", country: "Qatar" },
  { keyword: "مورد مواد كيميائية لمعالجة الغاز قطر", country: "Qatar" },
  { keyword: "معالجة الغاز الحامض قطر", country: "Qatar" },
  { keyword: "كيماويات حقول النفط قطر", country: "Qatar" },
  { keyword: "كاسح H2S حقل الشمال", country: "Qatar" },
  /* ── Kuwait ──────────────────────────────────────────── */
  { keyword: "MEA Triazine 78% Kuwait", country: "Kuwait" },
  { keyword: "MEA triazine supplier Kuwait", country: "Kuwait" },
  { keyword: "H2S scavenger supplier Kuwait", country: "Kuwait" },
  { keyword: "H2S scavenger supplier Ahmadi", country: "Kuwait" },
  { keyword: "buy MEA Triazine Kuwait", country: "Kuwait" },
  { keyword: "mono ethanol amine triazine manufacturer Kuwait", country: "Kuwait" },
  { keyword: "oilfield chemical supplier Kuwait", country: "Kuwait" },
  { keyword: "H2S scavenger KOC operations", country: "Kuwait" },
  { keyword: "H2S scavenger Burgan field Kuwait", country: "Kuwait" },
  { keyword: "H2S scavenger KNPC refinery", country: "Kuwait" },
  { keyword: "sour gas treatment chemical Kuwait", country: "Kuwait" },
  { keyword: "triazine based scavenger Kuwait", country: "Kuwait" },
  { keyword: "MEA Triazine CIF Shuwaikh Port", country: "Kuwait" },
  { keyword: "H2S scavenger Ratqa field", country: "Kuwait" },
  { keyword: "H2S scavenger Minagish field", country: "Kuwait" },
  { keyword: "triazine H2S scavenger Shuaiba", country: "Kuwait" },
  { keyword: "Bait Al Aseel triazine alternative", country: "Kuwait" },
  { keyword: "RXSOL triazine Kuwait", country: "Kuwait" },
  { keyword: "HME-FILM triazine alternative Kuwait", country: "Kuwait" },
  { keyword: "Triasorb alternative Kuwait", country: "Kuwait" },
  { keyword: "monoethanolamine triazine 78% Kuwait", country: "Kuwait" },
  { keyword: "كاسح كبريتيد الهيدروجين الكويت", country: "Kuwait" },
  { keyword: "مورد ترايازين الكويت", country: "Kuwait" },
  { keyword: "معالجة الغاز الحامض الكويت", country: "Kuwait" },
  { keyword: "كيماويات حقول النفط الكويت", country: "Kuwait" },
  /* ── Thailand ─────────────────────────────────────────── */
  { keyword: "MEA Triazine 78% Thailand", country: "Thailand" },
  { keyword: "MEA triazine supplier Thailand", country: "Thailand" },
  { keyword: "H2S scavenger supplier Thailand", country: "Thailand" },
  { keyword: "H2S scavenger supplier Bangkok", country: "Thailand" },
  { keyword: "buy MEA Triazine Thailand", country: "Thailand" },
  { keyword: "mono ethanol amine triazine manufacturer Thailand", country: "Thailand" },
  { keyword: "oilfield chemical supplier Thailand", country: "Thailand" },
  { keyword: "H2S scavenger PTTEP Thailand", country: "Thailand" },
  { keyword: "H2S scavenger Gulf of Thailand offshore", country: "Thailand" },
  { keyword: "H2S scavenger Map Ta Phut", country: "Thailand" },
  { keyword: "sour gas treatment chemical Thailand", country: "Thailand" },
  { keyword: "H2S scavenger biogas Thailand", country: "Thailand" },
  { keyword: "MEA Triazine CIF Laem Chabang", country: "Thailand" },
  { keyword: "Brenntag MEA alternative Thailand", country: "Thailand" },
  { keyword: "PTT GC MEA alternative Thailand", country: "Thailand" },
  { keyword: "BK Biocide alternative Thailand", country: "Thailand" },
  { keyword: "Borregaard H2S scavenger alternative", country: "Thailand" },
  { keyword: "monoethanolamine triazine 78% Thailand", country: "Thailand" },
  { keyword: "สารกำจัด H2S ไตรอะซีน", country: "Thailand" },
  { keyword: "สารดักจับไฮโดรเจนซัลไฟด์", country: "Thailand" },
  { keyword: "สารบำบัดก๊าซเปรี้ยว", country: "Thailand" },
  { keyword: "เคมีภัณฑ์สำหรับอุตสาหกรรมน้ำมันและแก๊ส", country: "Thailand" },
  { keyword: "สารเคมีขจัดไฮโดรเจนซัลไฟด์ก๊าซชีวภาพ", country: "Thailand" },
  /* ── Iran ────────────────────────────────────────────── */
  { keyword: "MEA Triazine 78% Iran", country: "Iran" },
  { keyword: "MEA triazine supplier Iran", country: "Iran" },
  { keyword: "H2S scavenger supplier Iran", country: "Iran" },
  { keyword: "H2S scavenger supplier Tehran", country: "Iran" },
  { keyword: "buy MEA Triazine Iran", country: "Iran" },
  { keyword: "mono ethanol amine triazine manufacturer Iran", country: "Iran" },
  { keyword: "oilfield chemical supplier Iran", country: "Iran" },
  { keyword: "H2S scavenger South Pars", country: "Iran" },
  { keyword: "H2S scavenger Assaluyeh", country: "Iran" },
  { keyword: "H2S scavenger NIOC operations", country: "Iran" },
  { keyword: "sour gas treatment chemical Iran", country: "Iran" },
  { keyword: "triazine based scavenger Iran", country: "Iran" },
  { keyword: "MEA Triazine CIF Bandar Abbas", country: "Iran" },
  { keyword: "Tsorb3400 alternative Iran", country: "Iran" },
  { keyword: "Tasfyeh Group triazine alternative", country: "Iran" },
  { keyword: "Chemical Iran MEA alternative", country: "Iran" },
  { keyword: "Triasorb alternative Iran", country: "Iran" },
  { keyword: "monoethanolamine triazine 78% Iran", country: "Iran" },
  { keyword: "حذف‌کننده H2S تری‌آزین", country: "Iran" },
  { keyword: "حذف‌کننده سولفید هیدروژن ایران", country: "Iran" },
  { keyword: "تصفیه گاز ترش ایران", country: "Iran" },
  { keyword: "مواد شیمیایی صنعتی میدان پارس جنوبی", country: "Iran" },
  { keyword: "خرید تری‌آزین MEA ایران", country: "Iran" },
] as const;

/**
 * Competitor brand → application mapping.
 * Shows where MEA Triazine 78% can serve as a drop-in alternative.
 * Use for comparison pages, FAQ schema, and "alternative to" SEO content.
 */
export const MEA_TRIAZINE_COMPETITOR_APPLICATIONS = [
  /* ── Metalworking & Cutting Fluids ──────────────────────── */
  {
    brand: "Grotan BK",
    application: "Benchmark biocide for cutting fluids",
    industry: "Metalworking",
    meaTriazineRole: "Biocide and H2S scavenger for metalworking fluid preservation",
  },
  {
    brand: "Triadine 3",
    application: "EPA-registered biocide (Arxada)",
    industry: "Metalworking",
    meaTriazineRole: "Cost-effective triazine alternative for metalworking biocide applications",
  },
  /* ── Industrial Preservation ────────────────────────────── */
  {
    brand: "Grotan HD",
    application: "Technical preservation solution",
    industry: "Industrial",
    meaTriazineRole: "High-concentration triazine preservative for industrial fluid systems",
  },
  {
    brand: "Grotan B",
    application: "Formaldehyde-releasing preservative",
    industry: "Industrial",
    meaTriazineRole: "Formaldehyde-donor biocide for broad-spectrum industrial preservation",
  },
  {
    brand: "Ottaform 204",
    application: "Formaldehyde donor biocide",
    industry: "Industrial",
    meaTriazineRole: "Triazine-based formaldehyde-releasing biocide for technical fluids",
  },
  {
    brand: "Roksol T 1-7",
    application: "Industrial biocide for technical fluids",
    industry: "CIS / Russia",
    meaTriazineRole: "Export-grade MEA Triazine alternative for CIS-region technical fluid preservation",
  },
  {
    brand: "Syntan OXB",
    application: "Additive for leather and technical fluids",
    industry: "Industrial",
    meaTriazineRole: "Biocide additive for leather processing and technical fluid systems",
  },
  /* ── Coatings & Paints ──────────────────────────────────── */
  {
    brand: "Nipacide BK",
    application: "In-can preservative for paints",
    industry: "Coatings",
    meaTriazineRole: "In-can preservation biocide for water-based paint and coating systems",
  },
  {
    brand: "Nuosept 78",
    application: "Industrial preservative for water-based media",
    industry: "Coatings",
    meaTriazineRole: "78% active triazine preservative for water-based coatings and emulsions",
  },
  /* ── Water Treatment & Paper ────────────────────────────── */
  {
    brand: "Busan 1060",
    application: "Water treatment and slime control",
    industry: "Paper / Oil",
    meaTriazineRole: "Triazine-based slime control and water treatment biocide",
  },
  {
    brand: "Busan 1506",
    application: "Broad-spectrum antimicrobial",
    industry: "Industrial",
    meaTriazineRole: "Broad-spectrum antimicrobial triazine for industrial water systems",
  },
  /* ── Adhesives & Emulsions ──────────────────────────────── */
  {
    brand: "Onyxide 200",
    application: "Highly active bactericide for emulsions",
    industry: "Adhesives",
    meaTriazineRole: "High-activity bactericide for adhesive and emulsion preservation",
  },
  /* ── Oilfield ───────────────────────────────────────────── */
  {
    brand: "Scavtreat",
    application: "Proprietary H2S scavenger blend (SLB)",
    industry: "Oilfield",
    meaTriazineRole: "Direct H2S scavenging alternative for upstream oil and gas operations",
  },
  /* ── Cleaning & Disinfection ────────────────────────────── */
  {
    brand: "Bactraclean",
    application: "Professional cleaning products",
    industry: "Disinfectant",
    meaTriazineRole: "Active biocide ingredient for professional cleaning and disinfectant formulations",
  },
  {
    brand: "Actane",
    application: "Biocide and anti-mildew agent",
    industry: "Global",
    meaTriazineRole: "Anti-mildew and antimicrobial triazine for global biocide applications",
  },
  /* ── Personal Care & Cosmetics ──────────────────────────── */
  {
    brand: "Miliden X-2",
    application: "Bactericide in cosmetic products",
    industry: "Personal Care",
    meaTriazineRole: "Cosmetic-grade triazine bactericide for personal care formulations",
  },
  {
    brand: "Kalpur TE",
    application: "Biocide in pesticides and cosmetics",
    industry: "Europe",
    meaTriazineRole: "Triazine biocide for European pesticide and cosmetic applications",
  },
  /* ── UAE/GCC Oilfield Branded Products ──────────────────── */
  {
    brand: "RXSOL-43-8160-210",
    application: "Triazine-based biocide for UAE/Oman oilfields (RX Chemicals)",
    industry: "Oilfield",
    meaTriazineRole: "Direct MEA Triazine alternative to RXSOL triazine biocide for MENA oilfield applications",
  },
  {
    brand: "Saudi Multichem MEA Triazine",
    application: "Regional triazine producer in Saudi Arabia",
    industry: "Oilfield",
    meaTriazineRole: "Indian-manufactured 78% MEA Triazine as competitive alternative to Saudi Multichem supply",
  },
  /* ── Oman-Market Branded Products ───────────────────── */
  {
    brand: "SULFA-CLEAR 8411HC",
    application: "80% activity MEA Triazine H2S scavenger (Lubrizol, distributed in Oman)",
    industry: "Oilfield",
    meaTriazineRole: "Direct manufacturer-priced 78% MEA Triazine as cost-effective alternative to Lubrizol SULFA-CLEAR for Oman oilfield operations",
  },
  {
    brand: "MC MX 2-1106",
    application: "H2S scavenger equivalent (Muscat Chemical, Oman)",
    industry: "Oilfield",
    meaTriazineRole: "Indian-manufactured 78% MEA Triazine as competitive alternative to Muscat Chemical MC MX 2-1106 for PDO and Oman LNG operations",
  },
  {
    brand: "MBBT H2S Scavenger",
    application: "Oilfield H2S scavenger (Muscat & Barka Business Trading, Oman)",
    industry: "Oilfield",
    meaTriazineRole: "Direct supply of 78% MEA Triazine from India to Oman with 2–4 day Sohar Port transit as alternative to MBBT local supply",
  },
  {
    brand: "G-SCAV EA77",
    application: "77% active triazine H2S scavenger",
    industry: "Oilfield",
    meaTriazineRole: "Higher 78% concentration alternative to G-SCAV EA77 for GCC oilfield operations",
  },
  /* ── USA Oilfield Branded Products ──────────────────────── */
  {
    brand: "Pro3",
    application: "Non-triazine and triazine-blend H2S scavenger (Q2 Technologies)",
    industry: "Oilfield",
    meaTriazineRole: "Drop-in MEA Triazine alternative to Q2 Technologies Pro3 product line",
  },
  {
    brand: "PureMark M500",
    application: "MEA triazine scavenger (Foremark Performance)",
    industry: "Oilfield",
    meaTriazineRole: "Direct equivalent to Foremark PureMark M500 for oil and gas H2S scavenging",
  },
  {
    brand: "PureMark B800",
    application: "High-concentration scavenger (Foremark Performance)",
    industry: "Oilfield",
    meaTriazineRole: "78% active alternative to Foremark PureMark B800 scavenger",
  },
  {
    brand: "Enviro-Scrub",
    application: "Environmental H2S scavenger (Q2 Technologies)",
    industry: "Biogas / Landfill",
    meaTriazineRole: "Cost-effective triazine alternative for biogas and landfill gas H2S removal",
  },
  {
    brand: "HSCAV-80",
    application: "80% MEA Triazine (Geocon Products)",
    industry: "Oilfield",
    meaTriazineRole: "Comparable 78% active MEA Triazine as alternative to Geocon HSCAV-80",
  },
  {
    brand: "Kontin",
    application: "Triazine scavenger (Geocon Products)",
    industry: "Oilfield",
    meaTriazineRole: "Direct triazine scavenger alternative to Geocon Kontin product",
  },
  /* ── High-Purity / Specialty ────────────────────────────── */
  {
    brand: "Protectol HT",
    application: "BASF brand for high-purity triazine",
    industry: "High-end",
    meaTriazineRole: "High-purity 78% MEA Triazine as cost-effective Protectol HT alternative",
  },
  {
    brand: "ETA 75",
    application: "Generic term for 75% active triazine",
    industry: "Industrial",
    meaTriazineRole: "Higher-concentration 78% alternative to standard 75% triazine products",
  },
  {
    brand: "KM 200",
    application: "Alcohol-based biocide formulations",
    industry: "Industrial",
    meaTriazineRole: "Water-soluble triazine biocide alternative to alcohol-based KM 200 formulations",
  },
  /* ── Qatar-Market Branded Products ─────────────────────── */
  {
    brand: "BKC Gulf Triazine Scavenger",
    application: "Qatar-focused triazine H2S scavenger supply (BKC Gulf)",
    industry: "Oilfield",
    meaTriazineRole: "Direct manufacturer-priced 78% MEA Triazine as competitive alternative to BKC Gulf triazine supply for Qatar oil and gas operations",
  },
  {
    brand: "HS-1526-40 (Univar Solutions)",
    application: "Triazine H2S scavenger distributed globally by Univar",
    industry: "Oilfield",
    meaTriazineRole: "Direct-from-manufacturer 78% MEA Triazine as cost-effective alternative to Univar HS-1526-40 for QatarEnergy and Ras Laffan operations",
  },
  {
    brand: "ChampionX H2S Scavenger",
    application: "QatarEnergy-approved H2S scavenger (ChampionX)",
    industry: "Oilfield",
    meaTriazineRole: "Indian-manufactured 78% MEA Triazine with CIF Qatar delivery as competitive alternative to ChampionX H2S scavenger products",
  },
  {
    brand: "Baker Hughes H2S Scavenger",
    application: "QatarEnergy-approved H2S scavenger (Baker Hughes)",
    industry: "Oilfield",
    meaTriazineRole: "Direct supply 78% MEA Triazine from India as cost-effective alternative to Baker Hughes H2S scavenger for North Field operations",
  },
  {
    brand: "Deluxe MEA (Qatar)",
    application: "Mono Ethanol Amine supplier in Qatar (Deluxe Trading Services WLL)",
    industry: "Gas Treatment",
    meaTriazineRole: "MEA Triazine 78% (finished H2S scavenger product) vs raw MEA — higher concentration and ready-to-use for Qatar gas treatment",
  },
  {
    brand: "K2P MEA-T",
    application: "Monoethanolamine Triazine scavenger (K2P Chemical Products)",
    industry: "Oilfield",
    meaTriazineRole: "Direct manufacturer 78% MEA Triazine as alternative to K2P Chemical MEA-T for gas sweetening and H2S removal",
  },
  /* ── Kuwait-Market Branded Products ─────────────────────── */
  {
    brand: "Bait Al Aseel H2S Scavenger",
    application: "Kuwait-based H₂S Scavenger – Triazine Based supply (Bait Al Aseel Trading, Shuwaikh)",
    industry: "Oilfield",
    meaTriazineRole: "Direct manufacturer-priced 78% MEA Triazine as competitive alternative to Bait Al Aseel triazine supply for KOC and KNPC operations",
  },
  {
    brand: "DK Petrochemicals MEA (Kuwait)",
    application: "Mono Ethanol Amine commodity chemical (Dar Al Kuwait Petrochemical Company)",
    industry: "Gas Treatment",
    meaTriazineRole: "MEA Triazine 78% (finished H2S scavenger) vs raw MEA — higher concentration and ready-to-use for Kuwait sour crude operations",
  },
  {
    brand: "HME-FILM MEA Triazine",
    application: "MEA Triazine-based high performance scavenger (MED Drilling Fluids, GCC)",
    industry: "Oilfield / Drilling",
    meaTriazineRole: "Direct manufacturer 78% MEA Triazine as cost-effective alternative to HME-FILM for Kuwait drilling and production H2S scavenging",
  },
  {
    brand: "Triasorb (Sintez-Oka)",
    application: "Russian-manufactured MEA triazine H2S absorber (Sintez-Oka)",
    industry: "Oilfield",
    meaTriazineRole: "Indian-manufactured 78% MEA Triazine with 4-6 day delivery to Kuwait as faster, cost-effective alternative to Triasorb from Russia",
  },
  {
    brand: "Xipeng MEA Triazine 78%",
    application: "Chinese-manufactured MEA Triazine (Xipeng Technology, Chennai office)",
    industry: "Oilfield",
    meaTriazineRole: "Indian-manufactured 78% MEA Triazine with guaranteed concentration and batch traceability as alternative to Chinese-sourced Xipeng product",
  },
  /* ── Thailand-Market Branded Products ──────────────────── */
  {
    brand: "Brenntag MEA (Thailand)",
    application: "Monoethanolamine distributor in Thailand (Brenntag Ingredients Thailand, Bangkok)",
    industry: "Gas Treatment / Chemical Processing",
    meaTriazineRole: "MEA Triazine 78% (finished H2S scavenger) vs raw MEA distributed by Brenntag — higher concentration, ready-to-use, no further processing needed",
  },
  {
    brand: "PTT GC MEA (Thailand)",
    application: "Thai-manufactured raw Monoethanolamine (PTT Global Chemical, Map Ta Phut)",
    industry: "Gas Treatment / Petrochemical",
    meaTriazineRole: "MEA Triazine 78% (finished scavenger product) vs PTT GC raw MEA — purpose-built H2S scavenger requiring no conversion or regeneration equipment",
  },
  {
    brand: "Borregaard H2S Scavenger",
    application: "Bio-based H2S scavenger (Borregaard, Norway)",
    industry: "Oilfield",
    meaTriazineRole: "Cost-effective 78% MEA Triazine as alternative to premium-priced Borregaard bio-based H2S scavenger for Thailand offshore and biogas operations",
  },
  {
    brand: "ECHEMI MEA Triazine 78%",
    application: "Chinese marketplace MEA Triazine (ECHEMI B2B platform)",
    industry: "Oilfield",
    meaTriazineRole: "Indian-manufactured 78% MEA Triazine with guaranteed batch quality, COA, and GHS documentation vs marketplace-sourced Chinese product with variable quality",
  },
  /* ── Iran-Market Branded Products ─────────────────────── */
  {
    brand: "Tsorb3400 (Tasfyeh Group)",
    application: "Iranian-manufactured MEA Triazine H2S scavenger (Tasfyeh Group, Iran — 50%, 60%, 80% variants)",
    industry: "Oilfield",
    meaTriazineRole: "Cost-competitive Indian-manufactured 78% MEA Triazine as import alternative to Tsorb3400 with consistent concentration and batch documentation for Iran operations",
  },
  {
    brand: "Chemical Iran MEA",
    application: "Raw Monoethanolamine supplier (Chemical Iran, Tehran — since 2011)",
    industry: "Gas Treatment",
    meaTriazineRole: "MEA Triazine 78% (finished H2S scavenger) vs Chemical Iran raw MEA — higher H2S removal efficiency, non-regenerable, no conversion equipment needed",
  },
  {
    brand: "IranChemicalMine MEA",
    application: "High purity Monoethanolamine exporter (Iran Chemical Mine)",
    industry: "Gas Treatment",
    meaTriazineRole: "MEA Triazine 78% (CAS 4719-04-4) vs raw MEA (CAS 141-43-5) — purpose-built scavenger for Iran oilfield operations",
  },
  {
    brand: "Triasorb (Iran supply)",
    application: "Russian MEA triazine H2S absorber supplied to Iran (Sintez-Oka)",
    industry: "Oilfield",
    meaTriazineRole: "Indian 78% MEA Triazine with 3-5 day transit to Bandar Abbas as faster, cost-competitive alternative to Russian Triasorb supply",
  },
] as const;
