export type SynonymGroup = {
  heading: string;
  items: string[];
};

export type ProductSynonyms = {
  intro: string;
  groups: SynonymGroup[];
  casNote?: string;
  closingText: string;
};

export const MEA_TRIAZINE_SYNONYMS: ProductSynonyms = {
  intro:
    "MEA Triazine 78% is known by many chemical names, IUPAC names, and trade names. Our product is the same compound regardless of the name your specification uses:",
  groups: [
    {
      heading: "IUPAC and Chemical Names",
      items: [
        "Hexahydro-1,3,5-tris(2-hydroxyethyl)-s-triazine",
        "1,3,5-Triazine-1,3,5(2H,4H,6H)-triethanol",
        "2,2',2''-(1,3,5-triazinane-1,3,5-triyl)triethanol",
        "2,2',2''-(hexahydro-1,3,5-triazine-1,3,5-triyl)triethanol",
        "TRIS(N-HYDROXYETHYL) HEXAHYDROTRIAZINE",
        "HEXAHYDRO-1,3,5-TRIS(HYDROXYETHYL)-S-TRIAZINE",
        "1,3,5-Tris(2-hydroxyethyl)hexahydro-1,3,5-triazine",
        "Triazinetriethanol",
        "HHT (Hexahydrotriazine Triethanol)",
      ],
    },
    {
      heading: "Trade Names and Brand Equivalents",
      items: [
        "Grotan BK (equivalent)",
        "J2.219E",
        "MEA based Triazine",
        "MEA Triazine",
        "1,3,5-Triazine",
      ],
    },
    {
      heading: "Application-Based Names",
      items: [
        "H2S Scavenger",
        "Hydrogen Sulfide Scavenger",
        "Mercaptan Scavenger",
        "Gas Sweetener / Sweetening Agent",
        "Desulfurizer",
        "Offshore H2S Scavenger",
        "Onshore H2S Scavenger",
        "Triazine H2S Scavenger",
        "Formaldehyde-Releasing Biocide",
        "Industrial Microbiocide / Microbiostat",
        "Slimicide",
        "Bactericide and Algicide",
        "Cutting Fluid Preservative",
        "Anti-mildew Agent",
        "Industrial Preservation Biocide",
      ],
    },
    {
      heading: "Vietnamese-Language Names (Tên tiếng Việt)",
      items: [
        "Chất hấp thụ H2S (H2S Absorbent)",
        "Hóa chất khử hydro sulfide (Hydrogen Sulfide Remover)",
        "Hóa chất xử lý khí chua (Sour Gas Treatment Chemical)",
        "Chất khử lưu huỳnh (Desulfurization Chemical)",
        "Triazine xử lý khí chua (Sour Gas Triazine)",
        "Hóa chất dầu khí MEA Triazine (Oil & Gas Chemical)",
      ],
    },
    {
      heading: "Brand Names Recognized in Vietnam",
      items: [
        "BK Biocide (Chinese trade name, widely traded in SEA)",
        "Dayong MEA Triazine (Dongying Dayong, Made-in-China)",
        "IRO MEA Triazine (IRO Group Inc.)",
        "JDC H2S Scavenger (Jay Dinesh Chemicals)",
        "H2S Scavenger Conc (generic trade description)",
        "MEA-T (Monoethanolamine Triazine abbreviation)",
        "Amine Solution (Q2 Technologies descriptor)",
      ],
    },
    {
      heading: "Brand Names Recognized in the USA",
      items: [
        "Pro3 / Pro3 HT / Pro3 GT / Pro3 NGL (Q2 Technologies)",
        "PureMark M500 / PureMark B800 (Foremark Performance Chemicals)",
        "Enviro-Scrub / Enviro-Scrub Bio (Q2 Technologies)",
        "HSCAV-80 / Kontin (Geocon Products)",
        "HS-1526-40 (Univar Solutions product code)",
        "Sulfa-Check (oilfield trade name)",
        "Bioban GK (Dow Chemical)",
        "Onyxide 200 (Lonza)",
        "Busan 1060 / Busan 1506 (Buckman Laboratories)",
        "Nuosept 78 (industrial preservative)",
        "Protectol HT (BASF)",
        "Triadine 3 / Triadine 10 (Arxada / Lonza)",
        "Troyshield B2 (Troy Chemical)",
      ],
    },
    {
      heading: "Arabic-Language Names (الأسماء العربية)",
      items: [
        "مزيل كبريتيد الهيدروجين (H2S Scavenger)",
        "كاسح H2S (H2S Scavenger)",
        "مادة إزالة كبريتيد الهيدروجين (H2S Removal Substance)",
        "معالجة الغاز الحامض (Sour Gas Treatment)",
        "إزالة الكبريت (Desulfurization)",
        "كيماويات حقول النفط (Oilfield Chemicals)",
        "مبيد حيوي ترايازين (Triazine Biocide)",
      ],
    },
    {
      heading: "Brand Names Recognized in UAE / GCC",
      items: [
        "RXSOL-43-8160-210 (RX Chemicals, UAE/India/Oman)",
        "Saudi Multichem MEA Triazine (Saudi Arabia regional producer)",
        "Geco Chemicals Triazine (UAE, Alibaba-listed)",
        "G-SCAV EA77 (77% active, specialty scavenger)",
        "BASOLON SC 78 (BASF, 78% H2S scavenger)",
        "STEPANQUAT 200 (Stepan Company)",
        "H2Stopper 1908C (specialty H2S scavenger)",
        "SINE PF77 (Chinese manufacturer, multiple variants)",
        "Dorf Ketal (service company, ADNOC JVs)",
        "Scomi Group (regional oilfield services)",
      ],
    },
    {
      heading: "Brand Names Recognized in Oman",
      items: [
        "RXSOL H2S Scavenger (RXSOL-11-5014-210, Oman Chemical)",
        "MC MX 2-1106 (Muscat Chemical, H2S scavenger equivalent)",
        "SULFA-CLEAR™ 8411HC (Lubrizol, 80% MEA Triazine, distributed in Oman)",
        "SULFA-CLEAR™ 8411C (Lubrizol, 60% MEA Triazine)",
        "OS TRI-SCAV (OSS Ltd., triazine-based H2S scavenger)",
        "BASOLON SC 78 (IRO Chemical, regional distribution)",
        "SINE PF77 (IRO Chemical, regional distribution)",
        "MBBT H2S Scavenger (Muscat & Barka Business Trading)",
        "OOISS Triazine (Oman Oil Industry Supplies & Services)",
        "ICPL Triazine H2S Scavenger (Imperial Oilfield Chemicals, exports to Oman)",
      ],
    },
    {
      heading: "Brand Names Recognized in Egypt",
      items: [
        "ACPA H2S Scavenger (Alexandria Company for Petroleum Additives)",
        "AquaNile H2S Scavenger (Giza/Cairo, ethanolamines for gas treating)",
        "MPC H2S Scavenger (Manufacture of Production Chemicals, Alamia Oil Services Group)",
        "Scomi Egypt drilling chemicals (Scomi Group Bhd)",
        "SULFA-CLEAR™ 8411HC (Lubrizol, distributed to Egypt)",
        "ICG MEA Triazine 40/60/77% (International Chemical Group)",
        "Filtron H2S Scavenger (Filtron Envirotech, India — exports to Egypt)",
        "CACIDE 301 (biodegradable triazine biocide, oilfield use)",
      ],
    },
    {
      heading: "Brand Names Recognized in Brazil",
      items: [
        "Global Trend MEA-Triazina 78% (Rio de Janeiro, local supplier)",
        "SCAVTREAT 1063 (Clariant Oil Services, used in Brazil export treatment)",
        "ABATE™ S-200 Scavenger (Dow Chemical, acid gas removal)",
        "Brenntag MEA / Triazine (Brenntag Química Brasil, São Paulo)",
        "SULFA-CLEAR™ 8411HC (Lubrizol, 80% MEA Triazine)",
        "BerrySweet™ 80% (Berryman Chemical, concentrated triazine)",
        "ICS-5780 (International Chemical Group, 77% MEA Triazine)",
        "SLB Triazine H2S Scavenger (Schlumberger, deepwater operations)",
        "Nalco/Ecolab H2S Scavenger (triazine formulations, Ecolab Brasil)",
        "Foscote MEA (Foscote Group, ethanolamines supplier Brazil)",
      ],
    },
    {
      heading: "Brand Names Recognized in Saudi Arabia",
      items: [
        "Chemara HS-1501 (Saudi Multichem, Dammam — local manufacturer)",
        "G-SCAV Triazine H2S Scavenger 78% (Global Company for Chemical Industries, Jubail)",
        "SUGEST H2S Scavenger (Dammam, Aramco approved vendor #10045611)",
        "CHEMAOIL Triazine (amine-based H2S scavenger, KSA)",
        "NassGuard MEA (oilfield chemicals, Dammam/Jubail)",
        "REPC Triazine (Dammam, serves Saudi Aramco)",
        "UCC Triazine (United Chemical Company, Dammam)",
        "Alkemist KSA MEA (Dammam, Eastern Province wholesale)",
        "SABIC® Monoethanolamine (Jubail — MEA raw material)",
        "DubiChem Triazine Biocide (UAE, distributes to KSA)",
        "Cola®Triazine 50 ME (Colonial Chemical, Middle East)",
        "HME-FILM MEA Triazine (MED Drilling Fluids, GCC)",
      ],
    },
    {
      heading: "Brand Names Recognized in Iraq",
      items: [
        "Tawreed H2S Scavenger (Baghdad, ISO-certified oilfield chemicals)",
        "ALDUHA H2S Scavenger (ALDUHA Engineering Group, Basra)",
        "SAHARA MEA Triazine (SAHARA Middle East Petroleum Services, North Rumaila)",
        "Federal Group / Advanced Chemicals (Erbil, Kurdistan Region warehouse)",
        "Sama Alyarmouk Oilfield Chemicals (Baghdad)",
        "Manar Al-Basra Oilfield Services (Basra, est. 2022)",
        "Petrobon MEA (Petrobon Trading, Iran → Iraq import)",
        "Ishtar MEA (Ishtar Company, petroleum/chemicals, Iran/Iraq)",
        "ATDMCO MEA (ATDM Company, UAE/Turkey → Iraq supply)",
        "TAQA Group Chemicals (Iraq, oil & gas chemical distributor)",
        "Falizan HS-9003 (Falizan Tasfyeh, Iran — triazine H2S scavenger)",
        "Xipeng MEA Triazine 78% (Xipeng Technology, China export)",
      ],
    },
    {
      heading: "Brand Names Recognized in Qatar",
      items: [
        "BKC Gulf Triazine Scavenger (Qatar-focused supplier)",
        "RXSOL Triazine Based Biocide (RXSOL-43-8160-210, DubiChem/RX Marine)",
        "DubiChem Triazine Biocide (distributed to GCC incl. Qatar)",
        "HS-1526-40 (Univar Solutions, global triazine product code)",
        "SULFA-CLEAR™ 8411HC (Lubrizol, 80% MEA Triazine)",
        "SULFA-CLEAR™ 8411C (Lubrizol, 60% MEA Triazine)",
        "ChampionX H2S Scavenger (QatarEnergy-approved)",
        "Baker Hughes H2S Scavenger (QatarEnergy-approved)",
        "Halliburton Triazine (QatarEnergy vendor)",
        "Scavtreat (Schlumberger/SLB proprietary blend)",
        "G-SCAV EA77 (77% active, GCC oilfields)",
        "BASOLON SC 78 (IRO Chemical)",
        "SINE PF77 (IRO Chemical)",
        "ICPL Triazine H2S Scavenger (Imperial Oilfield Chemicals, exports to Qatar)",
        "K2P MEA-T (K2P Chemical Products, monoethanolamine triazine)",
        "Deluxe MEA (Deluxe Trading Services WLL, Qatar — raw MEA, not triazine)",
        "Chemway MEA Triazine (UAE/GCC distribution)",
        "JadeScan54 (Jay Dinesh Chemicals, Indian export)",
      ],
    },
    {
      heading: "Qatar Arabic-Language Names (الأسماء العربية – قطر)",
      items: [
        "كاسح كبريتيد الهيدروجين قطر (H2S Scavenger Qatar)",
        "مورد ترايازين قطر (Triazine Supplier Qatar)",
        "مورد مواد كيميائية لمعالجة الغاز قطر (Gas Treatment Chemical Supplier Qatar)",
        "معالجة الغاز الحامض قطر (Sour Gas Treatment Qatar)",
        "كيماويات حقول النفط قطر (Oilfield Chemicals Qatar)",
        "كاسح H2S حقل الشمال (H2S Scavenger North Field)",
        "مزيل كبريتيد الهيدروجين ترايازين قطر (H2S Remover Triazine Qatar)",
        "مورد كيماويات صناعية الدوحة (Industrial Chemical Supplier Doha)",
      ],
    },
    {
      heading: "Brand Names Recognized in Kuwait",
      items: [
        "Bait Al Aseel H₂S Scavenger – Triazine Based (Shuwaikh, Kuwait)",
        "Bait Al Aseel MEA — Monoethanolamine (Kuwait supplier — raw MEA, not triazine)",
        "DK Petrochemicals MEA (Dar Al Kuwait Petrochemical Company — raw MEA)",
        "RXSOL Triazine Based Biocide (RX Chemicals / DubiChem, GCC distribution)",
        "HME-FILM MEA Triazine (MED Drilling Fluids, GCC oilfield use)",
        "HS-1526-40 (Univar Solutions, global triazine product code)",
        "SULFA-CLEAR™ 8411HC (Lubrizol, 80% MEA Triazine)",
        "ChampionX H2S Scavenger (KOC service contracts)",
        "Baker Hughes H2S Scavenger (KOC service contracts)",
        "Dorf Ketal H2S Scavenger (KOC service contracts)",
        "Triasorb® (Sintez-Oka, Russia — MEA triazine H2S absorber)",
        "ICPL Triazine H2S Scavenger (Imperial Oilfield Chemicals, India)",
        "K2P MEA-T (K2P Chemical Products)",
        "Xipeng MEA Triazine 78% (Xipeng Technology, China export)",
        "G-SCAV EA77 (77% active, GCC oilfields)",
        "Sarex HPT Triazine (Sarex Chemicals, India)",
      ],
    },
    {
      heading: "Kuwait Arabic-Language Names (الأسماء العربية – الكويت)",
      items: [
        "كاسح كبريتيد الهيدروجين الكويت (H2S Scavenger Kuwait)",
        "مورد ترايازين الكويت (Triazine Supplier Kuwait)",
        "مادة إزالة H2S لحقول نفط الكويت (H2S Removal for Kuwait Oilfields)",
        "معالجة الغاز الحامض الكويت (Sour Gas Treatment Kuwait)",
        "كيماويات حقول النفط الكويت (Oilfield Chemicals Kuwait)",
        "كاسح H2S حقل برقان (H2S Scavenger Burgan Field)",
        "مورد كيماويات صناعية الأحمدي (Industrial Chemical Supplier Ahmadi)",
        "مزيل كبريتيد الهيدروجين ترايازين الكويت (H2S Remover Triazine Kuwait)",
      ],
    },
    {
      heading: "Brand Names Recognized in Thailand",
      items: [
        "Brenntag MEA (Brenntag Ingredients Thailand, Bangkok — raw MEA, not triazine)",
        "PTT GC MEA (PTT Global Chemical, Map Ta Phut — Thai raw MEA manufacturer)",
        "Krungthep Trading MEA (Bangkok, Thai raw MEA supplier)",
        "Chemipan MEA (retail chemical supplier, Bangkok)",
        "BK Biocide (Chinese trade name, widely traded in SEA)",
        "Dayong MEA Triazine (Dongying Dayong, China export)",
        "IRO MEA Triazine (IRO Group Inc., China export to SEA)",
        "ECHEMI MEA Triazine 78% (Chinese marketplace)",
        "Borregaard H2S Scavenger (Norway, bio-based scavenger)",
        "HS-1526-40 (Univar Solutions, global triazine product code)",
        "SULFA-CLEAR™ 8411HC (Lubrizol, 80% MEA Triazine)",
        "ChampionX H2S Scavenger (PTTEP service contracts)",
        "JDC H2S Scavenger (Jay Dinesh Chemicals, India)",
        "Xipeng MEA Triazine 78% (Xipeng Technology, China export)",
      ],
    },
    {
      heading: "Thai-Language Names (ชื่อภาษาไทย)",
      items: [
        "สารกำจัด H2S ไตรอะซีน (H2S Scavenger Triazine)",
        "สารดักจับไฮโดรเจนซัลไฟด์ (Hydrogen Sulfide Scavenger)",
        "สารบำบัดก๊าซเปรี้ยว (Sour Gas Treatment Agent)",
        "ผู้ผลิต MEA ไตรอะซีน ประเทศไทย (MEA Triazine Manufacturer Thailand)",
        "สารเคมีขจัด H2S สำหรับแก๊สธรรมชาติ (H2S Removal Chemical for Natural Gas)",
        "เคมีภัณฑ์สำหรับอุตสาหกรรมน้ำมันและแก๊ส (Oil & Gas Industry Chemicals)",
        "สารเคมีขจัดไฮโดรเจนซัลไฟด์ก๊าซชีวภาพ (H2S Removal Chemical for Biogas)",
        "สารดักจับ H2S สำหรับแท่นขุดเจาะอ่าวไทย (H2S Scavenger Gulf of Thailand Rigs)",
      ],
    },
    {
      heading: "Brand Names Recognized in Iran",
      items: [
        "Tsorb3400 (Tasfyeh Group, Iran — MEA Triazine H2S scavenger)",
        "Tasfyeh MEA Triazine 80% (Tasfyeh Group, Iran)",
        "Tasfyeh MEA Triazine 60% (Tasfyeh Group, Iran)",
        "Tasfyeh MEA Triazine 50% (Tasfyeh Group, Iran)",
        "Chemical Iran MEA (Chemical Iran, Tehran — raw MEA supplier)",
        "IranChemicalMine MEA (Iran Chemical Mine — raw MEA exporter)",
        "RXSOL Triazine Based Biocide (RX Chemicals / DubiChem, GCC)",
        "Triasorb® (Sintez-Oka, Russia — supply to Iran)",
        "HS-1526-40 (Univar Solutions, global triazine product)",
        "SULFA-CLEAR™ 8411HC (Lubrizol, 80% MEA Triazine)",
        "ChampionX H2S Scavenger (NIOC service contracts)",
        "Baker Hughes H2S Scavenger (NIOC contractors)",
        "ICPL Triazine H2S Scavenger (Imperial Oilfield Chemicals, India)",
        "Sarex HPT Triazine (Sarex Chemicals, India export)",
      ],
    },
    {
      heading: "Farsi (Persian) Names (نام‌های فارسی)",
      items: [
        "حذف‌کننده H2S تری‌آزین (H2S Scavenger Triazine)",
        "حذف‌کننده سولفید هیدروژن ایران (H2S Scavenger Iran)",
        "تری‌آزین تأمین‌کننده ایران (Triazine Supplier Iran)",
        "تصفیه گاز ترش ایران (Sour Gas Treatment Iran)",
        "مواد شیمیایی صنعتی میدان پارس جنوبی (South Pars Industrial Chemicals)",
        "خرید تری‌آزین MEA ایران (Buy MEA Triazine Iran)",
        "تأمین‌کننده مواد شیمیایی بندرعباس (Chemical Supplier Bandar Abbas)",
        "شیمیایی پالایشگاه اصفهان آبادان (Isfahan Abadan Refinery Chemical)",
      ],
    },
    {
      heading: "Brand Names Recognized in Russia",
      items: [
        "Triasorb® (Sintez-Oka, Dzerzhinsk — Russian H2S absorber, 10,000+ tons/yr)",
        "Triasorb® MMA (Sintez-Oka — methylamine triazine variant)",
        "Sintez-Oka MEA (Dzerzhinsk — raw MEA producer since 1948)",
        "Kazanorgsintez MEA (PAO Kazanorgsintez, Kazan — raw MEA technical grade)",
        "Mirrico H2S Scavenger (Mirrico Group, Kazan — largest Russian oilfield chemical co.)",
        "NIKA-Synthetics Triazine (domestic Russian production)",
        "Himeko Triazine (domestic Russian production)",
        "Elarum MEA (Russian ethanolamine distributor, warehouse delivery)",
        "ILEM MEA (Kazanorgsintez distributor, Kazan — wholesale/retail)",
        "Sinotrust MEA Triazine Biocide (Chinese manufacturer, export to Russia/CIS)",
        "Sinolook MEA (Chinese raw MEA, 99% purity)",
        "HME-FILM (ME Drilling Fluids, triazine-based scavenger)",
        "HS-1526-40 (Univar Solutions, global triazine product)",
        "SULFA-CLEAR™ 8411HC (Lubrizol, 80% MEA Triazine)",
      ],
    },
    {
      heading: "Russian-Language Names (Русские названия)",
      items: [
        "нейтрализатор сероводорода триазин (H2S Neutralizer Triazine)",
        "поглотитель H2S триазин МЭА 78% (H2S Absorbent MEA Triazine 78%)",
        "триазин МЭА поставщик Россия (MEA Triazine Supplier Russia)",
        "удаление сероводорода из природного газа (H2S Removal from Natural Gas)",
        "химический реагент очистка попутного газа (Associated Gas Treatment Reagent)",
        "нейтрализатор H2S нефтегазовая промышленность (H2S Neutralizer Oil & Gas)",
        "осушка и очистка газа триазин (Gas Drying & Purification Triazine)",
        "поставщик химических реагентов из Индии (Chemical Reagent Supplier from India)",
      ],
    },
  ],
  casNote: "CAS: 4719-04-4",
  closingText:
    "If your specification, purchase order, or safety requirement lists any of the above names or the CAS number 4719-04-4, Vasudev Chemo Pharma can supply the matching product. Contact us for confirmation and TDS.",
};

export const MMA_TRIAZINE_SYNONYMS: ProductSynonyms = {
  intro:
    "MMA Triazine 40% may be listed under various names in technical specifications:",
  groups: [
    {
      heading: "Synonyms and Application Names",
      items: [
        "MMA Triazine",
        "MMA based Triazine",
        "1,3,5-Triazine (MMA variant)",
        "Monomethylamine Triazine",
        "H2S Scavenger (MMA type)",
        "Hydrogen Sulfide Scavenger",
        "Triazine biocide",
        "Industrial biocide for water treatment",
        "Formaldehyde condensate biocide",
      ],
    },
  ],
  closingText:
    "Contact us if your specification lists any of these names — we will confirm whether our MMA Triazine 40% matches your requirement.",
};
