const fs = require('fs');
const path = require('path');

const rawInput = `h2s scavenger 78 manufacturer in INDIA
monoethanolamine-triazine supplier in india
monoethanolamine triazine india
H2S Scavengers & Triazine-Based Gas Treatment Chemicals
MEA Triazine 70%
mea triazine manufacturers in india
mea triazine 78 suppliers in india
triazine manufacturer in india
water treatment biocide
Triazine Based H₂S scavenger Manufacturer
mea triazine by kwantum india
mea triazine
h2s scavenger manufacturer in INDIA
h2s scavenger
water based biocide
Biocides for metalworking fluids
Tacelene chem 62090
jadescan 54
Tacelene chem 62087
Tacelene chem 62081
monoethanolamine triazine
amine base triazine
cas no. 4719-04-4
biocide used as h2s scavenger
Triazine Based H2S Scavenger Manufacturer
oil drilling fluids
HSCAV- 70
nipacide bk`;

const baseKws = [...new Set(rawInput.split('\n').map(k => k.trim()).filter(Boolean))];

const infoTemplates = [
  'what is {kw}',
  'how does {kw} work',
  '{kw} technical data sheet',
  '{kw} safety data sheet',
  '{kw} chemical properties',
  'application guide for {kw}',
  'benefits of using {kw}',
  '{kw} mechanism of action',
  'industrial uses for {kw}',
  '{kw} formulation details'
];

const buyTemplates = [
  'buy {kw} online',
  'wholesale {kw}',
  '{kw} bulk price',
  'best price for {kw}',
  'order {kw} direct from factory',
  'reliable {kw} supplier',
  '{kw} quotation request',
  'top supplier of {kw}',
  '{kw} for sale',
  'import {kw}'
];

const researchTemplates = [
  '{kw} vs alternatives',
  'compare {kw} brands',
  'is {kw} the best choice',
  '{kw} specifications',
  'equivalent to {kw}',
  'reviews of {kw} suppliers',
  '{kw} concentration levels',
  '{kw} testing methods',
  '{kw} market analysis',
  'best {kw} for industrial use'
];

let generated = [];
baseKws.forEach(kw => {
  infoTemplates.forEach(t => generated.push(t.replace('{kw}', kw)));
  buyTemplates.forEach(t => generated.push(t.replace('{kw}', kw)));
  researchTemplates.forEach(t => generated.push(t.replace('{kw}', kw)));
});

const targetFile = 'src/lib/product-seo-keywords.ts';
let content = fs.readFileSync(targetFile, 'utf8');

const insertMarker = '      // ── Russia competitor brand keywords ───────────────';
const index = content.indexOf(insertMarker);

if (index !== -1) {
  const newText = '      // ── Autogenerated Intent Variations ───────────────\n' + 
                  generated.map(g => '      "' + g + '",').join('\n') + '\n\n';
  
  content = content.slice(0, index) + newText + content.slice(index);
  fs.writeFileSync(targetFile, content);
  console.log('Successfully injected ' + generated.length + ' keywords!');
} else {
  console.log('Could not find insert marker.');
}
